### ISSUE TITLE
OpenSees installation

### ISSUE THREAD

**Issue by petrasvestartas** [zhuminjie/OpenSeesPyDoc#1]
Do I need to install opensees software itself or only  openseespy file?

**Comment by zhuminjie** [comment]
only openseespy file

**Comment by petrasvestartas** [comment]
Thank you for a reply.

But when I try to import this file. In Spyder.
The file is not imported. When I press opensees. no autocomplete is running:

Do you know why?

![link](https://user-images.githubusercontent.com/18013985/36617473-d581fd7a-18e7-11e8-9438-d1f632cb0794.png)

**Comment by zhuminjie** [comment]
I guess Spyder only auto complete built-in libraries. I'm not an expert on Spyder. To import the opensees, you need set the 'path/to/OpenSeesPy/' the real path in your computer

sys.path.append('C:/path/to/OpenSeesPy')

in your case

**Comment by zhuminjie** [comment]
The ipython will autocomplete the opensees, see

![image](https://user-images.githubusercontent.com/6202967/36617884-04d9cd90-189e-11e8-8549-b5a9ed461280.png)

**Comment by khaledissam** [comment]
please ,Ph.D / Minjie Zhu

I want to More Tsunami examples for your Program 

I'm very sorry for the inconvenience, Professor

Your student  Khaled Issam
