### ISSUE TITLE
(Windows) pvd recorder - 'wrap by vector' error with 6 degrees of freedom

### ISSUE THREAD

**Issue by marcozord** [zhuminjie/OpenSeesPyDoc#10]
When I use pvd recorder in order to display the model and the deformed shape all the paraview feature work except the "wrap by vector" function. This happens only if the model is defined with 6 DOF because paraview doesn't recognize the displacement as a vector given that the displacement has 6 elements instead of 3.

**Comment by zhuminjie** [comment]
I am ware of the problem. Not sure a quick way to fix it.

**Comment by zhuminjie** [comment]
I use the "wrap by vector" function a lot for 2D beams. There should be no problem for 2D. For 3D, since paraview doesn't recognize the rotational dof for beams, that's not a problem of pvd recorder. I am going to close this issue unless further discussion can be made.
