### ISSUE TITLE
I can parallel a transient analysis in linux?

### ISSUE THREAD

**Issue by Zawarud** [zhuminjie/OpenSeesPyDoc#100]
I should do a seismic analysis in step and in parallel apply 7 bidirectional earthquakes according to EuroCode2.
Should I follow the example of parametric analysis?
Which analysis parameters should I use (simple example) in my case?
Im using this command : 
`mpiexec -np 7 python transient.py`

**Comment by zhuminjie** [comment]
You look for an example for parallel computing in openseespy?

**Comment by Zawarud** [comment]
In my case, if I run the serial analysis( 7 bidirectional earthquakes )  I use the same amount of time as doing it with the mpiexec command. Although the getPID () command detects the different COREs of the CPU the times are identical. So I wanted to see if I was doing something wrong.
The parameter analisys are : 

```
system('Umfpack')
constraints('Penalty', 1.0e+14, 1.0e+10)
numberer('ParallelRCM')
test( 'NormDispIncr', 1.0e-12, 10, 0)
algorithm('NewtonLineSearch')
integrator('HHT', 0.9 )
analysis('Transient')
```
Where is the problem?

**Comment by mhscott** [comment]
https://www.youtube.com/watch?v=vjGm2kM5Ihc
