### ISSUE TITLE
How can i add a new material into Openseesy?

### ISSUE THREAD

**Issue by PLYH1314** [zhuminjie/OpenSeesPyDoc#101]

**Comment by mhscott** [comment]
Please give more description of where you are in the process.  Are you starting from zero?  Have you coded the material and now want to add it to the OpenSeesPy interpreter?  Other details?

**Comment by erkanbicici** [comment]
Actually, I am working on same question. 
Previously, I have developed a new uniaxial material in OpenSees. I have c++ code. I have created .dll file and used it in OpenSees. (I also did same thing in Mac and Ubuntu with make command.)
 However, I could not use my new material in OpenSeespy. Thus, I could not swicth to openseespy.
If it is possible to include new materail in openseespy, it would be great for me.

Thank you for your help.

**Comment by zhuminjie** [comment]
To include in OpenSeesPy, you will need to add your new material to SRC/interpreteer/OpenSeesUniaxialMaterialCommands.cpp

**Comment by erkanbicici** [comment]
Thank you for your response.
I have pip installed openseespy. There is no such files in directory. 
From your response, I have undersood that I need to download the source code from github.com/OpenSees/OpenSees, and include my code inside of SRC/interpreteer/OpenSeesUniaxialMaterialCommands.cpp and compile OpenSees from beginning (with Visual Studio).

**Comment by zhuminjie** [comment]
Right, actually, you need compile the OpenSeesPy project in Visual Studio.
