### ISSUE TITLE
Arguments for eleResponse() command for a zeroLengthSection element

### ISSUE THREAD

**Issue by pp4** [zhuminjie/OpenSeesPyDoc#102]
Hi Minjie,

I'm trying to get the stress-strain curve in a specific fibre of a zeroLengthSection element using the eleResponse() command.
In this case, I assumed that the arguments for the eleResponse() command are: 'element tag'; 'section tag'; 'fibre coordinates'; and 'stress', 'strain', or 'stressStrain' (based on the last example in [https://opensees.berkeley.edu/OpenSees/manuals/usermanual/1214.htm](https://opensees.berkeley.edu/OpenSees/manuals/usermanual/1214.htm)).

The output that I get (i.e. `fibre_stressStrain`) from the code below is actually very plausible, but the eleResponse() command seems to ignore the 'section tag' and the 'fibre coordinates'.
Regardless of what I specify in `secTag` and `fibre_coords`, the output doesn't change.

```
eleTag        = 1                  # element tag
secTag        = 1                  # section tag
fibre_coord_y = 100.0              # fibre y-coordinate
fibre_coord_z = 100.0              # fibre z-coordinate
fibre_coords  = [fibre_coord_y,    # fibre y- and z-coordinates
                 fibre_coord_z]
responseType  = 'stressStrain'

fibre_stressStrain = op.eleResponse(eleTag,               # element tag
                                    'section', secTag,    # section tag
                                    fibre_coords,         # fibre y- and z-coordinates
                                    responseType)         # response type
```

Are my input arguments wrong?
I've tried different arguments (e.g. `'fiber', *fibre_coords`,  `'fiber', fibre_coords`,  `'-fiber', *fibre_coords`), but the results are either unplausible or empty lists.

Many thanks and
all the best,
Pedro

**Comment by pavan1388** [comment]
Hello Pedro,

I was able to get the "stressStrain" output successfully by using the below syntax lines: 

stressStrain = op.eleResponse(eleTag, "section", sectag, "-fiber", "y" , "z", "mattag", "stressStrain")

you can try these input arguments and check if it is working in your code. Just FYI, the final output is in the form of a list [stress, strain].

Regards,
Pavan Chigullapally.

**Comment by pp4** [comment]
Hi Pavan, 

You are right: input arguments must be strings; and  y- and z- coordinates are specified separately.
However, the argument `'-fiber'` that you used, it does not work for me (I'm using OpenSeesPy 0.5.8).

I get a correct output with the following input arguments (`matTag` is optional):
```
eleTag        = 1                  # element tag
secTag        = 1                  # section tag
fibre_coord_y = 100.0              # fibre y-coordinate
fibre_coord_z = 100.0              # fibre z-coordinate
matTag        = 1                  # material tag
responseType  = 'stressStrain'

fibre_stressStrain = op.eleResponse(eleTag,               # element tag
                                    'section', secTag,    # section tag
                                    str(fibre_coord_y),   # fibre y-coordinate
                                    str(fibre_coord_z),   # fibre z-coordinate
                                    str(matTag),          # material tag
                                    responseType)         # response type
```

I guess this can be marked as "solved".

Many thanks,
Pedro

**Comment by zhuminjie** [comment]
For the eleResponse, everythone after eleTag has to be strings. This is just how OpenSees works internally.

**Comment by pavan1388** [comment]
Hello Pedro, 

I am glad it worked. Yes the command provides results for nearest material to the coordinates. I guess it is kept that way as it is really hard to give exact coordinates sometimes. Also the version I am in is 0.5.10. So may be things changed a little or may be for zerolength it is that way? I am not sure. 

Regards, 
Pavan Chigullapally.

**Comment by mhscott** [comment]
This has been resolved and you no longer need to make everything a string

**Comment by pp4** [comment]
Thank you! 

Unfortunately, eleResponse() is not returning any output: neither 'stressStrain', neither an error message. 
I am using version 3.4.0 of OpenSeesPy. 

Does anyone else experience this issue?

**Comment by pp4** [comment]
Thank you!

Unfortunately, eleResponse() is not returning any output: neither 'stressStrain', neither an error message.
I am using version 3.4.0 of OpenSeesPy.

Does anyone else experience this issue?

**Comment by mhscott** [comment]
Please show the command line you are using

**Comment by mhscott** [comment]
If you are using zeroLengthSection, you should remove the 'secTag' from the eleResponse command. The secTag is not required.

**Comment by pp4** [comment]
Many thanks for the quick reply.

Yes, I am using a _zeroLengthSection_.
I have tried various combinations of arguments, including removing the `secTag` argument (like you suggested) and also not converting the arguments to strings (as also mentioned above), but I still get no output from `op.eleResponse()`. 

The rest of the script seems to be working because the moment-curvature curve I get is plausible. 
But before, i.e. about two years ago, I was also able to get stress-strain for fibres. 

```
eleTag        = 1                 # (int)   element tag (in this case, the element is actually a zero-length section)
secTag        = 1                 # (int)   section tag
fibre_coord_y = 0.0               # (float) fibre y-coordinate
fibre_coord_z = 100.0             # (float) fibre z-coordinate
matTag        = 1                 # (int)   material tag
responseType  = 'stressStrain'    # (str)   response type
        
fibre_stressStrain = op.eleResponse(eleTag,                # (int) element tag
                                    'section', secTag,     # (int) section tag
                                    str(fibre_coord_y),    # (str) fibre y-coordinates
                                    str(fibre_coord_z),    # (str) fibre z-coordinates
                                    str(matTag),           # (str) material tag
                                    responseType)          # (str) response type
```

**Comment by pp4** [comment]
Solved! 
By looking at the `recorder()` arguments in an [example in your blog *](https://portwooddigital.com/2021/07/25/how-to-record-fiber-response/), the arguments of  `eleResponse( )` became clear.

To get fibre stress and strain when using a _zeroLengthSection_ element, `eleResponse( )` can be used with following arguments: 
```
ops.eleResponse(eleTag,            # (int) element tag
                'section', 
                'fiber',          
                fibre_coord_y,     # (value or str) fibre y-coordinates
                fibre_coord_z,     # (value or str) fibre z-coordinates
                matTag,            # (int) material tag
                'stressStrain')    # (str) response type
```

I hope this solution also helps others. 
All the best, 
Pedro

(* the [Portwood Digital](https://portwooddigital.com/) blog is really good and extremely helpful. Thank you for your blog posts.)
