### ISSUE TITLE
TwoNodeLink arguments error ?

### ISSUE THREAD

**Issue by ArchDH** [zhuminjie/OpenSeesPyDoc#103]
Dear Dr.Zhu

I have encountered an error while using the 'twoNodeLink' element. Is there any line of code that I typed wrong here?. I am currently using Anaconda3 2019.10 and Python 3.7.
Thank you for this brilliant platform. Openseespy is very helpful for everyone in my lab.

import openseespy.opensees as ops

#Modeling
ops.model('basic', '-ndm', 2, '-ndf', 3)
ops.node(1, 0,  0)
ops.node(2, 0., 1)
ops.fix(1, 1, 1, 1)
ops.fix(2, 0, 1 , 1)
ops.mass(2, 100, 0, 0)
ops.uniaxialMaterial('Elastic', 1, 1e3)
ops.element('twoNodeLink', 1, 1, 2, '-mat', 1, 1, 1, '-dir', 1, 2, 3)

#Define Analysis
ops.timeSeries('Linear', 1)
ops.pattern('Plain', 1, 1)
ops.load(2, 1, 0, 0)
ops.system('BandGeneral')
ops.numberer('Plain')
ops.constraints('Transformation')
ops.algorithm('Newton')
ops.integrator('DisplacementControl', 2 , 1, 0.1)
ops.analysis('Static')
ops.analyze(1)

>> **WARNING expecting -dir dirs
Traceback (most recent call last):
  File "DIRECTORY", line 10, in <module>
    ops.element('twoNodeLink', 1, 1, 2, '-mat', 1, 1, 1, '-dir', 1, 2, 3)
opensees.OpenSeesError: See stderr output**

**Comment by mgrubisic** [comment]
It works fine for me. Try using the unpacking operator to list the directions of twoNodeLink element `* [1, 2, 3]`. And beware of the input values that should be integers versus those that should be floating point values. Good luck!

```
import opensees as ops

ops.wipe()

# Modeling
ops.model('basic', '-ndm', 2, '-ndf', 3)
ops.node(1, 0.0, 0.0)
ops.node(2, 0.0, 1.0)
ops.fix(1, 1, 1, 1)
ops.fix(2, 0, 1, 1)
ops.mass(2, 100.0, 0.0, 0.0)
ops.uniaxialMaterial('Elastic', 1, 1.0E3)
ops.element('twoNodeLink', 1, 1, 2, '-mat', *[1, 1, 1], '-dir', *[1, 2, 3])

# Define Analysis
ops.timeSeries('Linear', 1)
ops.pattern('Plain', 1, 1)
ops.load(2, 1.0, 0.0, 0.0)
ops.system('BandGeneral')
ops.numberer('Plain')
ops.constraints('Transformation')
ops.algorithm('Newton')
ops.integrator('DisplacementControl', 2, 1, 0.1)
ops.analysis('Static')

for i in range(0, 10):
    ops.analyze(1)
    print(ops.nodeDisp(2))
```

**Comment by ArchDH** [comment]
I've also found this error in 'twoNodeLink' element when using 'MultiLinear' material with. 

This Works with 'zeroLength' perfectly, 
---------------------------------------------------------
ops.wipe()
ops.model('basic', '-ndm',2, '-ndf', 3)
ops.node(1, 0., 0.)
ops.node(2, 0., 0.)
ops.mass(2, 1., 1., 1.)
ops.fix(1, 1, 1, 1)
ops.fix(2, 0, 1, 1)
ops.uniaxialMaterial("MultiLinear", 3, 0.01, 100, 0.05, 150, 0.1, 175)
ops.element('twoNodeLink', 1, 1, 2, '-mat', 3, 3, 3, '-dir', 1, 2, 3)
print("model is constructed")

ops.wipeAnalysis()
ops.timeSeries('Linear', 1)
ops.pattern('Plain', 1, 1)
ops.load(2, 30., 0., 0.)
ops.system('ProfileSPD')
ops.numberer('RCM')
ops.constraints('Plain')
ops.algorithm('Newton')
ops.integrator('LoadControl', 0.1)
ops.analysis('Static')
data = np.zeros((100, 2))
for i in range(100):
    data[i, 0] = ops.nodeDisp(2, 1)
    data[i, 1] = ops.eleForce(1, 1)
    ops.analyze(1)

![Figure_1](https://user-images.githubusercontent.com/22149162/69871517-5b39f080-12f6-11ea-9562-cfffd7b87350.png)
Figure 1 is the result of the code above.
----------------------------------------------------------------
But this doesn't work but outputs errors
ops.wipe()
ops.model('basic', '-ndm',2, '-ndf', 3)
ops.node(1, 0., 0.)
ops.node(2, 0., 0.)
ops.mass(2, 1., 1., 1.)
ops.fix(1, 1, 1, 1)
ops.fix(2, 0, 1, 1)
ops.uniaxialMaterial("MultiLinear", 3, 0.01, 100, 0.05, 150, 0.1, 175)
ops.element('twoNodeLink', 1, 1, 2, '-mat', 3, 3, 3, '-dir', 1, 2, 3)
print("model is constructed")

ops.wipeAnalysis()
ops.timeSeries('Linear', 1)
ops.pattern('Plain', 1, 1)
ops.load(2, 30., 0., 0.)
ops.system('ProfileSPD')
ops.numberer('RCM')
ops.constraints('Plain')
ops.algorithm('Newton')
ops.integrator('LoadControl', 0.1)
ops.analysis('Static')
data = np.zeros((100, 2))
for i in range(100):
    data[i, 0] = ops.nodeDisp(2, 1)
    data[i, 1] = ops.eleForce(1, 1)
    ops.analyze(1)

>> **WARNING: CTestNormUnbalance::test() - failed to converge 
after: 25 iterations  current Norm: 200 (max: 1e-06, Norm deltaX: 0.4)
NewtnRaphson::solveCurrentStep() -the ConvergenceTest object failed in test()
StaticAnalysis::analyze() - the Algorithm failed at iteration: 0 with domain at load factor 0.1**

**Comment by ArchDH** [comment]
> It works fine for me. Try using the unpacking operator to list the directions of twoNodeLink element `* [1, 2, 3]`. And beware of the input values that should be integers versus those that should be floating point values. Good luck!
> 
> ```
> import opensees as ops
> 
> ops.wipe()
> 
> # Modeling
> ops.model('basic', '-ndm', 2, '-ndf', 3)
> ops.node(1, 0.0, 0.0)
> ops.node(2, 0.0, 1.0)
> ops.fix(1, 1, 1, 1)
> ops.fix(2, 0, 1, 1)
> ops.mass(2, 100.0, 0.0, 0.0)
> ops.uniaxialMaterial('Elastic', 1, 1.0E3)
> ops.element('twoNodeLink', 1, 1, 2, '-mat', *[1, 1, 1], '-dir', *[1, 2, 3])
> 
> # Define Analysis
> ops.timeSeries('Linear', 1)
> ops.pattern('Plain', 1, 1)
> ops.load(2, 1.0, 0.0, 0.0)
> ops.system('BandGeneral')
> ops.numberer('Plain')
> ops.constraints('Transformation')
> ops.algorithm('Newton')
> ops.integrator('DisplacementControl', 2, 1, 0.1)
> ops.analysis('Static')
> 
> for i in range(0, 10):
>     ops.analyze(1)
>     print(ops.nodeDisp(2))
> ```

This works well for me too! Thanks for your advice :)

**Comment by ArchDH** [comment]
Plus, this code gives me an interesting result too.

[3] -----------------------------------------------------------------
import numpy as np
import openseespy.opensees as ops
import matplotlib.pyplot as plt

ops.wipe()
ops.model('basic', '-ndm',2, '-ndf', 3)
ops.node(1, 0., 0.)
ops.node(2, 0., 1.)
ops.mass(2, 1., 1., 1.)
ops.fix(1, 1, 1, 1)
ops.fix(2, 0, 1, 1)
ops.uniaxialMaterial("MultiLinear", 3, *[0.1, 100., 0.5, 150., 1., 175.])
ops.element('twoNodeLink', 1, 1, 2, '-mat', *[3, 3, 3], '-dir', *[1, 2, 3])
print("model is constructed")

ops.wipeAnalysis()
ops.timeSeries('Linear', 1)
ops.pattern('Plain', 1, 1)
ops.load(2, 1., 0., 0.)
ops.system('ProfileSPD')
ops.numberer('RCM')
ops.constraints('Plain')
ops.algorithm('Newton')
ops.integrator('DisplacementControl', 2, 1, 0.1)
ops.analysis('Static')
data = np.zeros((20, 2))
for i in range(20):
    data[i, 0] = ops.nodeDisp(2, 1)
    data[i, 1] = ops.eleForce(1, 1)
    ops.analyze(1)
    
x, y = data.T
plt.plot(x, y)
plt.grid(True)
plt.tight_layout()
plt.show()

![Figure_2](https://user-images.githubusercontent.com/22149162/69872048-c1734300-12f7-11ea-8fb6-683395e5d90f.png)

**Comment by zhuminjie** [comment]
The problem seems due to an internal bug, not the syntax.
