### ISSUE TITLE
eleload output error

### ISSUE THREAD

**Issue by maxs3** [zhuminjie/OpenSeesPyDoc#105]
Hi Dr. Zhu

When I use the eleload command with a 'beamUniform' type loading, I get the error "ElasticBeam2d::addLoad()  -- load type unknown for element with tag:", however when I look at the resulting forces it seems to be doing the correct thing. Not sure if the error output is itself an error, or if I am doing something incorrect. I have attached my test script. Note that I was originally using this script to test Joint2D, so that is in there.
[Joint2D_Check.zip](https://github.com/zhuminjie/OpenSeesPyDoc/files/3914281/Joint2D_Check.zip)

Thanks,

Max

**Comment by sewkokot** [comment]
This bug has been fixed in OpenSees and and also is fixed now in openseespy-0.5.10.

https://github.com/OpenSees/OpenSees/commit/e2d257e4f2f9ee578cb2006c07a035f3dc057c2e
https://github.com/OpenSees/OpenSees/pull/171

**Comment by maxs3** [comment]
I am using 0.5.10 and the error is still there.

**Comment by zhuminjie** [comment]
I will make sure it is included in the next release.
