### ISSUE TITLE
Versions of Python

### ISSUE THREAD

**Issue by ghost** [zhuminjie/OpenSeesPyDoc#106]
Dear Dr.zhu,

Only Python 3.7 can be used to do opensees analysis ?

**Comment by zhuminjie** [comment]
For Windows, Yes. Because it is burdensome to maintain different versions for Python 3.5,3.6,3.7,3.8, which unfortunately are needed for Windows. Indeed, you can run Linux Shell on Windows 10

https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by Albertmajian** [comment]
Thanks 
but I found the version of 0.5.5 could work in python 3.6, what's a difference.

**Comment by zhuminjie** [comment]
In the earlier version, python3.6 is supported, but since anaconda upgraded to python3.7, we support 3.7 now.
