### ISSUE TITLE
How to define Pinching4 material?

### ISSUE THREAD

**Issue by ghost** [zhuminjie/OpenSeesPyDoc#107]
"op.uniaxialMaterial('Pinching4',3, 4.267343,0.031207,4.268413,0.052062,4.271372,0.083336,[-4.267343,-0.031207,-4.268413,-0.052062,-4.271372,-0.083336],0.5, 0.25, 0.05,[0.5, 0.25, 0.05], 0.0, 0.1, 0.0, 0.0, 0.2,0.0, 0.1, 0.0, 0.0, 0.2, 0.0, 0.4, 0.0, 0.4, 0.9, 10,'energy')"
Pinching4 define like this ? or other style?

**Comment by Albertmajian** [comment]
uniaxialMaterial('Pinching4',9, 4.267343, 0.031207,4.268413,0.052062,4.271372,0.083336,5.070524,0.180030,-4.267343,-0.031207,-4.268413,-0.052062,-4.271372,-0.083336,-5.070524,-0.180030,0.5, 0.25, 0.05,0.5, 0.25, 0.05, 0.0, 0.1, 0.0, 0.0, 0.2,0.0, 0.1, 0.0, 0.0, 0.2, 0.0, 0.4, 0.0, 0.4, 0.9, 10.0,'energy')
when I delete the '[]' this founction could work but it differnet with the style of the founction, what's wrong ? 
Thanks!

**Comment by zhuminjie** [comment]
You cannot use list directly in function, it will be recognized as one parameter. The second one is correct.
