### ISSUE TITLE
(Windows) Can't define geomTransf in 3D for use in elasticBeamColumn 3D

### ISSUE THREAD

**Issue by canadiancastor** [zhuminjie/OpenSeesPyDoc#11]
In trying to define geomTransf as I would do in Tcl opensees:
`ops.geomTransf("Linear", 1, 1.0, 0.0, 0.0)`
`SystemError: <built-in function geomTransf> returned NULL without setting an error`

**Comment by zhuminjie** [comment]
Have you set 

model('basic','-ndm',3,'-ndf',6)

I don't have problem with this command.

**Comment by canadiancastor** [comment]
You are right, I had forgot to put my degrees of freedom to 6. Closed issue.
