### ISSUE TITLE
Text input in to Time series command for dynamic analysis

### ISSUE THREAD

**Issue by pavan1388** [zhuminjie/OpenSeesPyDoc#110]
Hello Dr. Zhu,

I am trying to input the ground motion in the form of text files in my model and OpenSeesPy error message says it cannot open the text file. Although the same model runs with different ground motion input formats. I did not have these issues before upgrading my OpenSeesPy to version 0.5.10, this issue started only after upgrading. 

I also tested the same on the Earthquake example files from the OpenSeesPy website (https://openseespydoc.readthedocs.io/en/latest/src/cantuni.html) and faced the same issue.  I have attached a simple sine wave text file I used in the analysis. 

OpenSees shows the below error for text input: 
op.timeSeries('Path', 2, '-dt', dt,'-filePath', 'sine wave.txt,  '-factor', GMfatt)
WARNING - PathSeries::PathSeries() - could not open file 

[sine wave.txt](https://github.com/zhuminjie/OpenSeesPyDoc/files/3937964/sine.wave.txt)

Can you please take a look at the issue and fix it.

Thank you,
Pavan Chigullapally.

**Comment by zhuminjie** [comment]
There is nothin change for the pathseries. I notice there is a space in the file name. Could you try to remove it?

**Comment by pavan1388** [comment]
Yes, it works fine when I have filenames without spaces.

It is weird as OpenSeesPy was able to read the files with spaces before I upgraded to the current version. Thanks for the help. 

Regards,
Pavan.
