### ISSUE TITLE
unsupported operand type(s) for ** or pow(): 'list' and 'float'

### ISSUE THREAD

**Issue by volkanozsarac** [zhuminjie/OpenSeesPyDoc#114]
Dear Dr. Zhu,

I was trying the examples that you have provided. Unfortunately, I am getting the following error when I run the first example. There error is here:

setting damping based on first eigen mode
freq = ops.eigen('-fullGenLapack', 1)**0.5
dampRatio = 0.02
ops.rayleigh(0., 0., 0., 2*dampRatio/freq)

How may I solve this issue? Thank you a lot

**Comment by mhscott** [comment]
The eigen command was recently changed to return a list of values.  Try this

w2 = ops.eigen('-fullGenLapack',1)
freq = w2[0]**0.5
dampRatio = 0.02
ops.rayleigh(0., 0., 0., 2*dampRatio/freq)


________________________________

**Comment by volkanozsarac** [comment]
Thank you for the reply Dr. Scott
