### ISSUE TITLE
cannot run on macOS 10.15.2

### ISSUE THREAD

**Issue by qyan327** [zhuminjie/OpenSeesPyDoc#119]
openseespy 0.5.10 failed running on macOS 10.15.2 with an error message of _Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)_.

**Comment by zhuminjie** [comment]
You may want to contact Stevan Gavrilovic (steva44@hotmail.com), who maintain the mac version. Thank you!

**Comment by qyan327** [comment]
Thank you!
