### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by warlockwarchief** [zhuminjie/OpenSeesPyDoc#120]
Dear Dr. Zhu
First, Thanks for your sustainable supports. Then, I have a problem when I want to use the command  **_import_** in designsafe 
when i write: _import openseespy.opensees as ops_
I face this error
Please guide me
![Import](https://user-images.githubusercontent.com/53867979/72419216-9b174300-3791-11ea-9427-7df195bc3b12.PNG)

**Comment by zhuminjie** [comment]
It looks like DesignSafe is missing the libblas.so.3 file. I will add this file to openseespy. Thanks.

**Comment by mhscott** [comment]
It might be worth submitting a ticket to DesignSafe to let them know the library is missing.

**Comment by zhuminjie** [comment]
Yes, that's an even better idea

**Comment by warlockwarchief** [comment]
Thanks Professors...
