### ISSUE TITLE
nonlinearBeamColumn in 3D model error message

### ISSUE THREAD

**Issue by ezrapogoda** [zhuminjie/OpenSeesPyDoc#123]
Initially I have specified all the elements in my 3D model as elasticBeamColumn elements and the code was running, however, now I am trying to change the elements to nonlinearBeamColumn elements and while I have specified all the necessary information I am getting an error saying "ndm must be 2 and ndf must be 3". I can't seem to find a solution for this. Is it possible that this element is only specified for 2D models in the python module? Because when looking at the tcl examples they also use this element in 3D models.
Thanks for the help and I am happy to share my code if necessary.

**Comment by mhscott** [comment]
Are you using 6 DOFs/node

model('basic','-ndm',3,'-ndf',6)?

--
Michael H. Scott, Ph.D.
Professor, Structural Engineering
Oregon State University
cce.oregonstate.edu/scott<https://cce.oregonstate.edu/scott>
OpenSees blog: portwooddigital.com<http://www.portwooddigital.com/>
________________________________

**Comment by ezrapogoda** [comment]
Yes, I do.

**Comment by mhscott** [comment]
Would you mind sharing your script so that we can take a look?

Thanks,

Michael


________________________________

**Comment by ezrapogoda** [comment]
The building I am trying to model is a bit more complex so I hope the sticht is not too confusing! 
Let me know if you have any questions. Thanks!
[Code.zip](https://github.com/zhuminjie/OpenSeesPyDoc/files/4118140/Code.zip)

**Comment by mhscott** [comment]
It looks like the Python interpreter is only checking ndm 2 and ndf 3 for nonlinearBeamColumn.  I will update it to allow ndm 3 and ndf 6.

In the meantime, you should use 'forceBeamColumn' instead of 'nonlinearBeamColumn'.  It's the same element formulation and it takes the same inputs.

But, what you're doing with these lines of code is unclear.  I think you just want to pass nodeTag1 and nodeTag2 to the element.  The coordinates are invalid inputs.

iNode = nodeCoord(nodeTag1)
jNode = nodeCoord(nodeTag2)
element(Type, eleTag, iNode, jNode, numIntgrPts, ColSecTag, TransfTagCol)

Michael

________________________________

**Comment by ezrapogoda** [comment]
Brilliant, that works. Thanks a lot!

**Comment by ezrapogoda** [comment]
I continue getting the following type of error when using the forceBeamColumn:

`WARNING - ForceBeamColumn3d::update - failed to get compatible element forces & deformations for element: 1(dW: << -nan, dW0: -nan)`

I assume this error results from my defined RC section. However, after checking this I can't find a mistake. 

When I use dispBeamColumn instead the element construction works. I just run into a convergence error.

**Comment by mhscott** [comment]
You will need to look more closely at your model and why it’s not converging.  Time step, element definitions, loads, etc.  Did you do verification tests to make sure it’s working or just go to a large nonlinear model and hope for the best? ☺

**Comment by ezrapogoda** [comment]
Ok, I will take another look. Initially, I used the elasticBeamColumn element which worked fine. I thought I could just replace the element type.

**Comment by mhscott** [comment]
Try using elastic uniaxial materials for the fiber sections and see if you get about the same results as with elasticBeamColumn.

**Comment by ezrapogoda** [comment]
Thanks so much. I was able to find my mistakes and get the model running. To complete my model I am trying to add rigid diaphragms as floor systems. I have added them for one floor to test it and I am given the attached error messages. I tried to follow one of the 3D examples on the opensees website and also tried different analysis types but it does not seem to work...
```
---------------------------------------------------------------------------
msg                                       Traceback (most recent call last)
msg: WARNING: numeric analysis returns 1 -- Umfpackgenlinsolver::solve


---------------------------------------------------------------------------
msg                                       Traceback (most recent call last)
msg: WARNING NewtonRaphson::solveCurrentStep() -the LinearSysOfEqn failed in solve()


---------------------------------------------------------------------------
msg                                       Traceback (most recent call last)
msg: StaticAnalysis::analyze() - the Algorithm failed at iteration: 0 with domain at load factor 0.1


---------------------------------------------------------------------------
msg                                       Traceback (most recent call last)
msg: OpenSees > analyze failed, returned: -3 error flag
```
