### ISSUE TITLE
Issue With Parallel Material

### ISSUE THREAD

**Issue by volkanozsarac** [zhuminjie/OpenSeesPyDoc#126]
_Dear Dr. Zhu and Dr. Scott,_

_I believe there might be an issue with Parallel Material. Please do correct me if I am wrong._
_I wanted to test ElasticPPGap material._
_For this reason I created two materials in Parallel, ElasticPPGap and Elastic._

_1) Initial stiffness should be equal to the stiffness of Elastic material_
_2) After the gap is exceeded stiffness is the summation of two materials_
_3) After ElasticPPGap yields, the stiffness of the element must be equal to the stiffness of Elastic_ _Material._
_When I plot the results, I only see a linear plot, which shows the behavior of the Elastic material._

**Here is my .py file:**

import matplotlib.pyplot as plt
import openseespy.opensees as op
import numpy as np

op.wipe()
op.model('basic', '-ndm', 1, '-ndf', 1)

Fy = 500
gap = 0.02
E1 = 10000
E2 = 0.01*E1

op.uniaxialMaterial('ElasticPPGap', 1, E1, Fy, gap, 0, 'damage')
op.uniaxialMaterial('Elastic', 2, E2)

op.node(1, 0); op.node(2, 0);
op.uniaxialMaterial('Parallel', 3, 1,2)
op.element('zeroLength', 1, 1, 2, '-mat', 3, '-dir', 1)

op.fix(2,1)

op.recorder('Node', '-file', 'NodeDisp.txt', '-time', '-node', 1, '-dof', 1, 'disp')
op.recorder('Element', '-file', 'EleForce.txt', '-time','-ele', 1, 'deformation') # force

Dmax = 500/E1*1.2
Dincr = 1e-4
maxNumIter = 6
Tol = 1e-8

op.timeSeries('Linear', 1)
op.pattern('Plain', 1, 1)
op.load(1, 1)

op.wipeAnalysis()
op.constraints('Plain')
op.numberer('Plain')
op.system('BandGeneral')
op.test('EnergyIncr', Tol, maxNumIter)
op.algorithm('Newton')
op.integrator('DisplacementControl', 1, 1, Dincr)
op.analysis('Static')

Nsteps =  int(Dmax/ Dincr)

ok = op.analyze(Nsteps)
print(ok)

test = {1:'NormDispIncr', 2: 'RelativeEnergyIncr', 4: 'RelativeNormUnbalance',5: 'RelativeNormDispIncr', 6: 'NormUnbalance'}
algorithm = {1:'KrylovNewton', 2: 'SecantNewton' , 4: 'RaphsonNewton',5: 'PeriodicNewton', 6: 'BFGS', 7: 'Broyden', 8: 'NewtonLineSearch'}

for i in test:
    for j in algorithm:

        if ok != 0:
            if j < 4:
                op.algorithm(algorithm[j], '-initial')
                
            else:
                op.algorithm(algorithm[j])
                
            op.test(test[i], Tol, 1000)
            ok = op.analyze(Nsteps)                            
            print(test[i], algorithm[j], ok)             
            if ok == 0:
                break
        else:
            continue

op.wipe()

history = np.loadtxt('NodeDisp.txt')
plt.plot(history[:,1],history[:,0])

![Figure_1](https://user-images.githubusercontent.com/46993652/73679916-a1774b80-46bb-11ea-8f3d-8db808a8410e.png)

**Comment by mhscott** [comment]
Did you close the issue because you resolved the issue?  What was the error?

**Comment by volkanozsarac** [comment]
Sorry, I was not sure, if it was because I use DisplacementControl as an integrator. I Closed it for that reason. But the result was the same with LoadControl

**Comment by mhscott** [comment]
Do you get the same results if you switch the order of inputs from 1,2 to 2,1 for the materials in the parallel material command?  What happens when you make the gap equal to zero?

**Comment by volkanozsarac** [comment]
Unfortunately, nothing has changed

**Comment by mhscott** [comment]
Is it a sign issue?  The springs are in compression but the gap is on the tension side.  Try changing the direction of the load to tension.

**Comment by volkanozsarac** [comment]
Thanks a lot! This was the issue
