### ISSUE TITLE
Analysis can't run in Linux Bash for Windows 10

### ISSUE THREAD

**Issue by lucafranco** [zhuminjie/OpenSeesPyDoc#13]
Hello everyone, I'm sorry in advance if the problems I'm exposing here are obvious for someone, but I'm quite new to Python language, and I can't find useful informations in the web. I'm having some issues in running OpenSeesPy in _Ubuntu bash for Windows 10_. Particularly, I'm trying to run the elastic truss analysis example found in the official documentation  ([https://openseespydoc.readthedocs.io/en/latest/truss.html](url)) . Python 3.7.0 is installed. I've installed the interpreter in both the way explained in the guideline:

1. through the library file opensses.so file, and I appended the path where the .so file is located; in my case it is:

    `sys.path.append('/home/luca/openseespylinux/nfs/stak/users/zhum/public_html/linux')` 

2. though PyPi ([https://openseespydoc.readthedocs.io/en/latest/pypi.html](url))

Anyway, it seems that **Python isn't able to recognize the OpenSees library**, since when i launch the analysis, the following error appears:

`NameError: name 'wipe' is not defined`

So it means that the typical OpenSees command to build models aren't recognized by Python.

Thanks in advance for any help, since I've no idea of how to solve the problem.

**Comment by zhuminjie** [comment]
can you post your script?

**Comment by lucafranco** [comment]
This is the script (that in my PC is located at the following path: _C:\Users\gufo8\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\LocalState\rootfs_):

`import sys`
`sys.path.append('/home/luca/openseespylinux/nfs/stak/users/zhum/public_html/linux')`
`from openseespy import *`
`import numpy as np`
`import matplotlib.pyplot as plt`
`wipe()`
`model('basic', '-ndm', 2, '-ndf', 2)`
`node(1, 0.0, 0.0)`
`node(2, 144.0,  0.0)`
`node(3, 168.0,  0.0)`
`node(4,  72.0, 96.0)`
`fix(1, 1, 1)`
`fix(2, 1, 1)`
`fix(3, 1, 1)`
`uniaxialMaterial("Elastic", 1, 3000.0)`
`element("Truss",1,1,4,10.0,1)`
`element("Truss",2,2,4,5.0,1)`
`element("Truss",3,3,4,5.0,1)`
`timeSeries("Linear", 1)`
`pattern("Plain", 1, 1)`
`load(4, 100.0, -50.0)`
`system("BandSPD")`
`numberer("RCM")`
`constraints("Plain")`
`integrator("LoadControl", 1.0)`
`algorithm("Linear")`
`analysis("Static")`
`analyze(1)`
`ux = nodeDisp(4,1)`
`uy = nodeDisp(4,2)`
`if abs(ux-0.53009277713228375450)<1e-12 and abs(uy+0.17789363846931768864)<1e-12:`
`    print("Passed!")`
`else:`
`    print("Failed!")`

At the path _C:\Users\gufo8\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\LocalState\rootfs\home\luca\openseespylinux\nfs\stak\users\zhum\public_html\linux_ I have located 3 files:

1. LICENSE.rst
2. opensees.so
3. opensees.pyd (this one because I initially supposed that the error was due to the fact that I'm running a Linux bash in a Windows 10 OS)

The error that appears in the bash is:

`luca@Dell-Luca:/$ sudo python3 ElasticTruss_Edited.py
Traceback (most recent call last):
  File "ElasticTruss_Edited.py", line 17, in <module>
    wipe()
NameError: name 'wipe' is not defined`

**Comment by zhuminjie** [comment]
Since you downloaded the opensees.pyd. You need import opensees instead of openseespy

from opensees import * 

let me know if that fixes the problem

**Comment by lucafranco** [comment]
I think that now OpenSees is recognized by Python, but now there is a new problem I can't solve. If fact the following error appears:

`Traceback (most recent call last):`
`  File "ElasticTruss_Edited.py", line 7, in <module>`
`    from opensees import *`
`ImportError: libpng15.so.15: cannot open shared object file: No such file or directory`

If i try to force anaconda to install a previous version of libpng, the following error appears:

`luca@Dell-Luca:/$ conda install libpng=1.5.13`
`Solving environment: failed`
`UnsatisfiableError: The following specifications were found to be in conflict:`
`  - anaconda==5.3.0=py37_0 -> pango==1.42.4=h049681c_0 -> cairo[version='>=1.14.12,<2.0a0'] -> fontconfig[version='>=2.12.6,<3.0a0'] -> freetype[version='>=2.8,<2.9.0a0'] -> libpng[version='>=1.6.32,<1.7.0a0']`
`  - libpng=1.5.13`
`Use "conda info <package>" to see the dependencies for each package.`

Sincerely I've found nothing useful to solve this problem.

**Comment by zhuminjie** [comment]
libpng15 was required for the Linux version, but not for windows version. I just updated the download to remove the dependency.

**Comment by lucafranco** [comment]
OK thanks. Where is the new download package? At the old link ([http://web.engr.oregonstate.edu/~zhum/openseespy.zip](url)) there is an empty zip

**Comment by zhuminjie** [comment]
Same link, I just update it.

**Comment by lucafranco** [comment]
Just put the updated files (both the .so and .pyd) into the above-mentioned path, but the problem of libpng remains :/

**Comment by zhuminjie** [comment]
![image](https://user-images.githubusercontent.com/6202967/46968497-376f0900-d068-11e8-8f54-04e93fa82b5f.png)

It shows that libpng is not in the list of dependency. I never used the linux bash for windows. Are you using .so or .pyd?

**Comment by lucafranco** [comment]
I have put both the updated versions of .pyd and .so file in the directory written in the script 
(`sys.path.append('/home/luca/openseespylinux/nfs/stak/users/zhum/public_html/linux')`
Since I'm importing the library with the command
`from opensees import *`
I suppose I'm using only the .pyd file anyway.
Maybe the problem is due to the way the Ubuntu bash for Windows 10 works.

**Comment by zhuminjie** [comment]
Yes, that's something I am confusing. Is the Ubuntu bash a way to run Linux binary and libraries or just a simulator of Linux? Would you be able to try in a real Linux system?

**Comment by lucafranco** [comment]
What I have found on a blog about this bash:

 It's not an emulator in the same way that WINE Is Not an Emulator. That is to say, they've added a Linux kernel interface to their Windows kernel. When an app tries to use the Linux kernel, it gets translated into a Windows native system call and any responses from the kernel is translated into a native Linux response. So the app thinks it's running on a Linux kernel and hence doesn't need to be modified.

Anyway yes, I think I can try tomorrow or this weekend.

**Comment by zhuminjie** [comment]
@lucafranco Any updates for Bash in Windows? Are you able to run in a native Linux?

**Comment by zhuminjie** [comment]
@frqc Thanks for your post! I am going to close this issue.
