### ISSUE TITLE
WARNING element type elastomericBearingBoucWen is unknown

### ISSUE THREAD

**Issue by volkanozsarac** [zhuminjie/OpenSeesPyDoc#131]
Hi.

I am getting warning for element type 'elastomericBearingBoucWen'. Is the element implemented?

Thanks

**Comment by zhuminjie** [comment]
Yes, I can see it is in the element command

**Comment by mhscott** [comment]
Please describe the warning in more detail and show the input command you used.

**Comment by volkanozsarac** [comment]
Here is the code;

import openseespy.opensees as op
op.wipe() # This command is used to destroy all constructed objects, i.e. all components of the model, all components of the analysis and all recorders.
op.model('basic', '-ndm', 3, '-ndf', 6) # Define the model builder, ndm=#dimension, ndf=#dofs

SmallMat = 1
op.uniaxialMaterial('Elastic', SmallMat, 1e-5)
BigMat = 2
op.uniaxialMaterial('Elastic', BigMat, 1e8)

op.node(1,0,0,0); op.fix(1,1,1,1,1,1,1)
op.node(2,0,0,0);

Kinit	= 1352
Fb		= 100
alpha1	= 0.01
alpha2	= 0.0
mu		= 0.0
eta	= 1.0
beta = 0.5
gamma = 0.5    
op.element('elastomericBearingBoucWen',	1, 1, 2, Kinit, Fb, alpha1, alpha2, mu, eta, beta, gamma, '-P', BigMat, '-T', SmallMat, '-My', SmallMat, '-Mz', SmallMat, '-orient', 0, 0, 1, 1, 0, 0)

whereas the following is the error I am getting
![image](https://user-images.githubusercontent.com/46993652/74858279-527d1780-5345-11ea-8ab1-f4cb0a00e1a9.png)

**Comment by mhscott** [comment]
Thank you for the information.  It looks like you’ve found an error in the input!  I’ll update the OpenSees source code.  Try your script with a capital “E” to see if it works in the meantime.

Michael

functionMap.insert(std::make_pair("ElastomericBearingBoucWen", &OPS_ElastomericBearingBoucWen));

**Comment by volkanozsarac** [comment]
Thank you!
