### ISSUE TITLE
Eigen Recorder

### ISSUE THREAD

**Issue by volkanozsarac** [zhuminjie/OpenSeesPyDoc#134]
Dear Dr. Zhu and Dr. Scott,

I was trying to use recorders to get the eigenvectors. However, when I use the recorders, it gives me any empy file. I have tried to get the eigenvectors for "3DFrame_Rendering.py" example.

In the following you can find my code. Could you please tell me if there is a problem in my expression or if it s another issue. 
Best Regards,

from openseespy.postprocessing.Get_Rendering import * 
from openseespy.opensees import *

import numpy as np

from math import asin, sqrt

# set some properties
wipe()

model('Basic', '-ndm', 3, '-ndf', 6)

# properties, units kip, ft

numBayX = 2
numBayY = 2
numFloor = 7

bayWidthX = 120.0
bayWidthY = 120.0
storyHeights = [162.0, 162.0, 156.0, 156.0, 156.0, 156.0, 156.0, 156.0, 156.0, 156.0, 156.0]

E = 29500.0
massX = 0.49
M = 0.
coordTransf = "Linear"  # Linear, PDelta, Corotational
massType = "-lMass"  # -lMass, -cMass

nodeTag = 1

# add the nodes, - floor at a time
zLoc = 0.
for k in range(0, numFloor + 1):
	xLoc = 0. 
	for i in range(0, numBayX + 1):
		yLoc = 0.
		for j in range(0, numBayY + 1):
			node(nodeTag, xLoc, yLoc, zLoc)
			mass(nodeTag, massX, massX, 0.01, 1.0e-10, 1.0e-10, 1.0e-10)
			if k == 0:
				fix(nodeTag, 1, 1, 1, 1, 1, 1)
				
			yLoc += bayWidthY
			nodeTag += 1
			
		xLoc += bayWidthX

	if k < numFloor:
		storyHeight = storyHeights[k]
	
	zLoc += storyHeight

# add column element
geomTransf(coordTransf, 1, 1, 0, 0)
geomTransf(coordTransf, 2, 0, 0, 1)

eleTag = 1
nodeTag1 = 1

for k in range(0, numFloor):
	for i in range(0, numBayX+1):
		for j in range(0, numBayY+1):
			nodeTag2 = nodeTag1 + (numBayX+1)*(numBayY+1)
			iNode = nodeCoord(nodeTag1)
			jNode = nodeCoord(nodeTag2)
			element('elasticBeamColumn', eleTag, nodeTag1, nodeTag2, 50., E, 1000., 1000., 2150., 2150., 1, '-mass', M, massType)
			eleTag += 1
			nodeTag1 += 1

nodeTag1 = 1+ (numBayX+1)*(numBayY+1)
#add beam elements
for j in range(1, numFloor + 1):
	for i in range(0, numBayX):
		for k in range(0, numBayY+1):
			nodeTag2 = nodeTag1 + (numBayY+1)
			iNode = nodeCoord(nodeTag1)
			jNode = nodeCoord(nodeTag2)
			element('elasticBeamColumn', eleTag, nodeTag1, nodeTag2, 50., E, 1000., 1000., 2150., 2150., 2, '-mass', M, massType)
			eleTag += 1
			nodeTag1 += 1
		
	nodeTag1 += (numBayY+1)

nodeTag1 = 1+ (numBayX+1)*(numBayY+1)
#add beam elements
for j in range(1, numFloor + 1):
	for i in range(0, numBayY+1):
		for k in range(0, numBayX):
			nodeTag2 = nodeTag1 + 1
			iNode = nodeCoord(nodeTag1)
			jNode = nodeCoord(nodeTag2)
			element('elasticBeamColumn', eleTag, nodeTag1, nodeTag2, 50., E, 1000., 1000., 2150., 2150., 2, '-mass', M, massType)
			eleTag += 1
			nodeTag1 += 1
		nodeTag1 += 1

# calculate eigenvalues & print results
numEigen = 7
**for i in range(numEigen):**
	**fname = "Mode" + str(i+1)+".txt"**
	**mode = "eigen " + str(i)**
	**recorder('Node', '-file', fname, '-node', nodeTag2, '-dof', 1, mode)**
**record**
eigenValues = eigen(numEigen)
PI = 2 * asin(1.0)

plot_modeshape(5)
plot_model()
wipe()

**Comment by u-anurag** [comment]
While you are still waiting, there is a workaround. Add the following code to your model file. This will record the **NodeTag** and the corresponding **eigenVector** in DOF 1 to respective files. Here a function nodeEigRecorder is defined to record eigenvectors of a node to an output file. The input arguments (and their order) of this function are nodeTag (int), "filename", EigenVector (int) and -dof (int). You call this function in a loop to record various eigenvectors.

```
numEigen = 7
eigenValues = eigen(numEigen)
 
def nodeEigRecorder(nodeTag, filename, eigenVector, dof):
    with open(filename, 'w+') as f_out:
        f_out.write(str(nodeTag)+" "+str(nodeEigenvector(nodeTag, eigenVector, dof))+" \n")
    f_out.close()
 
for i in range(1,numEigen):
    fname = "Mode" + str(i+1)+".txt"
    # mode = "eigen " + str(i)
    # recorder('Node', '-file', fname, '-node', 70, '-dof', 1, mode)
    nodeEigRecorder(nodeTag2, fname, i, 1)
 ```

**Comment by volkanozsarac** [comment]
Thanks a lot! This method works perfectly.
