### ISSUE TITLE
AttributeError: module 'openseespy.opensees' has no attribute 'wipe'

### ISSUE THREAD

**Issue by MrAlex8** [zhuminjie/OpenSeesPyDoc#137]
Dear Dr. Zhu,
When I tried to use the openseespy package using the following code:

`# import OpenSeesPy
import openseespy.opensees as ops`

`# wipe model
ops.wipe()`

I got the following error:

`AttributeError: module 'openseespy.opensees' has no attribute 'wipe'`

I am using Win10 (x64)+ Anaconda 3.5.3.1. My Python version is 3.6.9. I have ActiveTcl-8.5.18.0 installed.

Any suggestions please? Thanks a lot for your time!

**Comment by mcoar** [comment]
Are you sure that openseespy package is installed?
In anaconda:
pip install openseespy
In command line:
python -m pip install openseespy

https://openseespydoc.readthedocs.io/en/latest/src/pypi.html

**Comment by mcoar** [comment]
Also, it looks like only python 3.7 is supported:
https://github.com/zhuminjie/OpenSeesPyDoc/issues/106

**Comment by u-anurag** [comment]
Are you using Miniconda3 instead of full Anaconda? Some of my colleagues had this problem when using Miniconda3, even with python 3.7.

**Comment by MrAlex8** [comment]
Python 3.7 was the missing piece. Thanks all!
