### ISSUE TITLE
"parameter" syntax

### ISSUE THREAD

**Issue by mcoar** [zhuminjie/OpenSeesPyDoc#139]
Good morning, 

I'm just trying to understand how to use the parameter commands to identify the modulus of elasticity of an element.
I am using dispBeamColumnThermal elements and steel01thermal material.
I am using the following parameter callout (for example):

Etag = 1
parameter(Etag,'element',5,'E')

I keep on getting the following error:
Parameter::addComponent 1 -- no objects were able to identify parameter
E 

I have used a variety of parameter names: 'E0','Fy', ['material',matTag,'E'], etc. Nothing seems to be working. The page for the syntax references .tcl code, and doesn't seem complete. https://openseespydoc.readthedocs.io/en/latest/src/parameter.html 

when I call out the specific element, section and material -addToParameter(Etag,'element',el,'section',sec,'material',matTag,'E') - I don't get an error but then updateParameter(Etag, newEvalue) doesn't seem to change the material response. 
[pinned.txt](https://github.com/zhuminjie/OpenSeesPyDoc/files/4306678/pinned.txt)

Any help would be appreciated. Thank you

**Comment by mhscott** [comment]
The thermal elements/sections/materials probably don’t have setParameter and updateParameter implemented.  I’ll take a look.

**Comment by mcoar** [comment]
Thank you very much. I appreciate your time.
