### ISSUE TITLE
Notebook Azure

### ISSUE THREAD

**Issue by ahmetanildindar** [zhuminjie/OpenSeesPyDoc#14]
Dear all,
OpensSeesPy is great. I've been using in my computer locally.  
![image](https://user-images.githubusercontent.com/3111609/46890393-62dad380-ce6f-11e8-8ac2-c07eef1b1a9a.png)

I want to run OpenSeesPy in Azure Notebooks. Azure Notebooks is a free cloud service that runs Python. 

However,  the following is the screenshot where I have not proceeded any further :(

![image](https://user-images.githubusercontent.com/3111609/46888844-543ded80-ce6a-11e8-914f-15991ab16220.png)

Has anybody tried or tested OpenSeesPy in Notebooks Azure? 

Regards from Istanbul.

++Ahmet

**Comment by zhuminjie** [comment]
I cannot see any problems in the screen shot. What is the problem do you have?

**Comment by ahmetanildindar** [comment]
The problem is that Notebooks Azure do not respond :( The notebook freezes as seen in the screenshot. 

BTW, Python kernel is 3.6 in my Notebook.

**Comment by zhuminjie** [comment]
![image](https://user-images.githubusercontent.com/6202967/46966362-6c785d00-d062-11e8-98a8-b167cb812577.png)


I tried the Azure notebook. It seems working for me.

**Comment by ahmetanildindar** [comment]
I see it is running. That is good because it means using OpenSeespy in Azure is possible :+1: 

On the other hand, is it possible commenting about the warning message in the figure below?

![image](https://user-images.githubusercontent.com/3111609/47109063-f0df0180-d255-11e8-99c2-8bc330fad0f6.png)

For better reading, see below. 

```
nbuser@nbserver:~/library/openseespy$ python36
Python 3.6.6 |Anaconda custom (64-bit)| (default, Jun 28 2018, 17:14:51)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import opensees
Segmentation fault
nbuser@nbserver:~/library/openseespy$
```
Than, the question becomes what "segmentation fault" means? I've googled but results are not igniting in this folk's mind.

Any suggestion?

++Ahmet

**Comment by ahmetanildindar** [comment]
That's bizarre.

Anyway, I've seen that it works in Azure. For sure, I'll look for the solution in Azure. 

But, just before closing the issue, what about DesignSafe?

![image](https://user-images.githubusercontent.com/3111609/47111961-a1043880-d25d-11e8-83d2-82984509dbcf.png)

Another issue :(

**Comment by zhuminjie** [comment]
The team in DesignSafe is working on including OpenSeesPy. Before it is officially done, you can do following,

1. launch jupyter on designsafe; 
2. open a terminal;
3. type: pip3 install openseespy -- user 

After that you can create a new jupyter notebook and it will work!  But you need import openseespy as

import openseespy.opensees as ops

ops.model(...)

**Comment by ahmetanildindar** [comment]
Cool, I'll check it immediately.

**Comment by zhuminjie** [comment]
Thank you! I am going to close this issue. If you find other issues about Designsafe, please open another one.
