### ISSUE TITLE
Is there any way to add own material in openseespy?

### ISSUE THREAD

**Issue by mtsonicc** [zhuminjie/OpenSeesPyDoc#140]
Hi.
On windows, there is an instruction about adding own material model.
The example is show in (https://opensees.berkeley.edu/wiki/index.php/Adding_your_own_code_to_OpenSees,_Jan_2012).
I wonder if there's an equivalent way to add own material in opensees python.
I'm using OpenSees on macOS Catalina and Windows 10.
Any help or advice would be appreciated.

**Comment by zhuminjie** [comment]
You can create a material model and submit a pull request to [OpenSees](https://github.com/OpenSees/OpenSees)

**Comment by mtsonicc** [comment]
@zhuminjie 
Thanks for your reply!
Is there any solution other than submitting a pull request?
I hoped that I could add a material using opensees.pyd..

**Comment by zhuminjie** [comment]
what do you mean? you want to compile your own opensees.pyd?

**Comment by mtsonicc** [comment]
Thank you for your reply. 
No, compiling my own opensees.pyd is not necessary.

I think I understand your reply now.
If I need to develop my own material model, it is recommended to develop and test the model in tcl-based OpenSees (for the case of Windows system, OpenSees.EXE with CustomMaterial.DLL).
If developing the material model is completed, submit a pull request and wait for OpenSeesPy to merge it.
Did i get it right?

**Comment by zhuminjie** [comment]
You may want to develop your material in C++ and submit PR to OpenSees, then the material will be part of OpenSee. Everyone can use it, no more DLL.

**Comment by mhscott** [comment]
I agree.  DLLs are way too restrictive and complicated.  Submitting the source code as a PR works best.

**Comment by mtsonicc** [comment]
Thank you all for your kind instructions.
