### ISSUE TITLE
Issue with numpy.int64 data types

### ISSUE THREAD

**Issue by nicclemett** [zhuminjie/OpenSeesPyDoc#142]
Related to my previous post about the section aggregator command...

The material tags used in the 'Aggregator' command were type 'np.int64' and the command was crashing my analysis and IPython console with no warning. Using the int() command to change the material tag types to a standard python 'int' type solves this issue.

In other instances where the int64 type is not an acceptable input a warning and error message are generated. You can reproduce the message by creating an element tag, eTag = np.int64(1), and trying to create a forceBeamColumn element.

**Comment by zhuminjie** [comment]
The np.int64 is not a built-in type. All integer inputs in OpenSeesPy are of the built-in int type. Thank for pointing that out. If you have a np.int64 type, need to convert it first.

**Comment by zhuminjie** [comment]
Regarding the warnings, this command returns if a non-int type is provided. I will add a warning in that case.

**Comment by zhuminjie** [comment]
It will be updated in the next version
