### ISSUE TITLE
displacement of 'beamColumElement'

### ISSUE THREAD

**Issue by DomenicoGaudioso** [zhuminjie/OpenSeesPyDoc#143]
Hello,I have a problem.
I would like to take the displacement of 'beamColumElement' along the length of the item and not just at the nodal location of the element.
Is it possible ? 
Do I have to create the shape function ? 
Is there any built - function inside OpenSees?

Thanks

**Comment by mhscott** [comment]
There is no such recorder option.  Your best bet is to create a mesh of elements along the member and record the nodal displacements.

Michael

--
Michael H. Scott, Ph.D.
Professor, Structural Engineering
Oregon State University
cce.oregonstate.edu/scott<https://exmail.oregonstate.edu/owa/redir.aspx?C=_F2i-PfJ4o6PTa3_ZQo4PE-QjaGSDCPQO_2ZTY0wP-CV6RK6qknXCA..&URL=https%3a%2f%2fcce.oregonstate.edu%2fscott>
OpenSees blog: portwooddigital.com<https://exmail.oregonstate.edu/owa/redir.aspx?C=RsSqkQx_bVLdtoYw647MW5oapuJIB618wYXBdJ4ymaiV6RK6qknXCA..&URL=http%3a%2f%2fwww.portwooddigital.com%2f>
________________________________

**Comment by DomenicoGaudioso** [comment]
Thanks Michael, i can try create mesh of element.
Domenico.
