### ISSUE TITLE
Displacement in local axis

### ISSUE THREAD

**Issue by DomenicoGaudioso** [zhuminjie/OpenSeesPyDoc#144]
Hello.
I am trying to get the displacement of a beam that it is not oriented in the global coordinate.

i.e. 45 degree in xy plane

opensees.nodeDisp() gives me a vector that it is in the global coordinate. Is there anyway to have this result in the local coordinate of the beam?
Do I have to built my own function?

Domenico

**Comment by mhscott** [comment]
You will have to do this yourself.  The nodes do not know anything about the orientation of the connected beams.

--
Michael H. Scott, Ph.D.
Professor, Structural Engineering
Oregon State University
cce.oregonstate.edu/scott<https://exmail.oregonstate.edu/owa/redir.aspx?C=_F2i-PfJ4o6PTa3_ZQo4PE-QjaGSDCPQO_2ZTY0wP-CV6RK6qknXCA..&URL=https%3a%2f%2fcce.oregonstate.edu%2fscott>
OpenSees blog: portwooddigital.com<https://exmail.oregonstate.edu/owa/redir.aspx?C=RsSqkQx_bVLdtoYw647MW5oapuJIB618wYXBdJ4ymaiV6RK6qknXCA..&URL=http%3a%2f%2fwww.portwooddigital.com%2f>
________________________________

**Comment by DomenicoGaudioso** [comment]
Thanks , I imagine that I have to do the same for the forces ( Nx, Vy, Vz, Mx, My, Mz ).

**Comment by sewkokot** [comment]
@DomenicoGaudioso if you wait a few days, I will send here a python library for plotting deformed frames (see example plot below) and other finite element meshes based on OpenSeesPy calculations. This library also calculates element interpolated shape based on node displacement vectors. I need some time to clean up the code before sending it.

 https://imgur.com/a/5b6nJni.png

**Comment by mhscott** [comment]
No, you can get the local forces from the elements.

________________________________
