### ISSUE TITLE
HingeRadau and HingeRadauTwo integration scheme definitions swapped?

### ISSUE THREAD

**Issue by nicclemett** [zhuminjie/OpenSeesPyDoc#145]
Hi,
Whilst attempting to define a beam element with end hinges I noticed a discrepancy between the documentation and implementation of the 'HingeRadau' and 'HingeRadauTwo' integration schemes for forceBeamColumn elements.

The 'HingeRadau' scheme documentation says hinges are located at the end of the hinge and 2*Lp/3 (where Lp is the length of the plastic hinge). Link: https://openseespydoc.readthedocs.io/en/latest/src/HingeRadau.html
 However, when I use this scheme and query the locations of the integration points they are located at 0.0 and 8*Lp/3.

When using 'HingeRadauTwo' the integration points should be located at 0.0 and 8*Lp/3, instead they are located at 0.0 and 2*Lp/3. Link: https://openseespydoc.readthedocs.io/en/latest/src/HingeRadauTwo.html

I think the definitions just need to be swapped in the docs to match what is written here: https://opensees.berkeley.edu/wiki/images/a/ab/IntegrationTypes.pdf

**Comment by zhuminjie** [comment]
Thanks  @mhscott  for fixing it!

#146
