### ISSUE TITLE
Inconsistency of nonlinearBeamColumn

### ISSUE THREAD

**Issue by frqc** [zhuminjie/OpenSeesPyDoc#15]
When creating element in type of nonlinearBeamColumn, the python interpreter expects "eleTag,iNode,jNode,transfTag,integrationTag", which is not the [same](http://opensees.berkeley.edu/OpenSees/manuals/usermanual/637.htm) in the manual v2.0. 

I think the primary reason is in [SRC/interpreter/OpenSeesElementCommands.cpp,](https://github.com/OpenSees/OpenSees/blob/master/SRC/interpreter/OpenSeesElementCommands.cpp#L533) the "nonlinearBeamColumn" is directly aligned with &OPS_ForceBeamColumn

`	functionMap.insert(std::make_pair("nonlinearBeamColumn", &OPS_ForceBeamColumn));
`

Considering many tcl examples use this command, will this be fixed soon?

**Comment by zhuminjie** [comment]
We will work on it and let you know when it is fixed. Thank you!

**Comment by zhuminjie** [comment]
I have added the nonlinearBeamColumn in Python. Check OpenSeesPy update later.
