### ISSUE TITLE
Concrete Shear Wall

### ISSUE THREAD

**Issue by ezrapogoda** [zhuminjie/OpenSeesPyDoc#155]
Hey, 

I am currently trying to model a concrete shear wall. Initially, I tried to model it based on the following developed element [http://www.luxinzheng.net/download/OpenSEES/En_THUShell_OpenSEES.htm](url).
As PSUMAT is not available this, unfortunately, is not an option [https://github.com/zhuminjie/OpenSeesPyDoc/issues/73](url).

I have now used the ShellMITC4 element together with a PlateFiber section and ElasticIsotrophic nDMaterial, however, I would like to use some sort of concrete material to obtain the nonlinear behaviour. I believe only nDMaterials can be used for this, is that correct? Do you have any recommendations regarding which nDMaterial may be used or if there is even an option? 

Regards,
Ezra

**Comment by zhuminjie** [comment]
As shown in https://openseespydoc.readthedocs.io/en/latest/src/ShellMITC4.html,

the section currently must be either a 'PlateFiberSection', or 'ElasticMembranePlateSection'

**Comment by mhscott** [comment]
If I understand correctly, @ezrapogoda is looking for NDMaterial concrete models to use with PlateFiberSection because PSUMAT is not available.

**Comment by mhscott** [comment]
@ezrapogoda, can you use
OpenSees/SRC/material/nD/reinforcedConcretePlaneStress/ReinforcedConcretePlaneStress.cpp
in conjunction with
OpenSees/SRC/material/nD/PlateFromPlaneStress.cpp

I haven't tried any of the concrete materials for shells, but this might be a good place to start.

**Comment by u-anurag** [comment]
Can we add _PlasticDamageConcretePlaneStress_ material to OpenSeesPy? It works with OpenSees Tcl (binary and compiled on Linux) but shows "unknown material" with OpenSeesPy. The results of _PSUMAT_ and _PlasticDamageConcretePlaneStress_ are very close.

OpenSees/SRC/material/nD/PlasticDamageConcretePlaneStress.cpp

**Comment by zhuminjie** [comment]
I can take a look

**Comment by zhuminjie** [comment]
> Can we add _PlasticDamageConcretePlaneStress_ material to OpenSeesPy? It works with OpenSees Tcl (binary and compiled on Linux) but shows "unknown material" with OpenSeesPy. The results of _PSUMAT_ and _PlasticDamageConcretePlaneStress_ are very close.
> 
> OpenSees/SRC/material/nD/PlasticDamageConcretePlaneStress.cpp

I have added the material. Do you have document for that material?

**Comment by zhuminjie** [comment]
I add the material in the Doc. If you have manual, could you please add it?

**Comment by u-anurag** [comment]
Thanks! I'll add it.
