### ISSUE TITLE
difference between Quad4 and MITC element

### ISSUE THREAD

**Issue by Marco-Pellegrino** [zhuminjie/OpenSeesPyDoc#159]
Hi there.
I am looking to run an analyses with 2d element such a shell.
What's the main difference between **Quad4** and **MITC**?

I would like to have an element that can be use for "shear wall" and "slab".

Do they both have bending stiffness?

Best,
Marco

**Comment by Marco-Pellegrino** [comment]
Hi @mhscott @zhuminjie do you have any suggestion?

**Comment by mhscott** [comment]
Quad4 is a 2D element that handles only in plane stresses.  ShellMITC4 is a 3D element that handles in plane and out of plane stresses.  If you are looking to model shear walls and slabs, use ShellMITC4.
