### ISSUE TITLE
How to use the inerter emelent in the OpenSeesPy

### ISSUE THREAD

**Issue by kangjianfei** [zhuminjie/OpenSeesPyDoc#162]
I am glad to find that the inerter element has been included in the OpenSeesPy(version 3.1.5.12). However, how to use this component makes me very confused. The hint when using the inerter does not seem to correspond to the current code in Github.I tried many times but still couldn't use it successfully.
The hint of using the inerter and the current source code of the inerter in Github are:
![1](https://user-images.githubusercontent.com/48382725/78263846-0ec92080-7535-11ea-8602-7d74041e7ee2.JPG)
![2](https://user-images.githubusercontent.com/48382725/78263853-11c41100-7535-11ea-9127-5e931a4f25ba.JPG)
Because I don't have enough understanding of the source code, I hope to get a help document on how to use the inerter.

**Comment by zhuminjie** [comment]
You might be able to call with 

dirs = []
ib = []
len(ib) should be len(dirs)*len(dirs)
ops.element('inerter', eleTag, iNode, jNode,'-dir', *dirs, '-inertance')

**Comment by kangjianfei** [comment]
> You might be able to call with
> 
> dirs = []
> ib = []
> len(ib) should be len(dirs)*len(dirs)
> ops.element('inerter', eleTag, iNode, jNode,'-dir', *dirs, '-inertance')
Thank you very much for your reply.
But I still get errors when using the inerter. I'm very troubled. I've attached the simple example I used here. Can you help me see what the problem is? Thank you very much for your help.`
![3](https://user-images.githubusercontent.com/48382725/78297570-6467f200-7562-11ea-9df4-ce1cace1119c.JPG)

The text code is :
[text.zip](https://github.com/zhuminjie/OpenSeesPyDoc/files/4423401/text.zip)
`

**Comment by kangjianfei** [comment]
Tn the OpenSeesPy(version 3.2.0), this bug has been fixed. Thanks for your help. @zhuminjie
