### ISSUE TITLE
nDMaterial PressureDependMultiYield03 Currently Missing from OSpy

### ISSUE THREAD

**Issue by ajmakdisi-uw** [zhuminjie/OpenSeesPyDoc#164]
I'm a relatively new OpenSees and openseespy user, so I'm not entirely sure if this is an issue on my end or with the openseespy library, but a more recent version of one of the UC San Diego soil models, referred to as PressureDependMultiYield03, was implemented in OpenSees about 11 months ago (per github, but currently doesn't appear to be callable in OpenSeesPy. 

[https://opensees.berkeley.edu/wiki/index.php/PressureDependMultiYield03_Material
](https://opensees.berkeley.edu/wiki/index.php/PressureDependMultiYield03_Material
)
`nDMaterial('PressureDependMultiYield03',2,massDen, refG, refB, frictionAng, peakShearStrain,refPress,pressDependCoe,phaseTransAng,0,contraction_a,contraction_b,contraction_c,contraction_d,contraction_e,dilation_a,dilation_b,dilation_c,noYieldSurf,liqParam1,liqParam2,pa,S0)`

yields the error message: 

`WARNING material type PressureDependMultiYield03 is unknown`

**Comment by zhuminjie** [comment]
I will take a look

**Comment by ajmakdisi-uw** [comment]
> I will take a look

Thanks for the quick response! Let me know if you need any more information from me.

**Comment by zhuminjie** [comment]
I just added the material. It will be in the next pip version.
