### ISSUE TITLE
Obtaining Mass Matrix

### ISSUE THREAD

**Issue by volkanozsarac** [zhuminjie/OpenSeesPyDoc#165]
Dear Dr. Zhu and Dr. Scott,

I was wondering if it is possible to obtain mass matrix as an output in order to calculate modal participation factors. I am especially interested in this in order to define damping in a more proper way, when the higher mode effects are significant.

**Comment by mhscott** [comment]
As far as I know, there is not an easy way to get the mass matrix out of OpenSees because the matrix is not stored explicitly.  Mass is kept at the nodes and in the elements, then assembled into the effective stiffness matrix, which is the only matrix stored.

**Comment by volkanozsarac** [comment]
I understand, thanks a lot for the reply. So, I guess, the only way to calculate modal participation factor is to assemble the mass matrix manually, and then use eigenvectors to calculate them.
