### ISSUE TITLE
Install without pip

### ISSUE THREAD

**Issue by ahmetanildindar** [zhuminjie/OpenSeesPyDoc#166]
Dear all,
I wonder how I can install openseespy in a Linux terminal where I can not use pip. The Linux system is a remote server and my account is unfortunately not privileged to install anything using pip. 

Any recommendation?

Ahmet Anil Dindar

**Comment by zhuminjie** [comment]
You can install as a user

pip install --user openseespy

**Comment by ahmetanildindar** [comment]
Thank you very much @zhuminjie for the tip.

It worked for me.

![image](https://user-images.githubusercontent.com/3111609/79068383-2b9ceb00-7ccf-11ea-8779-b5397348d317.png)
