### ISSUE TITLE
Moment Curvature Recorder Example

### ISSUE THREAD

**Issue by seyhanokuyan** [zhuminjie/OpenSeesPyDoc#17]
Hi,
I am found discrepancy between opensees and openseespy examples regarding recorder. Opensees recorder `recorder Node -file section$secTag.out -time -node 2 -dof 3 disp` return moment and corresponding curvature into the output file.

![image](https://user-images.githubusercontent.com/33574270/48416585-ad4abb00-e761-11e8-938d-99a6e1aca15e.png)
Whereas openseespy recorder `recorder('Node', '-file', "M-C/section1.txt", '-closeOnWrite', '-node', 2, '-dof',3, 'disp')` does not return moment into the output file.

![image](https://user-images.githubusercontent.com/33574270/48416713-fac72800-e761-11e8-9329-115ccd840a50.png)

I wonder has anybody experience the same discrepancy. 

Best regards from Istanbul.

SEYHAN

**Comment by nithinvl** [comment]
Hello Seyhan, 
In your tcl code, you have put '-time' option, hence it is giving you the load factor which for your case, is coming to be equal to your moment. But in your python code, you have not used the '-time' option.

Regards
Nithin

**Comment by seyhanokuyan** [comment]
Hi,
Discrepancy was removed. Thank you. Issue is closed.
![image](https://user-images.githubusercontent.com/33574270/48429263-d4af8100-e77d-11e8-97f9-88f3133d45e3.png)

**Comment by zhuminjie** [comment]
@nithinvl Thank you for the response!
