### ISSUE TITLE
Failed to import openseespy.

### ISSUE THREAD

**Issue by lzy1239** [zhuminjie/OpenSeesPyDoc#170]
Hello, dear Zhu:
I have a problem when I want to use the command "import" in Pycharm(yes! the first codes. embarrassing...)
The code " from openseespy.opensees import * " has always shows gray color(as shows below) 
even I use the official codes from the "openseespydoc"

I'm sure that the Anaconda and the environment has been correctly installed or set in my computer, because I have coded openseespy with Pycharm for several months . Such a sudden error is totally confusing for me.

**Comment by zhuminjie** [comment]
Pycharm is an IDE. If it worked before, it must be something changed. Can you try to remove and reinstall openseespy?

**Comment by lzy1239** [comment]
Thanks, I will try to reinstall the Anaconda , Pycharm and openseepy. Hope it works.
(It was my fault that I didn't make it clear,  for "Pycharm(an anaconda interpreter)",  I mean that I have correctly set the proper  project interpreter(the 'pythone.exe' that  have installed openseespy with 'pip' command) in Pycharm
