### ISSUE TITLE
Fiber Strain recorder

### ISSUE THREAD

**Issue by Savvinos-Aristeidou** [zhuminjie/OpenSeesPyDoc#171]
Hello,
I have been trying to record the extreme fiber stress-strain time history of an element (with circular section) during the pushover analysis. The command that I'm using is shown below:

op.recorder('Element', '-file', 'ele1sec1StressStrain.out', '-time', '-ele', 1003, 'section', '1', 'fiber' , 0, D/2, 'stressStrain')

The problem is that, it gives me the output of the same fibers every time and I have no control of which fiber I am getting the strains of. I tried changing the Y and Z coordinates but nothing changes. I would be grateful if you could help me on this issue. Thanks in advance!

**Comment by mhscott** [comment]
The parsing of input in the FiberSection::setResponse method needs to be updated.  To work around it, you will have to put the fiber coordinates in ' ' and not use any expressions.
... 'fiber','0','3.4','stressStrain').  The setResponse method calls atof on everything turning literal strings to floats.  Definitely something we need to fix, but this part of the code is a little messy.

**Comment by Savvinos-Aristeidou** [comment]
Thank you very much for the quick response! It worked just fine!
