### ISSUE TITLE
internal Stress for Shell DKGQ-DKGT

### ISSUE THREAD

**Issue by Marco-Pellegrino** [zhuminjie/OpenSeesPyDoc#174]
Hi guys,
I am trying to read the internal stress for the element type DKGQ or DKGT.
I notice that it is possible to read the forces with the recorder but if I try to use the recorder with "stresses" as arguments, I only get a series of 0.
any thought?

Best,
Marco

**Comment by u-anurag** [comment]
The following works for me.

`recorder('Element','-file','Ele1_Stress.out', '-closeOnWrite','-ele',1,'stresses')`

**Comment by Marco-Pellegrino** [comment]
Hi Anurag,
thanks for reply. Unfortunately I am still getting a series of zeros.
Can I ask you to send me a really little example that you have tested?
I would like to see if it works in my computer as well.

Thanks,
Marco

**Comment by u-anurag** [comment]
I just added the following line to the pushover case of the [RCshearwall.py](https://openseespydoc.readthedocs.io/en/latest/src/RCshearwall.html) example and it is not all 0.

recorder('Element','-file','PushoverOut/Ele1_Stress.out', '-closeOnWrite','-ele',1,'stresses')

**Comment by Marco-Pellegrino** [comment]
I think I found the problem.
In my analyses, I am using a timeSeries('Constant') or timeSeries('Linear').

if I use:
ops.algorithm("Linear")
ops.analyze(1)
I will get a series of zeros in the first line of the ouput.

if I use:
ops.algorithm("Linear")
ops.analyze(4)

the output starts to give the correct value.

if I use:
ops.algorithm("Newton")
ops.analyze(1)

I have correct results from the first line.

in any case, displacement and forces are correct.

any thought?

**Comment by zhuminjie** [comment]
Is that a elastic or nonlinear problem

**Comment by zhuminjie** [comment]
For any modeling issues in the future, please post on 

https://opensees.berkeley.edu/community/viewforum.php?f=12
