### ISSUE TITLE
Question regarding parallel computing

### ISSUE THREAD

**Issue by volkanozsarac** [zhuminjie/OpenSeesPyDoc#176]
Dear Dr. Zhu and Dr. Scott,

I wonder if you may help with my issue, since it is not really related to OpenSeespy. I am using OpenSeespy parallel computing via Linux subsystem for windows. I am carrying out dynamic analysis of a single model. Each processor carries out set of analyses for different ground motion sets. I am trying to see, during the analyses which ground motion I am running, or what is the number run etc. Is it possible to retrieve the command window output while operations continue? It seems that command window output appears only when the operations are finished.

Thank you.
Volkan

**Comment by volkanozsarac** [comment]
I found another strategy to check which work of each processor. For each processor a log is created, at each step of analysis these log files are written. However, I could not find a way to get the output in the command window simultaneously. 

Thank you

**Comment by zhuminjie** [comment]
Could save the information you need to check in files from the script?

**Comment by volkanozsarac** [comment]
I was able to save log files, simultaneously, while running the operations. I have tried this in one of the examples provided in openseespy webpage (hello world2). 
Aside from this, while running analyses in Linux subsystem for windows, I have realized, at least in the model that I developed, a single analysis takes more time in Linux subsystem (at least 50-100% more time). I was wondering if this is something expected?

**Comment by zhuminjie** [comment]
more time than who?

**Comment by volkanozsarac** [comment]
If the same analysis time is compared in both Windows OS and Linux Subsystem for Windows, the run time is greater in Linux Subsystem.

**Comment by zhuminjie** [comment]
That makes sense to me. The Linux Subsystem is actually a virtual machine running on Windows, an extra layer adding to Windows.

**Comment by volkanozsarac** [comment]
I understand, thank you

**Comment by volkanozsarac** [comment]
It is as you said, I made a trial, and the computational time is almost the same in computer with Linux OS
