### ISSUE TITLE
Support for python 3.8

### ISSUE THREAD

**Issue by jamesmaguire** [zhuminjie/OpenSeesPyDoc#177]
The current python version available from python.org is 3.8. Is it possible to support 3.8 in addition to 3.7 for those of us not using conda distributions?

As an aside, I tried to look into the source code to see how much work this would require (or if I could contribute), but it seems that the source code is not available on Github (and I can't find any other links). Is the source code not open/contributable?

**Comment by mhscott** [comment]
This repo is just for documentation of the Python module.

The actual source code is here: https://github.com/OpenSees/OpenSees
