### ISSUE TITLE
importing problem

### ISSUE THREAD

**Issue by Penghui0616** [zhuminjie/OpenSeesPyDoc#18]
Dear Zhu:
I have a question about import openseespy after installing it by Pypi. I am trying to setup OpenSeesPy on Win7 64-bit system with Python3.6. When I try to run the example "ElasticTruss.py", it gives me error, The fllowing methods are all not right:  
from openseespy import *
from openseespy.opensees import *
from openseesp import *

And the error include:
NameError: name 'opensees' is not defined
ImportError: DLL load failed

**Comment by Penghui0616** [comment]
import sys
sys.path.append('D:/OpenSeesPy')
import opensee

ImportError: DLL load failed: 找不到指定的模块。

**Comment by Penghui0616** [comment]
Does this program base on another pakege?

**Comment by ndr93** [comment]
First you have to check if Python/Opensees and Tcl have been correctly added to your computer environmental variables and then if you placed Active Tcl in the right folder ("C:\Program Files\Tcl").

**Comment by Penghui0616** [comment]
Thank you for you response, environmental variables path of my computer:
C:\Program Files\Tcl\bin;C:\Program Files\Tcl;D:\Program Files\Python3.7;D:\Program Files\Python3.7\Scripts;D:\Program Files\Python3.6;D:\Program Files\Python3.6\Scripts;D:\Program Files\Python2.7;D:\Program Files\Python2.7\Scripts;

**Comment by Penghui0616** [comment]
when you say Opensees, do you mean the Opensees from PEER?

**Comment by Penghui0616** [comment]
And i find this program can't work in 32bit windows

**Comment by Penghui0616** [comment]
i have solved this problem by changing the codes:
import sys
sys.path.append('D:/OpenSeesPy')

import numpy as np
import matplotlib.pyplot as plt

from opensees import *

I think maybe openseespy relaies on numpy and matplotlib

**Comment by Penghui0616** [comment]
Thank you very much

**Comment by zhuminjie** [comment]
@Penghui0616 Good to know you fixed it!
