### ISSUE TITLE
Falied Get_Rendering

### ISSUE THREAD

**Issue by ItaloIF** [zhuminjie/OpenSeesPyDoc#180]
Dear Dr. Zhu,
I am writing to tell you about a bug  that occurs when I want import `openseespy.postprocessing.Get_Rendering`. Because this file Get_Rendering.py have a tabs error from line 495 onwards.

I fixed this error in my computer package. Can I open a Pull Request? or it's not necessary

**Comment by zhuminjie** [comment]
The tab problem has been fixed in the repo. It just has not been released. Thank you!

**Comment by zhuminjie** [comment]
It's fixed now.
