### ISSUE TITLE
4.2.2.1. Truss Element 

### ISSUE THREAD

**Issue by Johandcj** [zhuminjie/OpenSeesPyDoc#181]
There is an error in the documentation for truss elements of the type 'TrussSection'
element('TrussSection', eleTag, *eleNodes, **_A_**, secTag[, '-rho', rho][, '-cMass', cFlag][, '-doRayleigh', rFlag])
The area does not need to be specified and results in an error message of the type:
SectionForceDeformation *getSectionForceDeformation(int tag) - none found with tag: 0
WARNING: Invalid section not found element TrussSection 11011201 $iNode $jNode 0 <-rho $rho> <-cMass $flag> <-doRayleigh $flag>

**Comment by mhscott** [comment]
Thanks for catching that!
