### ISSUE TITLE
RuntimeError: Failed to import openseespy (3.2.0)

### ISSUE THREAD

**Issue by mnadhro** [zhuminjie/OpenSeesPyDoc#182]
Hi,
after upgrading to the latest version 3.2.0, failed to import opensees,
It is in both linux and web based DesignSafe Jupyter, there is no problem for windows

![Screenshot at 2020-05-04 11-36-17](https://user-images.githubusercontent.com/61713112/80949359-9340e480-8dfc-11ea-84d6-0512d0616bfd.png)

**Comment by zhuminjie** [comment]
That's because the new release was compiled on ubunty 18.04, which has newer library than DesignSafe or your linux machine. I will look into it to ship with the updated library.

**Comment by mnadhro** [comment]
Thank you,
by the way , I have tried it on Ubuntu 20.04 and an Arch base system

**Comment by zhuminjie** [comment]
It should be fixed now

**Comment by mnadhro** [comment]
Yes, it works in DesignSafe now,
but not in my two linux systems.
![Screenshot at 2020-05-08 21-42-40](https://user-images.githubusercontent.com/61713112/81438120-e73d2780-9174-11ea-89ef-2b0bf8b5ca2c.png)

**Comment by zhuminjie** [comment]
What Linux system are you using?

**Comment by mnadhro** [comment]
this my main system,
OS      :Ubuntu 20.04 LTS x86_64
Kernel : 5.4.0-28-generic

and I also tried it in Arch linux

**Comment by zhuminjie** [comment]
Ubuntu 20.04 is just released last month and Arch linux is always cutting-edge. Can you try on Ubuntu 18.04?

**Comment by mnadhro** [comment]
Ok, I will try it,
but for my main system do yo think if I've tried to compile it from source, is it going to work?

**Comment by mnadhro** [comment]
by the way I could run version 3.0.3 now, since it is the last version that I had before upgrading to 3.2

**Comment by zhuminjie** [comment]
there is no 3.0.3 version, are you talk about 3.2.0.3?

**Comment by mnadhro** [comment]
I meant the that based on OpenSees 3.0.3

**Comment by zhuminjie** [comment]
I am able to find the problematic library. Can you please check again with all your linux systems?

**Comment by mnadhro** [comment]
Unfortunately, did not work
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/mnadhro/.local/lib/python3.8/site-packages/openseespy/opensees/linux/lib/librt.so.1: undefined symbol: __clock_nanosleep, version GLIBC_PRIVATE`

**Comment by zhuminjie** [comment]
That's the same error you got before. Did you try the new 3.2.2 version?

**Comment by mnadhro** [comment]
yes, on both systems ...

![Screenshot at 2020-05-09 21-45-58](https://user-images.githubusercontent.com/61713112/81482281-87ab4e80-923e-11ea-9fb6-b52f8a5d933c.png)

**Comment by zhuminjie** [comment]
I have tested on Ubuntu 18.04, Centos 7, DesignSafe, and WSL. They all work.

What you got seems like a Ubuntu 20 problem

https://answers.launchpad.net/ubuntu/+question/689324

**Comment by Sadia328** [comment]
could anyone guide me on how to install Openseespy to use it in Anaconda>> Spyder environment? on windows. 
![image](https://user-images.githubusercontent.com/70929596/93224395-7e9d3180-f78a-11ea-835c-6ad35980c93d.png)

**Comment by mnadhro** [comment]
just enter in command window:
```pip install openseespy```

and import using:
```import openseespy.opensees as ops```

https://openseespydoc.readthedocs.io/en/latest/src/pypi.html

**Comment by Sadia328** [comment]
Thank you that was very helpful.
