### ISSUE TITLE
EqualDOF and rigidDiaphragm Slaving.

### ISSUE THREAD

**Issue by nicclemett** [zhuminjie/OpenSeesPyDoc#183]
Hi All,

I am having some troubles with using the `equalDOF()` and `rigidDiaphragm()` commands to create a rigid diaphragm in my model, when double nodes are specified at each coordinate.
The issue I am encountering is that if I try and use the `equalDOF()` and `rigidDiaphragm()` commands sequentially all of constraints do not appear to be applied to the model.

I have a simple 3D model as shown below and described in the attached input file.

![image](https://user-images.githubusercontent.com/62114051/81168181-ca4afd80-8f96-11ea-87c2-5e3a410c5333.png)

I have modelled two nodes at each BCJ location so that at a later stage I can add a zeroLength spring to represent the BCJ flexibility. In the meantime I would like to slave the two nodes so that they have the same displacements in all 6 DOF.

I have used the `rigidDiaphragm()` command to slave all of the L1 nodes to one of the nodes at the corner. The issue I am encountering is that if I specify the pairs of nodes to also have the same Z, Mx, and My, displacements using the command `equalDOF(master, slave, *[3, 4, 5])` then no constraint appears to be imposed as evidenced by the `nodeDOFs()` and eigenvalues printed out by my script.

![image](https://user-images.githubusercontent.com/62114051/81166250-b5b93600-8f93-11ea-8376-d8f3f7e72c65.png)

Another interesting thing that I noticed was that if the `equalDOF()` command is placed **before** the `rigidDiaphragm()` then the node DOFs are quite different and the modeshapes no longer seem reasonable... N10 Dofs 3,4 are equal to N6 Dofs 1, 5 respectively.

![image](https://user-images.githubusercontent.com/62114051/81166892-95d64200-8f94-11ea-9520-ad66889e9bca.png)

It appears as if when one of the constraints (`equalDOF() or rigidDiaphragm()`) is already specified for a node then the next one is sort of ignored...

In addition I also tried to slave only node A at each location to the `rigidDiaphragm()` and then use `equalDOF(master, slave, *[1,2,3,4,5,6])` for node B but this also gave unrealistic modeshapes.

I can work around this problem by slaving all of the L1 nodes to the diaphragm and then placing a very stiff zeroLength element between the nodes. This gives the same displacements for each node in the pair as I would expect, however, I would prefer to avoid this and use slaving if possible.

I appreciate any help that you can provide regarding this...

Cheers,
Nic

[dbl_node_frame_with_node_masses.zip](https://github.com/zhuminjie/OpenSeesPyDoc/files/4586259/dbl_node_frame_with_node_masses.zip)

**Comment by mhscott** [comment]
Hello @nicclemett, this repo is intended for documentation of the OpenSees Python commands.  General modeling issues such as yours should be posted at https://github.com/OpenSees/OpenSees.

**Comment by nicclemett** [comment]
Hi Michael,
My apologies. I am using OpenSeesPy. I wasn't sure whether this was an OpenSeesPy issue or a general OpenSees query.
I will repost in the general page.

Thanks,
Nic
