### ISSUE TITLE
nDMaterial 'PM4Silt' is unknown in openseespy

### ISSUE THREAD

**Issue by ajmakdisi-uw** [zhuminjie/OpenSeesPyDoc#185]
I am attempting to build a model in OSpy using the PM4Silt model (which I believe is in the UWmaterials folder of the nD directory). Would it be possible to include it in the next update of OpenSeesPy? Thanks!

**Comment by mhscott** [comment]
It should be in the next pip update.

https://github.com/OpenSees/OpenSees/pull/348
