### ISSUE TITLE
PROBLEMS IN THE ANALYSIS IN TRANSFORMATION FROM MODEL TCL TO PY

### ISSUE THREAD

**Issue by fjjimenez1** [zhuminjie/OpenSeesPyDoc#187]
I am making a model of a soil column in 3D, when starting the static analysis Openseespy does not perform the interactions and does not record the results.

This is how the console shows the interactions of all analyzes:

Timer :: start (hr: min: millisec): 16: 17: 375
CTestNormDispIncr :: test () - iteration: 1 current Norm: 0 (max: 0.0001, Norm deltaR: 0)
CTestNormDispIncr :: test () - iteration: 1 current Norm: 0 (max: 0.0001, Norm deltaR: 0)
CTestNormDispIncr :: test () - iteration: 1 current Norm: 0 (max: 0.0001, Norm deltaR: 0)
CTestNormDispIncr :: test () - iteration: 1 current Norm: 0 (max: 0.0001, Norm deltaR: 0)
CTestNormDispIncr :: test () - iteration: 1 current Norm: 0 (max: 0.0001, Norm deltaR: 0)
CTestNormDispIncr :: test () - iteration: 1 current Norm: 0 (max: 0.0001, Norm deltaR: 0)
CTestNormDispIncr :: test () - iteration: 1 current Norm: 0 (max: 0.0001, Norm deltaR: 0)
End of elastic static analysis

**Comment by mhscott** [comment]
Please post modeling issues on the OpenSees message board (OpenSeesPy forum)

https://opensees.berkeley.edu/community/viewforum.php?f=12

--
Michael H. Scott, Ph.D.
Professor, Structural Engineering
Oregon State University
cce.oregonstate.edu/scott<https://exmail.oregonstate.edu/owa/redir.aspx?C=_F2i-PfJ4o6PTa3_ZQo4PE-QjaGSDCPQO_2ZTY0wP-CV6RK6qknXCA..&URL=https%3a%2f%2fcce.oregonstate.edu%2fscott>
o: 1-541-737-6996
OpenSees blog: www.portwooddigital.com<https://outlook.office.com/mail/options/mail/messageContent/www.portwooddigital.com>
________________________________
