### ISSUE TITLE
module 'openseespy.opensees' has no attribute 'testNorm'

### ISSUE THREAD

**Issue by YexiangYan** [zhuminjie/OpenSeesPyDoc#188]
Dear Dr. Zhu: 
   When I run the following command, I get an error:

``` 
import openseespy.opensees as op
op.testNorm()
```
The error is "module 'openseespy.opensees' has no attribute 'testNorm".

Is the python interface of this command not provided yet? I tried this command in tcl format and it can be run. I use the latest version of openseespy.

Thank you for providing such an excellent tool !

**Comment by mhscott** [comment]
Is it this command to get the convergence test norms?

Tcl_CreateCommand(interp, "testNorms", &getCTestNorms,

**Comment by zhuminjie** [comment]
It is called getCTestNorms right now. But looks like the document calls it testNorm. I will fix the name as the document. For now, you can call getCTestNorms until it's updated.

**Comment by YexiangYan** [comment]
Dear  Prof. Scott and Dr. Zhu:  
       The code has run successfully by using 'getCTestNorms'. Thank you very much.
