### ISSUE TITLE
Contributing Some Geotechnical Examples to Documentation

### ISSUE THREAD

**Issue by ajmakdisi-uw** [zhuminjie/OpenSeesPyDoc#189]
I've been spending some time in the last few weeks developing some OpenSeesPy examples as Jupyter Notebooks, where chunks of code are interspersed with markdown text describing what is actually being generated in the model. These are relatively simple single element-wide examples of dynamic analysis of a soil column, using a few different types of `nDMaterial` soil models - I also developed some Python scripts for efficiently processing and plotting output data.

Would there be any interest having these notebook examples in the documentation page for OpenSeesPy? Or is the preference to submit these as pure .py scripts (which I am also happy to do).

**Comment by zhuminjie** [comment]
I think notebooks are good. Can you convert them to html so I can embed directly. Thank you!

**Comment by ajmakdisi-uw** [comment]
Yes, absolutely! I need to go back through them one more time and clean them up a little bit before sending directly, but will do so in the next couple of days.

**Comment by zhuminjie** [comment]
Thank you! Take your time.
