### ISSUE TITLE
printA is not working

### ISSUE THREAD

**Issue by frqc** [zhuminjie/OpenSeesPyDoc#19]
When I add `printA()` at the bottom of this example [script](https://openseespydoc.readthedocs.io/en/latest/truss.html), nothing happens regardless using '-file' option. 

I'm not sure I used it in the right way. Is this a bug or could you illustrate the correct usage of this command in openseespy document? Thank you!

**Comment by zhuminjie** [comment]
The problem is that printA() uses the interface getA of linearSOE base class. However, no solver implements that interface in OpenSees. This is really not a problem of OpenSeesPy but OpenSees framework. I can add the getA interface for some solvers.

**Comment by zhuminjie** [comment]
@frqc I will make printA work for some solvers in the next version of OpenSeesPy. What specific solver do you use?

**Comment by frqc** [comment]
Actually I was not aware that the printA will only work for a FullGeneral system only. What I'm looking for is to print out the matrix to solve, in order to inspect/debug/optimize the structure. 

For example, I once created floating points not connecting to any elements and then it led to a singular matrix. And when I was trying [example 1.7](https://openseespydoc.readthedocs.io/en/latest/ThreeStorySteel.html), I notice it used dummpy nodes and restrict them with equalDOF commands. I wanted to see the differences when creating the structure with elements connected to same nodes without dummy nodes and equalDOF. 

I guess by printing the matrix to solve it will be helpful to validate these cases. Is there an easy way without big constraints to do so?
Thanks!

**Comment by zhuminjie** [comment]
Yes, you are right. printA currently only works for FullGeneral solver. I tried printA for other solvers. It doesn't look very useful for them and not easy to implement. A quick way will be using FullGeneral to check stiffness matrix and switch back to other solvers to solve. Or if you want to check stiffness matrix for certain steps, use faster solver to proceed the steps, switch to FullGeneral to check, and switch back to other solvers.
