### ISSUE TITLE
Section Fiber Recorder Example Please

### ISSUE THREAD

**Issue by timbotics** [zhuminjie/OpenSeesPyDoc#193]
Greetings,

I have looked through the forum and found this issue pop up a few times, but I still cannot get the element recorder to output the stress-strain at a specific point on a fiber section. Below is the code I have written to record a fiber stress-strain:

`recorder('Element', '-file', 'fiberstressStrain.out', '-closeOnWrite', '-time', '-ele', 1, 'section', '1', 'fiber', '0.','12.', 'mat', '2', 'stressStrain');`

Can someone please provide a complete example of how to properly define the arguments in the recorder function to obtain the fiber stress-strain at a specific point on a section?

Cheers,

Tim

**Comment by pavan1388** [comment]
Hello Tim,

I have some comments related to your question about the stress-strain issue in the link below. 

https://opensees.berkeley.edu/community/viewtopic.php?f=12&t=66954&sid=1898277d2a0e61edeb00833f1aecb05e


I hope it helps.

Pavan Chigullapally.

**Comment by mhscott** [comment]
https://portwooddigital.com/2021/07/25/how-to-record-fiber-response/
