### ISSUE TITLE
Running Opensees in Spyder with python 3.8

### ISSUE THREAD

**Issue by spinosa10** [zhuminjie/OpenSeesPyDoc#197]
Hi 

I've just started to work with spyder and Openseespy. I downloaded the last version of Anaconda with python 3.8. When I try to use openseespy I get the following msg in Console:

runfile('C:/Users/spino/.spyder-py3/temp.py', wdir='C:/Users/spino/.spyder-py3')
Traceback (most recent call last):

  File "C:\Users\spino\.spyder-py3\temp.py", line 7, in <module>
    import openseespy.opensees as op

  File "C:\Users\spino\anaconda3\lib\site-packages\openseespy\opensees\__init__.py", line 29, in <module>
    raise RuntimeError(

RuntimeError: Python version 3.7 is needed for Windows (Anaconda is recommended https://www.anaconda.com/distribution/)

I am brand new with this and I really need some help

Thank you!!

**Comment by zhuminjie** [comment]
This is because Anaconda just upgraded to Python3.8 and openseespy still supports upto Python3.7. We will update our version soon.

**Comment by spinosa10** [comment]
Thank you for your answer, it is very clear, I think I'll try to get the 3.7 Python version.

**Comment by BijanSeif** [comment]
Hi 

Today we have this problem with Python version 3.9.6 and when we try to use Opensees this message becomes appear: 

"RuntimeError: Python version 3.8 is needed for Windows" 

Am I true? (The problem is the need of updating the version of opensees)

Thank you!

**Comment by zhuminjie** [comment]
We follow whatever Python version is supported by Anaconda

https://www.anaconda.com/products/individual
