### ISSUE TITLE
(Linux) OpenSeesPy Import Error: Invalid ELF Header

### ISSUE THREAD

**Issue by anurag-upadhay** [zhuminjie/OpenSeesPyDoc#2]
I am trying to setup OpenSeesPy on Linux Mint 18.3 Xfce 64-bit system with Python3.6.5. When I try to run the example "ElasticTruss.py", it gives me error 

``File` "ElasticTruss.py", line 3, in <module>
from opensees import *
ImportError: /home/anurag/OpenSeesPy/opensees.so: invalid ELF header``

I repeated the installation procedure but still got the same error. Does anyone know about this issue?

![screenshot_openseespy](https://user-images.githubusercontent.com/35711550/40564136-c9a9ffb4-6024-11e8-9e00-c324c12ff87c.png)

**Comment by zhuminjie** [comment]
Is there other library files in the path? So the python program loaded the other one.

**Comment by anurag-upadhay** [comment]
I reinstalled my OS and all the packages. It works now. Thanks.
