### ISSUE TITLE
Running Dam Break Example for OpenSeesPy

### ISSUE THREAD

**Issue by jstolle13** [zhuminjie/OpenSeesPyDoc#20]
Good afternoon,

I recently attempted to use OpenSeesPy for fluid structures interactions using the installation procedure suggested on the OpenSeesPy Wiki. I tried the dam-break problem, however, the code works okay until the analysis portion and the analyze function kicks back a "-1". All of the other OpenSeesPy examples seem to work (except for the Elastic obstacle in a dam-break).

Thank you for any help you can give.

**Comment by zhuminjie** [comment]
There was a bug found. The OpenSeesPy will be updated to fix the bug.
