### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by theRicky** [zhuminjie/OpenSeesPyDoc#206]
![image](https://user-images.githubusercontent.com/28887559/93012286-b7de7180-f5d1-11ea-994a-cdd7abdeef0a.png)

I have trouble in importing openseespy which is installing by pip in anaconda. Can anybody help?

**Comment by zhuminjie** [comment]
Does this run from pycharm? Can you try open a python shell and import directly with import openseespy.opensees as ops?

**Comment by theRicky** [comment]
![image](https://user-images.githubusercontent.com/28887559/93280549-82699c00-f7fc-11ea-945e-d911ab6c5574.png)
I imported it in anaconda prompt, still got the same result. Is it the problem of anaconda environment?

**Comment by zhuminjie** [comment]
Probably not, I will get back to you later.

**Comment by zhuminjie** [comment]
Can you try for the base environment?

**Comment by zhuminjie** [comment]
A fix is patched. Can you try again?

**Comment by theRicky** [comment]
It works！Thanks for your time and effort!
