### ISSUE TITLE
OpenSeesPy Warnings

### ISSUE THREAD

**Issue by davitshahnazaryan3** [zhuminjie/OpenSeesPyDoc#213]
Sometimes running openseespy, when convergence is not achieved or minor issues have been recorded, there could be an abundance of warnings. 
A question is, whether there is a possibility to ignore those warnings (to not show in the terminal)? If not, I would highly recommend adding the possibility of ignoring those warnings, as sometimes they may be way too many warnings (especially during nonlinear time history analysis), and tracking steps of the analysis in the terminal without the use of external files could be cumbersome.

**Comment by mhscott** [comment]
Some of the warnings can be important, especially if they appear at each step of a response history analysis.

**Comment by davitshahnazaryan3** [comment]
Thank you. Yes, of course they can be important. I am not saying to remove them, but a possibility to turn them on or off could be really handy.

**Comment by zhuminjie** [comment]
You can redirect python stdout and stderr to file.

**Comment by davitshahnazaryan3** [comment]
Thank you.
