### ISSUE TITLE
No module named 'openseespy' *Spyder* and Jupyter says Python 3.8

### ISSUE THREAD

**Issue by burakdur** [zhuminjie/OpenSeesPyDoc#215]
Hi everyone,

I am trying to install openseespy and work on it using Jupyter Notebook or Spyder, but I have some errors like below.

![Screenshot_16](https://user-images.githubusercontent.com/76974357/103676699-67f43380-4f4f-11eb-96d3-7ae7ec18e007.jpg)

I installed Python 3.9, but Jupyter does not see it and Spyder still says it can't see the openseespy module although it is located in C:\Users\Administrator\Anaconda3\Lib\site-packages. So, I am using same file directory where openseespy is located. Do you think the problem is because of the file locations, or why the Jupyter can't see Python 3.9? It is interesting that Spyder can't see the openseespy module whatever I did. 

Thanks

**Comment by mhscott** [comment]
Closing. OpenSeesPy should work with Python 3.9 now.
