### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by arisalehi** [zhuminjie/OpenSeesPyDoc#216]
Dear Dr. Zhu

After I installed the Openseespy, I tried the "RCFrameEarthquake" example; when running the code in line : "dt, nPts = ReadRecord.ReadRecord(record+'.at2', record+'.dat')" I got this error:
unsupported operand type(s) for +: 'builtin_function_or_method' and 'str'
Would you please help me through this?

**Comment by mhscott** [comment]
That is a native Python error, not OpenSeesPy
