### ISSUE TITLE
Unable to record stress in Nine Four Node Quad u-p Element

### ISSUE THREAD

**Issue by harshmistry96** [zhuminjie/OpenSeesPyDoc#217]
Hi,

I am trying to perform the effective site response analysis in openseespy by following the equivalent code for the same example which is provided for opensees.

I tried recording the stress  and strain in element but the file only shows the column for time and it doesn't record any stress or strain.
Following is the command for openseespy:
op.recorder('Element', '-file', 'stress1.txt', '-time', '-recDT', '-eleRange', 1, nElemT, '-material', 1, 'stress')
op.recorder('Element', '-file', 'strain1.txt', '-time', '-recDT', '-eleRange', 1, nElemT, '-material', 1, 'strain')

Please let me know if the implementation is wrong ?

Kind Regards,
Harsh Mistry

**Comment by zhuminjie** [comment]
For now, the inquiry options should be in string:

```python
op.recorder('Element', '-file', 'stress1.txt', '-time', '-recDT', '-eleRange', '1', 'nElemT,' '-material', '1', 'stress')
```

This will be changed in the future.

**Comment by harshmistry96** [comment]
Thank you,

also instead of '-material' should it be 'material' ?

**Comment by harshmistry96** [comment]
Hi,

@zhuminjie, Is it possible to record **Excess pore pressure ratio** from the Nine Four Node Quad u-p Element, using the following command:

`op.recorder('Element','-file','press1.txt','-time', '-dT',recDT,'-eleRange', 1, nElemT,'material','1','pressure')`

**Comment by mhscott** [comment]
This option may not be enabled for the recorder of that material. Check the source code of the nDMaterial.

This repo is for documentation of OpenSeesPy, not general user issues like this one.  Please post such questions to the OpenSees message board (opensees.berkeley.edu/community) or the Facebook group.
