### ISSUE TITLE
 Version 3.2.2.9 of OpenSeesPy

### ISSUE THREAD

**Issue by subedinaresh** [zhuminjie/OpenSeesPyDoc#218]
I am running Moment-curvature analysis of a RC section with zeroLengthSection'Element. My code was running fine with the previous version (3.2.2.6) of OpenSeesPy but with the new version the program fails to converge--even with elastic materials. 

This happens when the load factor becomes negative (curvature applied in opposite direction to the reference moment).  I would like to know if this is the case or some issue particular to my code. 

Thank you.

**Comment by mhscott** [comment]
We're not aware of any changes, so please provide more details about how you define the section.

**Comment by subedinaresh** [comment]
I define the circular section and do the moment-curvature analysis as follows (Unit definitions omitted for clarity):
----------------------------------------------------------------------------------------

`from openseespy.opensees import *
import numpy as np `

`def MomentCurvature(secTag, N, maxK, curIncr=0.0001*(1/m), recorderFileName='SectionAnalaysis.txt'):
    """Function to carry-out the momemt-curvature analaysis using zeroLengthSection element"""
    
    # Define two nodes at (0,0)
    node(1, 0.0, 0.0)
    node(2, 0.0, 0.0)

    # Fix all degrees of freedom except axial and bending
    fix(1, 1, 1, 1)
    fix(2, 0, 1, 0)
    
    # Define element
    #                            tag ndI ndJ  secTag
    element('zeroLengthSection',  1,   1,   2,  secTag)

    #Define recorders
    #Moment-curvature recorder
    recorder('Node', '-file', "MPhi"+recorderFileName, '-time',  '-node', 2,'-dof', 3, 'disp')
    
    # Define constant axial load
    tSTag=100;         #timeSeries tag [tag 2 is used for REFERENCE Moment applied to node 2]
    pTag=100;          #Load Pattern tag [tag 2 is used for REFERENCE Moment applied to node 2]
    timeSeries('Constant', tSTag)
    pattern('Plain', pTag, tSTag)
    
    #Initial axial load
    load(2, N, 0.0, 0.0)
    

    # Define analysis parameters
    integrator('LoadControl', 0.0)
    system('SparseGeneral', '-piv')
    test('NormUnbalance', 1e-9, 10)
    numberer('Plain')
    constraints('Plain')
    algorithm('Newton')
    analysis('Static')

    # Do one analysis for constant axial load
    analyze(1)
    
    # Define reference moment
    timeSeries('Linear', 2) #[tag 2 for REFERENCE Moment applied to node 2]
    pattern('Plain',2, 2)   #[tag 2 for REFERENCE Moment applied to node 2]
    load(2, 0.0, 0.0, 1.0)

    
    #Analyze for each curvature
    for curv in maxK:
        
        #For negative curvature values 
        if curv< 0.0:
            curIncrTemp=-1*curIncr;
        #For positive curvature values
        else:
            curIncrTemp=curIncr;
            
        # Compute number of increments
        numIncr = int(round(curv/curIncrTemp));
        print("numIncr: ", numIncr)
 
        print("Curvature:",curv)    
        
        print("curIncrTemp: ", curIncrTemp)
        
        #From 0--> Peak
        #----------------
        # Use displacement control at node 2 for section analysis
        integrator('DisplacementControl',2,3,curIncrTemp,1,curIncrTemp,curIncrTemp) 
        
        # Do the section analysis
        analyze(numIncr)
        
#         #From  Peak-->0
#         #--------------
#         curIncrTemp*=-1;
        
#         # Use displacement control at node 2 for section analysis
#         integrator('DisplacementControl',2,3,curIncrTemp,1,curIncrTemp,curIncrTemp) 

#         # Do the section analysis
#         analyze(numIncr)`

`#remove existing model 
#---------------------
wipe()

print("Start Pile section analysis")

# Define model builder
# --------------------
model('basic','-ndm',2,'-ndf',3)


# Define materials for pile section
# ------------------------------------------
#material tag for unconfined concrete
ConUCTag=201;
# --------------------------------------------------------
#Confined concrete (According to Han et al. (2007))
fpccc = -32.20*MPa;
epcc = -0.002404;
Ec = 25374.0*MPa;
fpucc = 0.20*fpccc;
# epsucc = -0.0403;
epsucc = -0.020;

ftc=2.55*MPa;
Ets=0.05*Ec;
# --------------------------------------------------
#uniaxialMaterial('Concrete02', matTag, fpc, epsc0, fpcu, epsU, lambda, ft, Ets)
uniaxialMaterial('Concrete02', ConUCTag, fpccc, epcc, fpucc, epsucc, 0.1, 0.0, 0.0)
# uniaxialMaterial('Elastic', ConUCTag, Ec);


# --------------------------------------------------
# STEEL CASING
# --------------------------------------------------

#material tag for steel-encasing material
SteelTag=203;  

#Steel casing properties from Material Test 
Es = 200000.0*MPa;	#Steel casing Young's Modulus
fys = 427.5*MPa;		#Steel yield stress
fus = 579.6*MPa;		#Steel Ultimate Tensile Strength 
esult = 0.1543;					#Steel Ultimate strain
bs = 0.005;			#Ratio of post-yield stiffness to initial stiffness

uniaxialMaterial('Hysteretic', SteelTag, fys, fys/Es, 1.25*fys, 0.05, fus, esult, -fys, -fys/Es, -1.25*fys, -0.05, -fus, -esult, 0.30, 0.60, 0.0, 0.0, 0.0)
# uniaxialMaterial('Elastic', SteelTag, Es);
#-----------------------------------------------------------------------

print("Materials defined.")

# Define cross-section of pile
# ------------------------------------------
# set pile dimenstions
Dia = 1200.0*mm;
t=9.6*mm; 
momentArm = 3000.0*mm;  	#Length of the pile from support to the loading point


#section parameters 
PileSectionID=301;

# some variables derived from the parameters
ris  = 0.5*(Dia-2*t);		# inner radius of the steel casing
ros  = 0.5*Dia;			# overall (outer) radius of steel casing

ric  = 0.0;				# inner radius of the concrete infill
roc  = ris;			# outer radius of concrete infill

#section discretization parameters 

nfST = 72;	# number of theta divisions in the steel section (number of "wedges")
nfSR = 1;		# number of radial divisions in the steel section (number of "rings")
 
nfCT = 72;		# number of theta divisions in the concrete section (number of "wedges")
nfCR = 15;		# number of radial divisions in the concrete section (number of "rings")

#------------------------------------------
section('Fiber', PileSectionID)

#patch('circ', matTag, numSubdivCirc, numSubdivRad, *center, *rad, *ang)

patch('circ', SteelTag, nfST, nfSR, 0.0, 0.0, ris, ros, 0, 360);	# Define the steel casing patch
patch('circ', ConUCTag, nfCT, nfCR, 0.0,0.0, ric, roc, 0, 360);	# Define the concrete-infill patch


#Constant axial load for analysis
N=-4072.0*kN;  #Axial load at the start of loading

# Curvature increment in analysis
curIncr = 0.00001*(1/m);


#Ultimate curvature for analysis
# phiUlt=np.array([0.040*(1/m)]);
phiUlt=np.array([-0.020*(1/m)]);

# Call the section analysis procedure
MomentCurvature(PileSectionID, N, phiUlt, curIncr, 'SC_ConstAxialLoad.txt')

print("==========================")`

**Comment by subedinaresh** [comment]
I define Fiber section with circular patches for concrete and steel.  

Seems like GitHub does not like notebook files and directly pasting the code, so the here is the [link to the file](https://drive.google.com/file/d/1j9hKYfINzhaeNCz4SmjsMk-hXPoWXubl/view?usp=sharing).

**Comment by mhscott** [comment]
It might be related to this: https://github.com/OpenSees/OpenSees/issues/524

**Comment by subedinaresh** [comment]
Yes, that was the case; works now!

Thank you Professor.
