### ISSUE TITLE
Missing velocity history input file for freeFieldEffective.py

### ISSUE THREAD

**Issue by kengwit** [zhuminjie/OpenSeesPyDoc#224]
Where can I find the "velocityHistory.txt" input for running this example?

**Comment by zhuminjie** [comment]
@harshmistry96 can you take a look at this issue, thank you

**Comment by harshmistry96** [comment]
[velocityHistory.txt](https://github.com/zhuminjie/OpenSeesPyDoc/files/6097514/velocityHistory.txt)

Here is the file.

Should I upload it in the repo and create the pull request?

**Comment by zhuminjie** [comment]
Is there other input files are needed? You can submit another PR to merge these files in the same folder of the source file.

**Comment by harshmistry96** [comment]
No its just this file. Okay i will create the new PR to merge

**Comment by zhuminjie** [comment]
Okay, thanks! Also put a link to the data file in the .rst file same as the link to the source file.

**Comment by harshmistry96** [comment]
sure !

**Comment by zhuminjie** [comment]
@kengwit it should be fixed now. Wait for few minutes.

**Comment by kengwit** [comment]
Thank you!
