### ISSUE TITLE
ops_vis.plot_fiber_section

### ISSUE THREAD

**Issue by ozgunnn** [zhuminjie/OpenSeesPyDoc#229]
ops_vis.plot_fiber_section command when used with a list trying to patch and plot a circular section.

I get the error as below. When I go to line 2314 of ops_vis.py, I realized there was no definition for 
if item[1] == 'circ'

```
File "C:xxxx\Anaconda3\lib\site-packages\openseespy\postprocessing\ops_vis.py", line 2314, in plot_fiber_section
    outIJxIK = (Jy-Iy)*(Kz-Iz) - (Ky-Iy)*(Jz-Iz)

UnboundLocalError: local variable 'Jy' referenced before assignment
```

**Comment by u-anurag** [comment]
ops_vis.plot_fiber_section command does not support Circular sections.

**Comment by sewkokot** [comment]
As @u-anurag wrote, it's not supported yet. It's on my TODO list as many other features :)
Or you can try yourself based on plotSection.zip (see plotSection.m matlab file) available from:
http://users.ntua.gr/divamva/software.html
Pull requests are welcome.

**Comment by sewkokot** [comment]
Ok, I gave it a try and implemented the support for circular fiber section. It seems to work, just give me a day or two to prepare a PR.
![fibsec_circ](https://user-images.githubusercontent.com/12695169/114058734-03b97680-9894-11eb-9036-522cb53b03dd.png)

**Comment by ozgunnn** [comment]
Thanks a lot!
