### ISSUE TITLE
PVD recorder fails when using relative path

### ISSUE THREAD

**Issue by frqc** [zhuminjie/OpenSeesPyDoc#23]
Not a serious bug though. When running `recorder('PVD', "../log/pvd_result")` it fails due to the path concating: 
`WARNING: Failed to open file ../log/pvd_result/../log/pvd_result_T1.0000000000e+00_P0.vtu
`

Shouldn't be on the first priority since there are ways to work around. 
Thanks

**Comment by zhuminjie** [comment]
It has been updated to allow users to set both path and filename. Will be available in the next version.
