### ISSUE TITLE
plot_fiberResponse2D() - Fiber strains averaged on the element or dependent on the integration point?

### ISSUE THREAD

**Issue by ozgunnn** [zhuminjie/OpenSeesPyDoc#231]
Hello, I have been working for a while with displacement based beam-column elements having fiber sections.

I realized the plot of fiber strains change on the same model and the same element if i reverse the node numbers of that element only but change nothing else (element number stays the same).

I previously thought that the plotted fiber response was average (let's say strain) along the single element. But changing response with reversed node numbering makes me think it is probably on the integration point but not average along the element.

Realizing this I couldn't figure how to choose the integration point on which the response will be plotted since the function doesn't take integration point as argument (as far as I understood). 

Am i right about the response being on the integration point and not along the whole element?
If yes is there a way to set which integration point will be used to plot the response?

Thanks a lot.

**Comment by mhscott** [comment]
I assume this has been resolved. You can select integration points in the recorders.
