### ISSUE TITLE
QzSimple2

### ISSUE THREAD

**Issue by fallahireza** [zhuminjie/OpenSeesPyDoc#234]
Hi, I need to use uniaxialMaterial 'QzSimple2', but I am getting a warning message "WARNING material type QzSimple2 is unknown" even though similar materials 'QzSimple1 are working.
-OS: Windows 7
-OpenSeesPy Version: OpenSeesPy 3.2.2.10
-Python Version: Python 3.8.8
Anaconda 2.0.3

**Comment by mhscott** [comment]
Fixed. Thanks for bringing it to our attention. https://github.com/OpenSees/OpenSees/pull/586

**Comment by fallahireza** [comment]
I appreciate you Prof. Scott, Look forward to seeing the next version soon.
