### ISSUE TITLE
The specified section deformation cannot be recorded

### ISSUE THREAD

**Issue by wangzhiyang123** [zhuminjie/OpenSeesPyDoc#237]
recorder('Element','-file','./nonlinear_frame_structure/defbeamsec_1.out','-time','-ele',3,'section',1,'deformation')
recorder('Element','-file','./nonlinear_frame_structure/defbeamsec_5.out','-time','-ele',3,'section',5,'deformation')
The above two lines of code get the deformation of the section at all integration points. Instead of the section deformation at integration points 1 and 5.I don't know if it's a bug.

In addition Is the function of RecorderDrift realized?

Thanks!

**Comment by zhuminjie** [comment]
recorder('Element','-file','./nonlinear_frame_structure/defbeamsec_1.out','-time','-ele',3,'section',1,'deformation')

I think 3 and 1 should be '3' and '1'

**Comment by mhscott** [comment]
Which version of openseespy are you using?

That issue should be fixed in future versions of openseespy. You won't need to put everything in ' '

**Comment by wangzhiyang123** [comment]
> recorder('Element','-file','./nonlinear_frame_structure/defbeamsec_1.out','-time','-ele',3,'section',1,'deformation')
> 
> I think 3 and 1 should be '3' and '1'
If I do, there will be only one column.

**Comment by wangzhiyang123** [comment]
> Which version of openseespy are you using?
> 
> That issue should be fixed in future versions of openseespy. You won't need to put everything in ' '

The version I use is 3.3.3.0

**Comment by wangzhiyang123** [comment]
> recorder('Element','-file','./nonlinear_frame_structure/defbeamsec_1.out','-time','-ele',3,'section',1,'deformation')
> 
> I think 3 and 1 should be '3' and '1'

If I do, there will be only one column.
