### ISSUE TITLE
Section DOF for sectionForce

### ISSUE THREAD

**Issue by frqc** [zhuminjie/OpenSeesPyDoc#24]
When I'm using [sectionForce](https://openseespydoc.readthedocs.io/en/latest/sectionForce.html), I notice that the force is return at given dof of section, which nowhere can I find its definition. 

I'm using a system with ndf=6 and sections are created with [fiber section](https://openseespydoc.readthedocs.io/en/latest/fibersection.html) to simulate a W or a box sections. I am expecting the dof of section to be 1 to 6, but the script fails when section dof is more than 4. 

To get the expected result (axial force, two shear forces, two moments and one torsion), how to define the section and how to use sectionForce correctly? And what's the meaning of the returned values considering its order? 

Thanks!

**Comment by zhuminjie** [comment]
When you set ndf=6 with model command, it sets the nodal ndf = 6. The ndf for section depends on the section you use. It seems you use a fiber section in 3D problem? For fiber 3D section, there are 4 section forces (P, Mz, My, T). If you want shear forces, you should use ND fiber section, which has 6 section forces (P, Mz, My, Vy, Vz, T). Thank you for pointing out, I will add to the document.

**Comment by frqc** [comment]
Thanks!
