### ISSUE TITLE
Perform several Transient Analysis for different GM using a loop

### ISSUE THREAD

**Issue by gamecult2** [zhuminjie/OpenSeesPyDoc#240]
Hello everyone
Recently I tried to perform a Transient Analysis using a loop for different Ground Motions.
The code used is shown below.
```python
# -------------------------------------------------------------------------------------------------------
# ----------------------- Define GROUND Motion ----------------------------------------------------------
# -------------------------------------------------------------------------------------------------------

# ------------------------ SELECTED GM ------------------------->   0,   1,   2
GM_sele = ['waves\GM\RSN1594_CHICHI_TTN051-E', 'waves\GM\RSN6896_DARFIELD_DORCN20W', 'waves\GM\ARTIFICIAL']
scal_fact = [0.4624, 0.1916, 1]            

Active_GM = np.zeros(len(GM_sele))
iter = 1
for i in range(0, len(GM_sele)):
    record = GM_sele[i]
    dt, nPts = ReadRecord.ReadRecord(record + '.at2', record + '.dat')
    GMfact = scal_fact[i] * 9806.65

    ## Record the output in different files for each Ground Motion GM1, GM2, GM3
    Active_GM = i    
    if Active_GM == 0:     ############### GM 1 Recorder ######################
        recorder('Node', '-file', f'GM\\Node_Disp_Y2_GM1.out', '-time', '-nodeRange', 1, 25, '-dof', 2, 'disp')
        recorder('Node', '-file', f'GM\\Node_Acc_Y2_GM1.out', '-time', '-nodeRange', 1, 25, '-dof', 2, 'accel')
    elif Active_GM == 1:   ############### GM 2 Recorder ######################
        recorder('Node', '-file', 'GM\\Node_Disp_Y2_GM2.out', '-time', '-nodeRange', 1, 25, '-dof', 2, 'disp')
        recorder('Node', '-file', 'GM\\Node_Acc_Y2_GM2.out', '-time', '-nodeRange', 1, 25, '-dof', 2, 'accel')
    elif Active_GM == 2:   ############### GM 3 Recorder ######################
        recorder('Node', '-file', 'GM\\Node_Disp_Y2_GM3.out', '-time', '-nodeRange', 1, 25, '-dof', 2, 'disp')
        recorder('Node', '-file', 'GM\\Node_Acc_Y2_GM3.out', '-time', '-nodeRange', 1, 25, '-dof', 2, 'accel')
    else:
        pass
    # -------------------------------------------------------------------------------------------------------
    # ----------------------- DYNAMIC ground-motion analysis (Transient analysis) -------------------
    # -------------------------------------------------------------------------------------------------------

    ## timesSeries with different Tag i and the correspondent pattern for each Ground Motion
    timeSeries('Path', iter , '-dt', dt, '-filePath', record + '.dat', '-factor', GMfact * 0.65)
    pattern('UniformExcitation', iter , 2, '-accel', iter )  

    # Create the transient analysis------------------------------------
    constraints('Transformation')
    numberer('Plain')
    system('FullGeneral')
    test('EnergyIncr', 1e-6, 200, 1)
    algorithm('ModifiedNewton')
    integrator('Newmark', 0.5, 0.25)
    analysis('Transient')
    analyze(nPts, dt)
    iter += 1
```
The problem is when I do so the time in the result output overlap and all the results are wrong.
I tried to use `WipeAnalysis()` and `setTime()` command after each analysis but still get the same error in the output results.

Thank you very much for your time!
Best,

**Comment by RPariona** [comment]
Hola, baje el archivo "Canti2DEQ.py", en la parte de establecer la amortiguación que copio programación a continuación.

timeSeries('Path', 2, '-dt', 0.01, '-filePath', 'BM68elc.acc', '-factor', 1) # define acceleration vector from file (dt=0.005 is associated with the input file gm)
pattern('UniformExcitation', 2, 1, '-accel', 2)		         # define where and how (pattern tag, dof) acceleration is applied

freq = eigen('-fullGenLapack', 1) ** 0.5
dampRatio = 0.02
rayleigh(0., 0., 0., 2 * dampRatio / freq)

wipeAnalysis()			     # clear previously-define analysis parameters
constraints('Plain')    	 # how it handles boundary conditions
numberer('Plain')    # renumber dof's to minimize band-width (optimization), if you want to
system('BandGeneral') # how to store and solve the system of equations in the analysis
test('NormDispIncr', 1 * 10 ** -8, 6)
algorithm('Newton')	 # use Linear algorithm for linear analysis
integrator('Newmark', 0.5, 0.25)    # determine the next time step for an analysis
analysis('Transient')   # define type of analysis: time-dependent
analyze(1000, 0.02)	 # apply 3995 0.01-sec time steps in analysis

y al correr la rutina me sale lo siguiente:

TypeError                                 Traceback (most recent call last)
<ipython-input-10-5ae84e9bc897> in <module>
      2 pattern('UniformExcitation', 2, 1, '-accel', 2)                  # define where and how (pattern tag, dof) acceleration is applied
      3 
----> 4 freq = eigen('-fullGenLapack', 1) ** 0.5
      5 dampRatio = 0.02
      6 rayleigh(0., 0., 0., 2 * dampRatio / freq)

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'float'

Como puedo saber cual es el error, gracias.

**Comment by mgrubisic** [comment]
Native Python does not support element-by-element operation "**". Convert a native Python list to a Numpy array if you have multiple frequencies. For only one frequency it is enough to write:

`omegaSquared = eigen('-fullGenLapack', 1)`
`omega = omegaSquared[0] ** 0.5`

**Comment by RPariona** [comment]
Thank you very much Marin.

Regards

Ronald Pariona
