### ISSUE TITLE
mass matrix

### ISSUE THREAD

**Issue by Likuikui12** [zhuminjie/OpenSeesPyDoc#241]
how can i calculate the mass matrix by opensees

**Comment by mhscott** [comment]
Please ask modeling questions on the OpenSees message board: https://opensees.berkeley.edu/community

**Comment by Likuikui12** [comment]
Thank you very much for your help



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Michael H. ***@***.***&gt;; 
发送时间: 2021年8月11日(星期三) 晚上7:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhuminjie/OpenSeesPyDoc] mass matrix (#241)





 
Please ask modeling questions on the OpenSees message board: https://opensees.berkeley.edu/community
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
