### ISSUE TITLE
ConcreteCM Documentation

### ISSUE THREAD

**Issue by siwalan** [zhuminjie/OpenSeesPyDoc#245]
For the Chang-Mandel 1994 concrete model, there is some inconsistencies with the documentation. In the documentation (https://openseespydoc.readthedocs.io/en/latest/src/ConcreteCM.html), it would imply that the command below would be valid

ops.uniaxialMaterial('ConcreteCM',4,8.09,-0.002371,5403.2172,15,1.022,0.335798,10000,'-GapClose',0);

However, using this command would instead result in a error.  But strangely, I tried to change the '-GapClose' with True (the full command is positioned below)

ops.uniaxialMaterial('ConcreteCM',4,8.09,-0.002371,5403.2172,15,1.022,0.335798,10000,True,0);

And it suddenly works. This would suggest to me that the documentation guide is not in match with the implementation of the function.

Furthermore, it seems for ops.element, for the SFI-MVLEM element, the Python parser does not check if the passed thickness, width, and material list is equal with the number of the macro-fiber passed.

For the attention given, thank you.

**Comment by siwalan** [comment]
![image](https://user-images.githubusercontent.com/59278902/144722716-14102472-025a-4dfd-aa42-bed3d0c836a3.png)

I run some further testing and found out that the problems seems to be related with the Python-Tcl translator. AFAIK, the TCL ConcreteCM command is 'unique' in the way that it requires a string parameter, while other command only requires float/numerical parameter*


*Based on my limited experience.

**Comment by zhuminjie** [comment]
Hi, thanks for finding an issue. First, OpenSeesPy is not a Python-Tcl translator. It is a native Python package. Although the underlying core functions are shared between Tcl and Python. The parsing is native and not related to each other.

The command documented is:

```python
uniaxialMaterial('ConcreteCM', matTag, fpcc, epcc, Ec, rc, xcrn, ft, et, rt, xcrp, '-GapClose', GapClose=0)
```

when you call with

```python
ops.uniaxialMaterial('ConcreteCM',4,8.09,-0.002371,5403.2172,15,1.022,0.335798,10000,'-GapClose',0)
```

You only gave it 8 inputs before ``'-GapClose'``, but 10 is required before ``'-GapClose'``.

The following works:

```python
ops.uniaxialMaterial('ConcreteCM',4,8.09,-0.002371,5403.2172,15,1.022,0.335798,10000,True,0)
```

because the two extra inputs can be interpreted as floating numbers, which completes the 10 inputs required, but the results could be wrong.

**Comment by zhuminjie** [comment]
However, your comments do help us to find a missing optional input. The command should be like:

```python
uniaxialMaterial('ConcreteCM', matTag, fpcc, epcc, Ec, rc, xcrn, ft, et, rt, xcrp, mon, '-GapClose', GapClose=0)
```

where ```mon``` is an optional input to denote monotonic stress-strain relationship. But in your case, since you only gave 8 or 10 inputs. This optional input was not touched at all.

**Comment by siwalan** [comment]
Thanks Dr. Zhu @zhuminjie . You are correct, I just checked it again and turns out I forgot the shape parameters. Thank you again for your correction and clarification on the command and the behavior of the package

But I do still have one more question, for the command, should GapClose be written so that the input is "GapClose=0", or we need to skip the "GapClose" and have the last input as "0"? Based on my interpretation of the documentation, 'GapClose' should be written... but as you know, the uniaxialMaterial() does not take any keyword argument. Should the last "GapClose" be removed from the documentation? 

![image](https://user-images.githubusercontent.com/59278902/144752661-76092e6b-2c04-4a5d-9d80-88962fe86057.png)


Furthermore (this question scope may be too broad), is it okay add Code 'Examples' (ala https://opensees.berkeley.edu/wiki/index.php/Model_command) in the documentation? Or it is not okay according to the documentation writing style/ terms of conduct.

**Comment by zhuminjie** [comment]
No, there is not keyword argument. We leave it as ``GapClose = 0`` to show the default value is 0. We have to keep ``GapClose`` there, because it's a variable not ``0``.

What do you mean by Code 'Examples', contribute your examples? Sure, you can send full request. Just follow the existing example for styles.

**Comment by siwalan** [comment]
Actually, command examples. The OpenSees Wiki sometimes have command example such as this at each of the function documentation. I attached some of the examples. I have to note that this kind of examples only exist partially, not all the command documentation have example attached below
![image](https://user-images.githubusercontent.com/59278902/144753002-f92c63d0-5ef4-4eb8-ac44-5c4b838f8f5b.png)
![image](https://user-images.githubusercontent.com/59278902/144753101-81c05568-24c7-4bea-9ca2-8465168d2285.png)

("Command" examples from other library, just as a reference)
![image](https://user-images.githubusercontent.com/59278902/144753156-83d31364-77fb-4f91-bece-a49a5124b48e.png)


I think, it would greatly help beginner to learn about how to use the command.

**Comment by zhuminjie** [comment]
Yes, you are welcome to add command example.
