### ISSUE TITLE
eleResponse, eleForce, element Recorder returning forces in global coordinate system instead of local coordinate system

### ISSUE THREAD

**Issue by IFCManager** [zhuminjie/OpenSeesPyDoc#248]
Openseespy version == 3.2.2.3
[test files.zip](https://github.com/zhuminjie/OpenSeesPyDoc/files/7727584/test.files.zip)

I noticed that my beamColumnElement, which is angled, returns the same forces using eleForce or recorder commands as a reaction forces retrieved by nodeReaction.

Tested this on different simple examples, such as vertical column element, two beams under different angles and a file from youtube tutorial and all of my test returns same forces for element and for reactions, which is incorrect, the forces for elements should be in local coordinate system and should not be identical to reaction forces.

I am attaching my test files (comments at the end are results that I am getting)

**Comment by sewkokot** [comment]
To get the forces in the local crd system use the 'localForce' option in the recorder and eleResponse; instead of 'forces' or 'force' . By default, in OpenSees, the 'forces' and 'force' options are equal to 'globalForce'/'globalForces'.

**Comment by IFCManager** [comment]
> To get the forces in the local crd system use the 'localForce' option in the recorder and eleResponse; instead of 'forces' or 'force' . By default, in OpenSees, the 'forces' and 'force' options are equal to 'globalForce'/'globalForces'.
> 
> See, for instance: https://opensees.berkeley.edu/wiki/index.php/Force-Based_Beam-Column_Element

Much thanks, now its working properly. One would think that the forces should be in local system by default and could not find any other information about that on the openseespy wiki.

**Comment by sewkokot** [comment]
For modelling related questions you can also search the OpenSees Message Board:

https://opensees.berkeley.edu/community/viewtopic.php?f=2&t=66373&p=114026&hilit=localForce#p114026
