### ISSUE TITLE
How to save the output of dam break+opensees.py

### ISSUE THREAD

**Issue by AzamAbdollahi** [zhuminjie/OpenSeesPyDoc#25]
Good afternoon,

I have a question about the output of "dambreak" file. how to save only pressure or velocity of one point in specific time? I changed the value of "dT" but I didn't see any changes in my results. 
recorder('PVD', filename, 'precision=4.0','dT=0.5', 'pressure')

thanks,

**Comment by zhuminjie** [comment]
If you want to save at specific time, create the recorder at the desire time.

To call recorder correctly, check here

https://openseespydoc.readthedocs.io/en/latest/pvdRecorder.html

**Comment by AzamAbdollahi** [comment]
Thank you for response, I try to save the date only at t=2s but the program
take all step times. I changed the dT to different values but nothing
changed. would you write the comment that I can use for this case?

Regards,

Azam Abdollahi

**Comment by zhuminjie** [comment]
Check the link above, the correct way to call PVD recorder is 

recorder('PVD', filename, '-precision',4,'-dT', 0.5, 'pressure')

in the loop of time stepping, such as

while dt < totaltime:
     if currentTime = 2.0:
          recorder('PVD', ...)

**Comment by AzamAbdollahi** [comment]
Good morning,

Thank you for good point, I used your command in my program. I thought it
was possible to decrease the running time but it was the similar. I would
like to find the hydraulic problem and it will be fast running. In this
case, do you have any suggestion with opensees-FSI?

Regards,


Azam Abdollahi

**Comment by zhuminjie** [comment]
Check dt in PVD rcorder won't change the time step. The time step has been set in analyze command. The dt here is to save data in every dt time. If you want save less data, try larger dt here.
