### ISSUE TITLE
Errors in Example (example_name_spaced_nonlinear_sdof.py)

### ISSUE THREAD

**Issue by boustrephon** [zhuminjie/OpenSeesPyDoc#257]
Hi MinJie,

Thanks for all your work on this.

I had trouble running one example so I have fixed it and attached the corrected Python file. 

The problems were that the duhamel library has been deprecated, and the eigenvector solution generates a list.

I have also included the constants (so that note is no longer required), and I have automated the download of the EQ datafile using `requests`. Neither of the two additional files are therefore required now.

[example_name_spaced_nonlinear_sdof.txt](https://github.com/zhuminjie/OpenSeesPyDoc/files/8008096/example_name_spaced_nonlinear_sdof.txt)

**Comment by vnodkumaryadav** [comment]
Thank you

**Comment by mhscott** [comment]
Which example? Where is the URL or description of the original? It if's from OpenSeesPy, make a PR to update or add an example.

**Comment by boustrephon** [comment]
Hi @mhscott : the relevant location is here: https://openseespydoc.readthedocs.io/en/latest/src/exampleNamedSpacedNonlinearSDOF.html

How do I do a PR for this?

**Comment by mhscott** [comment]
There are many tutorials online for how to make a pull request (PR) to a GitHub repo.

**Comment by boustrephon** [comment]
Do I clone this repository? I can't find the file that I need to change.
