### ISSUE TITLE
openseespy not running in centos linux

### ISSUE THREAD

**Issue by nithinvl** [zhuminjie/OpenSeesPyDoc#26]
I have been using openeespy in my linux system (Fedora OS) and it is running fine. Presently I am trying to use openseespy in our campus central server machine which is having Centos OS. I tried running openseespy there, but it is failing with some errors.
Initial error was :
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found

I solved this by installing glibc-2.14 and then i ran. But it is showing the following error :
ImportError: /usr/lib64/libgfortran.so.3: version `GFORTRAN_1.4' not found

Our campus central server personnel told that this opensees.so file is not compatible with the architecture of the server. I am more interested in running openseespy in this server as it is having many cores and more cpu memory allowing me to run many openseespy executables for performing many analysis cases simultaneously saving a huge amount of time.
Since the opensees.so file is not compatible with this server, could you kindly provide an opensees.so file compatible with Centos OS.

Hoping for your kind help and time in this regard.

Thank You.

Regards

Nithin V.L
PhD Structural Engineering
IIT Guwahati
India

**Comment by nithinvl** [comment]
I am not talking about any parallel version anywhere in my query. I am talking about compatibility of openseespy with linux centos OS.

**Comment by frqc** [comment]
From the [link](https://stackoverflow.com/questions/32316707/rhel-6-how-to-install-glibc-2-14-or-glibc-2-15) it seems the problem is related to the compiler used in your os. 

I guess you need to check the version of your compilers and let the Makefile.def using the correct one

**Comment by nithinvl** [comment]
Hi frqc,
I am new to Linux environment and compilation of source codes of OpenSees. Could you help me out ?
Nithin

**Comment by frqc** [comment]
> Hi frqc,
> I am new to Linux environment and compilation of source codes of OpenSees. Also the source codes provided in the above link are for making OpenSees python executable ? I am trying to compile for a long time in linux, but not able to do it successfully since I am new to compiling using makefiles and so many source codes, Hoping for your kind help.
> Nithin

Yes, you need to clone the main repo of opensees and compile it. The correct Makefile will solve file organization and the whole compilation can be done with one single command with a Makefile configured for your environment. 

If you have spent too much time to configure the compilation (like more than an hour), ask a CS major friend or the system manager may solve your pain quickly.

**Comment by nithinvl** [comment]
Hi frqc,
I have changed the Makefile.def as per my little knowledge. I am attaching the Makefile.def file and also compilation messages. Kindly help me.
[Makefile.txt](https://github.com/zhuminjie/OpenSeesPyDoc/files/2663651/Makefile.txt)
[compilation_log.txt](https://github.com/zhuminjie/OpenSeesPyDoc/files/2663644/compilation_log.txt)

Regards
Nithin

**Comment by zhuminjie** [comment]
The opensees.so is actually compiled in centos 7.0. What the version of your centos?

**Comment by frqc** [comment]
My guess is the compiler tries to link some lib but cannot find it. Have you create the folder named ‘lib’ and ‘bin’ ?

Besides does your school server support docker? If so I could write a docker file really soon which can compile the opensees (almost) os-independently. If not Singularity is also supposed to work but I don’t have the test environment

**Comment by nithinvl** [comment]
Sorry i forgot to mention that the Makefile.txt and compilation_log.txt files were made when i tried to compile in my system (which is having Fedora 24 OS). I am aware that the compilation of the codes require additional packages for which i am facing problems as central server has some restrictions on installation of such packages. I am trying to learn the compilation procedure (currently in Fedora OS) as to see whether I can somehow bypass these restrictions or I can request the server personnel for help.
If i am unable to compile the source codes, it would be helpful if i could get a linux version of opensees compatible to the central server. The server is having the OS "CentOS release 6.6 (Final)".

Regards
Nithin

**Comment by zhuminjie** [comment]
It does requires linux experience to compile OpenSees. It's a good suggestion to have a compiling guide.

tcl is not needed for openseespy, it is there because makefile.def is really for comping tcl version of opensees. 

to compile the python version, you need 'make' in SRC/interpreter

**Comment by nithinvl** [comment]
Could you upload a tutorial for compilation as soon as possible ? It will be really helpful.

**Comment by zhuminjie** [comment]
Yes, I can put a tutorial for compilation soon.
