### ISSUE TITLE
Changelog for  v3.3.0.1, v3.3.0.1.1 and v3.4.0.1?

### ISSUE THREAD

**Issue by firai** [zhuminjie/OpenSeesPyDoc#263]
It seems like only changes up to v3.3.0.0 have been added to the [changelog](https://github.com/zhuminjie/OpenSeesPyDoc/blob/master/src/changelog.rst). Can changes corresponding to v3.3.0.1, v3.3.0.1.1 and v3.4.0.1 be added? Thanks!

**Comment by zhuminjie** [comment]
Yes, we can add the changelog.
