### ISSUE TITLE
Tunnel lining in OpenSeespy

### ISSUE THREAD

**Issue by MehrshadGh** [zhuminjie/OpenSeesPyDoc#264]
Hi, thanks for your excellent work, I have learned quite a lot from that. I would like to ask Professor Scott a question about modeling tunnel lining.
I read the thesis of Stephanie Lange "Numerical Response of Concrete-Lined Tunnels Crossing Active Faults". How can be modeled soil spring with a zero-length section? It is not clear. I tried to model with zero-length element and Elastic no tension material, but this did not work. You will be of great help to me if you give me guidance.

**Comment by mhscott** [comment]
This repo is for documentation of OpenSeesPy. Please post general modeling questions on the OpenSees message board or OpenSees Facebook group.
