### ISSUE TITLE
addToParameter command 

### ISSUE THREAD

**Issue by luca-marella** [zhuminjie/OpenSeesPyDoc#265]
Dear Minjie,
I'm using the last version of OpeenSeesPy (3.4), and trying to make a sensitivity analysis I got a problem with the "addToParameter" command.

Scenario 1:
using that command with 'elasticBeamColumn' element all works fine.

Scenario 2:
using that command with a shell element, for example with 'ShellMITC4' or 'ASDShellQ4', I obtain this error:

Parameter::addComponent 1 -- no objects were able to identify parameter E

I'd appreciate your kind help in troubleshoting this problem.
 
Thanks in advance and congrats for your amazing work with Python porting.

Regards.

**Comment by mhscott** [comment]
The parameter methods are not implemented for those elements.

**Comment by luca-marella** [comment]
Dear prof. Scott,
thanks for your real-time reply.
If I use the same analysis using a TCL script and the OpenSees solver, it works fine with those kind of elements.
That means there at moment no shell elements can be used in sensitivity analysis in OpenSeesPy?
Thanks for your reply.

**Comment by mhscott** [comment]
Then it should work in OpenSeesPy too. Make sure you are using the latest version of OpenSeesPy.
