### ISSUE TITLE
Parametric earthquake analyses with OpenSeesPy Parallel

### ISSUE THREAD

**Issue by ihsanenginbal** [zhuminjie/OpenSeesPyDoc#266]
I have an OpenSeesPy model which runs parametric analyses with multiple earthquake records. The existing version of my model runs on a single CPU core. I would like to distribute these analyses to multiple cores on Ubuntu 20.04.

What I want to do is, in the below structure of nested loops, I would like to send each analysis to a different core. 

for each record
    for each value of parameter 1
        for each value of parameter 2
             for each value of parameter 3
                   CONSTRUCT THE MODEL AND RUN

Is this possible? 

The examples in the documentation are not referring to a case like this, as far as I understand. When I try to implement these examples in my model, I end up each allocated CPU core runnning the whole set analyses seperately (so instead of sharing the analyses, each core runs the entire set).

Could you help me on that?

Thank you.

**Comment by najafice** [comment]
Hi @ihsanenginbal ;
I would recommend this video of Dr. Mazzoni, It would be very helpful.

https://www.youtube.com/watch?v=fZQ6pP6sfqg
