### ISSUE TITLE
Inputting load factor values in Path TimeSeries not working

### ISSUE THREAD

**Issue by nithinvl** [zhuminjie/OpenSeesPyDoc#27]
Hi
I have written a code for timehistory analysis which reads each ground motion from a text file containing the list of ground motion filenames. The ground motion files are in a two column format. I am reading the data from the ground motion file as
    import numpy as np
    data = np.loadtxt(filename)
    shape = np.shape(data)
    data_length = shape[0]
    time = data[0:data_length,0]
    acceleration = data[0:data_length,1]

and then assigning it to the timeseries as
timeSeries('Path', accelseries_timetag, '-dt', dt, '-values',[1.0,1.0,1.0], '-factor', GMfatt)

But when I run, I am getting the following error :
WARNING choice of options for path series is invalid
Traceback (most recent call last):
  File "run_wo.py", line 69, in <module>
    exec(open('building1.py').read())
  File "<string>", line 34, in <module>
  File "<string>", line 53, in <module>
SystemError: <built-in function timeSeries> returned NULL without setting an error

In the manual, it is written that the load factor values should be inputted as list(float) values, I tried some ways to input as list, but not working, Is there any specific format in which I should input the values ? 

Note: The same script I had written in tcl and it is working successfully, I had used many times before for my analyses.

Regards
Nithin

**Comment by zhuminjie** [comment]
To use lists in OpenSeesPy, you have to call it as "*values". Also the numpy array doesn't work with openseespy. in your case, first convert numpy arrays to lists and call them as

timeSeries('Path', tag, '-dt', dt, '-values',*values, '-factor', GMfatt)

**Comment by nithinvl** [comment]
Sorry in my query I wrote 
timeSeries('Path', accelseries_timetag, '-dt', dt, '-values',[1.0,1.0,1.0], '-factor', GMfatt)
instead of
timeSeries('Path', accelseries_timetag, '-dt', dt, '-values',acceleration, '-factor', GMfatt)

**Comment by nithinvl** [comment]
> To use lists in OpenSeesPy, you have to call it as "*values". Also the numpy array doesn't work with openseespy. in your case, fi
