### ISSUE TITLE
Return value is None using "modalProperties" function

### ISSUE THREAD

**Issue by luca-marella** [zhuminjie/OpenSeesPyDoc#273]
Dear Minjie,
with the 3.4.0.2 version of OpenSeesPy and Python 3.9, I'm trying to use the **_modalProperties_** function in this way:

![image](https://user-images.githubusercontent.com/96304887/198691714-68b4e445-3506-4956-b244-f06374961f89.png)

but the _**data**_ variable is always None.

I would appreciate your kind help to undestand if I'm doing something wrong.

Thanks in advance and best regards.
L

**Comment by mhscott** [comment]
The `-return` option is a pending PR (https://github.com/OpenSees/OpenSees/pull/1042) in OpenSees, so the feature will not be part of OpenSeesPy until the next pip version

**Comment by luca-marella** [comment]
Thanks prof. Scott for your reply.
When you plan the next pip version?
