### ISSUE TITLE
Incoherency in printing the java file vs console

### ISSUE THREAD

**Issue by mlaura1996** [zhuminjie/OpenSeesPyDoc#274]
Dear @zhuminjie,
I think I found an issue with the printing function. As you can see in the image below when I print the model file in a js file, for the tetrahedron elements, there is missing one node. When I print in the console, the node are correctly 4
![image](https://user-images.githubusercontent.com/99893051/201067280-e49a0871-3045-40d5-87d5-b392fa37e641.png)

**Comment by mhscott** [comment]
Fixed, thanks! https://github.com/OpenSees/OpenSees/commit/034b07b0771a876d1e7e43e60bbf7cbf256b7bfb
