### ISSUE TITLE
OpenSeesError: See stderr output

### ISSUE THREAD

**Issue by chriss-1994** [zhuminjie/OpenSeesPyDoc#276]
Hello everyone, 

I am new to Opensees. I have an issue in running a file and don't know how to fix it, hope you can help.

When I run the file, I get this message:

**runfile('G:/My Drive/Posao/disertacija/numeričko modeliranje_opensees/ModelFunctions.py', wdir='G:/My Drive/Posao/disertacija/numeričko modeliranje_opensees')
Traceback (most recent call last):

  File "G:\My Drive\Posao\disertacija\numeričko modeliranje_opensees\ModelFunctions.py", line 116, in <module>
    getSections()

  File "G:\My Drive\Posao\disertacija\numeričko modeliranje_opensees\ModelFunctions.py", line 81, in getSections
    ops.section('Fiber', 100)

OpenSeesError: See stderr output**

The problem is that yesterday command ops.section('Fiber', 100) worked and everything ran perfectly and today it does not, although I didn't change a thing.

I have a Spyder version 5.2.2.

**Comment by laiqi1017** [comment]
> Track down the error. Replicate in a simple script what you're doing in the script. You can't be that new to OpenSees if you are already using helper functions and multiple scripts!`ModelFunctions.py`
> 
> Also, this repo is for documentation of OpenSeesPy, not modeling issues and other errors. Just documentation. You can get more detailed help on the OpenSees message board or the Facebook group.

SO，OpenSeesError: See stderr output**  means there is nothing wrong？I just go on with my modeling work？
