### ISSUE TITLE
uniaxialMaterial pyliq pult pult reduction failure

### ISSUE THREAD

**Issue by wangzhiyang123** [zhuminjie/OpenSeesPyDoc#277]
Through repeated tests, the calculation results of uniaxialMaterial pyliq and pysimple in openseespy are completely consistent, but there are obvious differences in opensees.

**Comment by mhscott** [comment]
Not sure what you mean, but post a minimal working example over at the [OpenSees GitHub page](https://github.com/OpenSees/OpenSees).
