### ISSUE TITLE
Module Not Found Error

### ISSUE THREAD

**Issue by JiaweiChenKodomo** [zhuminjie/OpenSeesPyDoc#28]
Dear Dr. Zhu,
When I tried to import the openseespy package using the following code:

`import sys
sys.path.append('E:\OpenseesFile\openseespy\win') #this is my directory

import numpy as np

import matplotlib.pyplot as plt

from opensees import *`

I got the following error:

`ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-20-268f7805acfe> in <module>()
      7 import matplotlib.pyplot as plt
      8 
----> 9 from opensees import *

ModuleNotFoundError: No module named 'opensees'`

I also tried "pip install openseespy" and "import openseespy.opensees as ops", but it did't make much difference: it still couldn't find "opensees".

I am using Win10 (x64)+ Anaconda 3.5.3.1. My Python version is 3.7.0. I have ActiveTcl 8.5.18.0 installed and the Opensees binary works fine. 

Could you please provide some suggestions as to what should I do? Is the Anaconda version a problem? (But why would the version issue cause trouble in finding the module?)

Thanks a lot for your time!

**Comment by zhuminjie** [comment]
In windows, the path should use slash instead of back splash

import sys
sys.path.append('E:/OpenseesFile/openseespy/win')

**Comment by JiaweiChenKodomo** [comment]
Dear Dr. Zhu,
Thank you for your response. I changed the path to the one with slashes, but still it can't find the "Opensees" module and returns a "ImportError: DLL load failed: The specified module could not be found" error.
What do you think is the problem? I will try using Python 3.6 and Anaconda 5.0 now and see if that works.

**Comment by zhuminjie** [comment]
That means you have imported the module. But for some reason, it works only for python 3.6. There is some inconsistency between python 3.7 and python 3.6. You can reinstall Python 3.6.

**Comment by JiaweiChenKodomo** [comment]
Thank you, Dr. Zhu. It is the problem with Python 3.7.

**Comment by JiaweiChenKodomo** [comment]
Thank you, Zarhin. For my case it seems to be the problem with Python 3.7. I tried pip on Python 3.7 and it didn't work.
