### ISSUE TITLE
openseespy v3.4.0.5 windows installation error

### ISSUE THREAD

**Issue by em812** [zhuminjie/OpenSeesPyDoc#283]
I tried installing openseespy after the release of version 3.4.0.5 using:
`pipenv install opneseespy`

and I am getting the following error:

> ERROR: Could not find a version that matches openseespywin>=3.4.0.5
> Tried: 3.2.2.9, 3.2.2.10, 3.3.0.0, 3.3.0.1

I tried requesting an older  version of openseespy with:
`pipenv install openseespy=3.3`
but this still produces the same error.

In conclusion, the windows installation of version 3.4.0.5 is not working. 

The only way I have found to install the library is by specifying an older version both for openseespy and for openseespywin:
pipenv install "openseespy==3.3.0.1.1" "openseespywin==3.3.0.1"

**Comment by zhuminjie** [comment]
It should be ``pip install openseespy``

https://pypi.org/project/openseespy/
