### ISSUE TITLE
Why there is not  BraceMaterial in OpenSeesPY??

### ISSUE THREAD

**Issue by sushisann** [zhuminjie/OpenSeesPyDoc#287]
How to build BraceMaterial??

**Comment by mhscott** [comment]
Thanks for pointing that out. BraceMaterial is basically HystereticMaterial but with a wrapper on strains. You can get the same behavior out of MinMaxmaterial + HystereticMaterial.

**Comment by sushisann** [comment]
thank you very much

**Comment by sushisann** [comment]
could you tell me some details about that??

**Comment by sushisann** [comment]
I have been worried about this for a long time.
