### ISSUE TITLE
Import error with most recent Anaconda

### ISSUE THREAD

**Issue by ozsahinecem** [zhuminjie/OpenSeesPyDoc#290]
Hi All,

I have downloaded the most recent Anaconda release which comes with Python 3.10.9. When I try to import Openseespy I encountered an error that says 'Python version 3.8 is needed for Windows'). Does this mean Openseespy has not been updated to support Python 3.10? Should I download an older version of Anaconda?

**Comment by mhscott** [comment]
The latest version of OpenSeesPy should work with Python 3.10 now.
