### ISSUE TITLE
eigen function 

### ISSUE THREAD

**Issue by IFFI11Q** [zhuminjie/OpenSeesPyDoc#295]
hello guy, can anyone help me about this function issue -Error Main (line 41)
[~,~, omg,~,~, phi]=eigenvalue (m ', k');% Find the frequency omg and period T of each order of the original structure;

**Comment by mhscott** [comment]
That's not OpenSeesPy syntax. More context of what you're doing is required. See examples for how to compute eigenvalues in OpenSeesPy.
