### ISSUE TITLE
Postprocessing.Get_Rendering

### ISSUE THREAD

**Issue by SamAbd8** [zhuminjie/OpenSeesPyDoc#299]
Hi
When I import "openseespy.postprocessing.Get_Rendering," I get
 ModuleNotFoundError: No module named 'openseespy.postprocessing.Get_Rendering'

**Comment by zhuminjie** [comment]
Get_Rendering is no longer in openseespy for a long time. Please check the documentation

https://openseespydoc.readthedocs.io/en/latest/src/postprocessing.html

**Comment by SamAbd8** [comment]
Even "opsvis"?

**Comment by mhscott** [comment]
Yes. https://opsvis.readthedocs.io/en/latest/index.html
