### ISSUE TITLE
Stress-strain recorder for fiber section

### ISSUE THREAD

**Issue by anurag-upadhay** [zhuminjie/OpenSeesPyDoc#3]
Please add the recorder commands to record "stress-strain" in a fiber section and W-section in _nonLinearBeamColumn _Elements__.

**Comment by zhuminjie** [comment]
I think this could be done in the element recorder

**Comment by anurag-upadhay** [comment]
I used the following command but did not work. Maybe I am doing it wrong. 

`recorder('Element', '-file', "PushoverOut/BeamStress.out", '-closeOnWrite', '-element', 102, '-section', 4, '-fiber',4,0, '-mat', 1 , 'stressStrain')`

**Comment by zhuminjie** [comment]
@anurag-upadhay Could you please send you script? Thank you!
