### ISSUE TITLE
MVLEM model - Load command and gravity load increasing period significantly 

### ISSUE THREAD

**Issue by LiamPledger** [zhuminjie/OpenSeesPyDoc#302]
Hi All, 

I've developed a simple wall structure using the MVLEM model in OpenSeesPy. I get a period of 0.378 sec before applying gravity load. (This matches well with the SAP2000 model and hand calcs done in MathCAD ~ 0.38 s). However, when I apply gravity load using the Load command and then get the period after gravity load analysis, the period is 0.93 sec. I know there is clearly something drastically wrong however I can't work out what exactly. I have checked units and that is not the problem. I have developed an RC frame model in opensees previously and period changes approx <1% when applying gravity load. 

Even changing the direction of the load to +ve (upwards) which should reduce the period by increasing stiffness leads to the same period of 0.93 sec. I have also tried changing the transformation from Corotational to Linear and this doesn't do anything.

Any help would be greatly appreciated,
Cheers,
Liam

![image](https://github.com/zhuminjie/OpenSeesPyDoc/assets/145072932/6b34efde-0832-44ac-8934-25d5a77c5d14)
![image](https://github.com/zhuminjie/OpenSeesPyDoc/assets/145072932/d2353a10-2df7-4b47-b16f-171b23de6485)
![image](https://github.com/zhuminjie/OpenSeesPyDoc/assets/145072932/6342b2b3-606d-43e2-94e3-7f792a55bb30)
![image](https://github.com/zhuminjie/OpenSeesPyDoc/assets/145072932/257a5511-b6d6-4aa5-b0f9-af4f0f521676)
![image](https://github.com/zhuminjie/OpenSeesPyDoc/assets/145072932/ec7c33d0-c101-470d-912f-5585b4a66eee)

**Comment by mhscott** [comment]
This repo is for the documentation of OpenSeesPy.

Please post modeling questions and issues on the OpenSees message board or Facebook group.
