### ISSUE TITLE
opensees

### ISSUE THREAD

**Issue by Qingtian9426** [zhuminjie/OpenSeesPyDoc#307]
Dear colleagues, when encountering eigenvalue problems during the gravity analysis of a cable-stayed bridge in OpenSees, how should we proceed with checking the issue, given that the constraints appear to be without issues.
FullGenEigenSolver::solve()the eigenvalue 1 is numerically undetermined or infinite
FullGenEigenSolver::solve()-the eigenvalue 2 is numerically undetermined or infiniteinfinite
FullGenEigenSolver::solve()the eigenvalue:3 is numerically undetermined or  infiniteinfinite
FullGenEigensolver::solve()the eigenvalue 4 is numerically undetermined or infinite
FullGenEigenSolver::solve()the eigenvalue 5 is numerically undetermined or infinite.
FullGenEigenSolver::solve()theeigenvalue6 is numerically undetermined or infinite.
FullGenEigenSolver::solve()-the eigenvalue 7 is numerically undetermined or infinite
FullGenEigenSolver::solve()the eigenvalue:8 is numerically undetermined or infinite
FullGenEigenSolver::solve()- the eigenvalue 9 is numericallyundetermined or infinite
FullGenEigenSolver::solve()the eigenvalue:10 is numerically undetermined or infinite
FullGenEigenSolver::solve()the eigenvalue11 is numerically undetermined or infinite
FullGenEigensolver::solve()-the eigenvalue 12 isnumerically undetermined or infinite

**Comment by mhscott** [comment]
You probably need to move the nodes around slightly
https://portwooddigital.com/2021/11/22/cable-analysis/
Or, you can fix the rotational DOFs of the cable nodes.
