### ISSUE TITLE
Node  Recorder Command

### ISSUE THREAD

**Issue by shongwai** [zhuminjie/OpenSeesPyDoc#34]
Dear Dr Zhu,

How are you? I am trying to use the Node Recorder Command, a file was created but the response was not recorded in the file, can you please have a look, is there an error with the command?

Thank you.

**Comment by zhuminjie** [comment]
Did you figure it out?

**Comment by shongwai** [comment]
I wanted to use that for recording eigenvectors but it didn't work, I am using another command "nodeEigenvector" command instead.
