### ISSUE TITLE
Difference in timeperiod values by very small decimal values for the same model analyzed in tcl and python versions

### ISSUE THREAD

**Issue by nithinvl** [zhuminjie/OpenSeesPyDoc#35]
Hi
I modeled a vertical cantilever with rectangular section (Depth=0.4m and Width=0.2m) of height 1.0m. Steel01 material was assigned to the whole section using fiber patch command. I modeled in OpenSees (tcl version) and OpenSeesPy.
The timeperiod for model in OpenSeespy is 0.24884085015825474 s and for model in OpenSees (Tcl) is 0.2488408433834686 s. They are differing from eight decimal place. Could you explain the reason behind this ?

**Comment by zhuminjie** [comment]
That could be due to the input values in tcl and python
