### ISSUE TITLE
Uniaxial materials - PySimple1 Material and QzSimple1 Material

### ISSUE THREAD

**Issue by pavan1388** [zhuminjie/OpenSeesPyDoc#36]
Hello Dr. Zhu,

I hope you are doing good. The syntax for PySimple1 material is incomplete in the Openseespy page (https://openseespydoc.readthedocs.io/en/latest/PySimple1.html#pysimple1-material). I have used the syntax in a similar form available in Opensees and it works. Can you please update the syntax for this material. 

The QzSimple1 Material has some issues I guess, I was trying to run the code using the syntax from https://openseespydoc.readthedocs.io/en/latest/QzSimple1.html. It always returns an error as "returned NULL without setting an error". Can you please take a look into this and fix the issue. I really appreciate the help. 

Thank you,
Pavan

**Comment by zhuminjie** [comment]
Do you mean the syntax in the document is not complete or the command in OpenSeesPy is not working?

**Comment by pavan1388** [comment]
The syntax for PySimple1 material is incomplete but when I used the syntax similar to that in opensees tcl it works fine. 

The QzSimple1 Material has some issues in code I guess.

These two commands have two different issues.

**Comment by zhuminjie** [comment]
I have fixed the command PySimple1 in the documentation. For QzSimple1, can you send a script and point to where is wrong? Thank you!

**Comment by zhuminjie** [comment]
Does the PySimple1 work fine in Python?

**Comment by pavan1388** [comment]
> Does the PySimple1 work fine in Python?

Yes this works syntax (uniaxialMaterial('PySimple1', matTag, soildType, pult, Y50, Cd, c=0.0))

**Comment by pavan1388** [comment]
> I have fixed the command PySimple1 in the documentation. For QzSimple1, can you send a script and point to where is wrong? Thank you!

I will email you my code so that you can check the command there. thank you

**Comment by zhuminjie** [comment]
PySimple1 has been added to the new version.

**Comment by pavan1388** [comment]
> PySimple1 has been added to the new version.

Do you mean QzSimple1 Material, PySimple1 Material is already working.
Thank you.

**Comment by zhuminjie** [comment]
Yes,
