### ISSUE TITLE
pathseries::pathseries()

### ISSUE THREAD

**Issue by Jingyixiong** [zhuminjie/OpenSeesPyDoc#37]
Dear Dr.Zhu:
When I was running my program, I encountered a problem that the showed "WARNING - PathSeries::PathSeries() - could not open file A10000.dat". I installed tcl and also set all environment like numpy, matplotlib before I called the opensees, I do not know what happened, can you give me some advice?

**Comment by Jingyixiong** [comment]
Thank you for your reply, I just copied the first example of the earthquake in your web, and when it runs to the 
" pattern('UniformExcitation', 2, 1, '-accel', 2) " sentence  		         

Such an error occurs:
An internal error has occurred in the Interactive window.  Please restart Visual Studio.
WARNING - PathSeries::PathSeries() - could not open file A10000.dat
The interactive Python process has exited.

**Comment by zhuminjie** [comment]
Are you trying to compile your version of openseespy?

Did you put A10000.dat in the same folder?
