### ISSUE TITLE
Request: move *.py examples to a separate directory

### ISSUE THREAD

**Issue by sewkokot** [zhuminjie/OpenSeesPyDoc#39]
Since there is a long list of documentation *.rst files, the *.py example files are visually lost. Just a suggestion to *.py to examples/ directory.

**Comment by zhuminjie** [comment]
Thank you for your comments. Will you be able to help with that? Thank you!

**Comment by sewkokot** [comment]
Please see the relevant pull request.

**Comment by zhuminjie** [comment]
Thanks! It has been merged.
