### ISSUE TITLE
(Linux) OpenSeesPy Import Error: libgfortran.so.3 Error

### ISSUE THREAD

**Issue by gautham949** [zhuminjie/OpenSeesPyDoc#4]
I'm trying to install OpenSeesPy and added the path 

`sys.path.append('/home/gautham/Documents/openseespylinux/opensees.so')`

`from opensees import *`

and it shows the following 

`ImportError: libgfortran.so.3: cannot open shared object file: No such file or directory`

Can someone help me with the problem?

**Comment by zhuminjie** [comment]
when you add the path, you don't have to include the file name, just the path name 

sys.path.append('/home/gautham/Documents/openseespylinux')

**Comment by gautham949** [comment]
Thanks. I tried it and it still it shows the same error as I mentioned above.

**Comment by anurag-upadhay** [comment]
It happened to me when I was using Linux Mint. I could not find a way around and finally moved to Xubuntu (lighter ubuntu) and everything worked fine. The latest version of Ubuntu has all other libraries (including libgfortran) which made it easier.

**Comment by zhuminjie** [comment]
@anurag-upadhay Thank you for your reply! Good to know that Ubuntu resolves the problem.

@gautham949 Did you solve your problem?

Thank you @gautham949 and @anurag-upadhay for using OpenSeesPy, may I know what kind of projects or researches you are using OpenSeesPy for? This information will help us to improve the software. Thank you!

**Comment by mgrubisic** [comment]
First of all, thanks to Minjie for all efforts related to OpenSeesPy, we've been waiting for Python interpreter for a long time!
I personally encountered the same problems on my home machine, **Ubuntu 18.04.1** and also on my server machine (hosted by DigitalOcean), with the same version of Ubuntu. I encountered 3 problems, which required additional installations, **libgfortran.so.3**, **libpng15.so.15**, **libssl.so.10**, respectively.
These missing libraries are relatively easy to install, after which OpenSeesPy works without any difficulties.

**Comment by zhuminjie** [comment]
@mgrubisic Thank you for your inputs! I think this issue could be closed.

**Comment by gautham949** [comment]
> @anurag-upadhay Thank you for your reply! Good to know that Ubuntu resolves the problem.
> 
> @gautham949 Did you solve your problem?
> 
> Thank you @gautham949 and @anurag-upadhay for using OpenSeesPy, may I know what kind of projects or researches you are using OpenSeesPy for? This information will help us to improve the software. Thank you!

Thank you for the OpenseePy. It's amazing. I am using OpenSeesPy primarily for my research on seismic studies on gravity and arch dams.

**Comment by Zarhin** [comment]
> I'm trying to install OpenSeesPy and added the path
> 
> `sys.path.append('/home/gautham/Documents/openseespylinux/opensees.so')`
> 
> `from opensees import *`
> 
> and it shows the following
> 
> `ImportError: libgfortran.so.3: cannot open shared object file: No such file or directory`
> 
> Can someone help me with the problem?

Did you solve your problem? I met the same problem yesterday, and fix it by installing the libgfortran.so.3 using the command "sudo apt-get install libfortran3:amd64"
