### ISSUE TITLE
setParameter command

### ISSUE THREAD

**Issue by dlincoln** [zhuminjie/OpenSeesPyDoc#47]
Hi, can you help with calling the setParameter command - I can't find reference to it for controlling the frictional behavior of the contact elements? See docs 1.2.64 note 2.5. Apologies if I have overlooked anything. Many thanks.

**Comment by zhuminjie** [comment]
can you specify element? thank you

**Comment by dlincoln** [comment]
'BeamContact2D'

**Comment by zhuminjie** [comment]
The parameter command should be under the sensitivity. It is not there yet, but will be added soon. There are couple commands to set, update and get parameter values.  I will add them in the near future.

**Comment by dlincoln** [comment]
OK I see, thank you, I'll look forward.

**Comment by zhuminjie** [comment]
check out here

https://openseespydoc.readthedocs.io/en/latest/src/senscmds.html

**Comment by dlincoln** [comment]
Thanks for your help, may I ask how to call the Tcl command `setParameter -value 0 -eleRange 1001 1042 friction` in Python? I can't reference `ops.setParameter`. Please see line 2113 in the example  http://opensees.berkeley.edu/wiki/images/b/bc/Excavation.tcl found at http://opensees.berkeley.edu/wiki/index.php/Excavation_Supported_by_Cantilevered_Sheet_Pile_Wall

**Comment by zhuminjie** [comment]
The setParameter command is not there. I just added it. Please check it later.

**Comment by dlincoln** [comment]
Also a source fix/update perhaps?
![fix](https://user-images.githubusercontent.com/47535671/53504700-52d43100-3aaa-11e9-9739-e32aef220d7c.png)

**Comment by zhuminjie** [comment]
will soon

**Comment by zhuminjie** [comment]
It's updated now!
