### ISSUE TITLE
Opensees.py website bug

### ISSUE THREAD

**Issue by amihirata** [zhuminjie/OpenSeesPyDoc#49]
Dr. Zhu-
I've encountered a small bug with the opensees.py website where whenever searching for a command (in this example I searched for the layer command) the command will display twice and the first result will issue an error page, while the second will show the actual page for the command.  I've attached some screenshots below:

Thank you,
-Amedeo 

![search](https://user-images.githubusercontent.com/47037805/53027700-74427680-3433-11e9-9003-c34cb7b129b2.PNG)
![dne](https://user-images.githubusercontent.com/47037805/53027705-760c3a00-3433-11e9-9156-fa4a3b1177c9.PNG)

**Comment by zhuminjie** [comment]
I have noticed that.  There is no such problem when I compile it locally. It might be due to the sphinx version used by readthedocs.io. So I can do nothing about it.
