### ISSUE TITLE
The way to construct as truss element is confused

### ISSUE THREAD

**Issue by CodingThinking** [zhuminjie/OpenSeesPyDoc#55]
The fifth param in the  element('Truss', eleTag, *eleNodes, A, matTag[, '-rho', rho][, '-cMass', cFlag][, '-doRayleigh', rFlag]) is matTag or secTag, but if matTag and secTag has a same identifier, it will be confused. Will the fifth param be set into a keyword?

**Comment by zhuminjie** [comment]
Currently, we cannot implement the keyword, because the API interface was designed to accommodate different scripting languages, and the keyword is a unique feature for Python.

**Comment by CodingThinking** [comment]
Is there any possibility to  make a distinction between  matTag and secTag without keyword, e.g, use '-matTag' or '-secTag' before them? Besides, I find that the int8~64 in numpy can not be identified by element commend correctly. I use anaconda 2018.12.

**Comment by zhuminjie** [comment]
It is possible. But the command has been like that for many years. An easy solution will to setting "secTag" and "matTag" variables instead of using integer directly in the command.
