### ISSUE TITLE
Problem with nDMaterial('PressureIndependMultiYield')

### ISSUE THREAD

**Issue by Zarhin** [zhuminjie/OpenSeesPyDoc#56]
Hello Dr. Zhu:
       It still has a problem with system error when I use the PressureIndependMultiYield material in the new openseespy version(0.1.1).
      I use Anaconda in Windows and installed the openseespy package by pip command. A model works well with the ElasticIsotropic material, but when I use the PressureIndependMultiYield material, it has the problem as before (the test scrip as follow fig.).
      Thank you very much~
                                                                                                                              lizaixian |  BJUT                                                                                                                      
                            2019/03/26

![image](https://user-images.githubusercontent.com/40398481/54964631-2f68ad00-4fa8-11e9-8c0f-d6f2c6fef067.png)

**Comment by zhuminjie** [comment]
nDMaterial('PressureIndependMultiYield', matTag, nd, rho, refShearModul, refBulkModul, cohesi, peakShearStra, frictionAng=0., refPress=100., pressDependCoe=0., noYieldSurf=20, *yieldSurf)

Can you try to give more parameters of frictionAng, refPress, and pressDependCoe

**Comment by Zarhin** [comment]
> nDMaterial('PressureIndependMultiYield', matTag, nd, rho, refShearModul, refBulkModul, cohesi, peakShearStra, frictionAng=0., refPress=100., pressDependCoe=0., noYieldSurf=20, *yieldSurf)
> 
> Can you try to give more parameters of frictionAng, refPress, and pressDependCoe

Yes, I've already done that, but there's still this mistake.

**Comment by zhuminjie** [comment]
Did you call like:

nDMaterial('PressureIndependMultiYield', matTag, nd, rho, refShearModul, refBulkModul, cohesi, peakShearStra, frictionAng, refPress, pressDependCoe, noYieldSurf)

Those parameters are required. You probably miss the "refBulkModul"

**Comment by Zarhin** [comment]
![image](https://user-images.githubusercontent.com/40398481/56504604-a6fc0e80-654b-11e9-913b-dfab83db6d68.png)
I'm happy to see the openseespy is updated again, but the problems of 'PressIndependendMultiYield' material still exists, I give all the parameters of the material but it didn't work
Could you give some examples of this material? Thank you very much~

**Comment by zhuminjie** [comment]
The parameter "cohesi" should be a float, i.e. 37.0

**Comment by Zarhin** [comment]
It works!!! Thank you !!! 
And I saw the input format of the material, the format of the number of dimensions is a float? 
![image](https://user-images.githubusercontent.com/40398481/56702721-1afb0a00-6738-11e9-8952-f4ff88c0b1e4.png)
Thank you once more~
