### ISSUE TITLE
shellDKGT element cannot use

### ISSUE THREAD

**Issue by strdesigner** [zhuminjie/OpenSeesPyDoc#62]
Hello Dr. Zhu:
I want to use shellDKGT element through openseespy.
However, my program code wouldn't move with the message as follows:

"opensees.msg: WARNING element type shellDKGT is unknown"

My openseespy version is 0.2.0 (It's latest  as of today).

How can I use shellDKGT element through openseespy?

Thanks,
FUJITA

**Comment by zhuminjie** [comment]
The shellDKGT element is not in openseespy now. But the shellDKGQ does. Thank you for letting me know. I will add it in the next version.

**Comment by strdesigner** [comment]
Thank you for your immediate reply.
I look forward to being able to use shellDKGT in future updates.

Thanks,
FUJITA

**Comment by zhuminjie** [comment]
New version is updated

**Comment by Armando0793** [comment]
Hi Dr. Zhu
I have updated openseespy to the latest version 3.2.2.1 but when I try to use shellDKGT element I see the same message: "WARNING element type ShellDKGT is unknown".  Could please check if it's all right.
Thank you for your work

AZ

**Comment by mhscott** [comment]
Use lowercase 's' ... shellDKGT instead of ShellDKGT.  It should take both in the next update.

________________________________
