### ISSUE TITLE
Fail to start

### ISSUE THREAD

**Issue by anzhiyese** [zhuminjie/OpenSeesPyDoc#63]
Dr. Zhu:
I want to use openseespy. However, it fails to start with the message as follows:

"Traceback (most recent call last):
from openseespy.opensees.winpy37.opensees import *
ImportError: DLL load failed"

I've reinstall the openseespy for several times, but it doesn't work. So what should i do to solve the problem.

My openseespy version is 0.2.0.

Thanks,
Robin

**Comment by zhuminjie** [comment]
This is usually due to you have multiple python  installed.

**Comment by runlevel0** [comment]
I experienced the same problem - on my Windows machine I use anaconda to manage python environments.

A run with [DependencyWalker](http://www.dependencywalker.com/) on the openseespy\opensees\winpy37\opensees.pyd file showed that the "PYTHON37.DLL" and "TLC86T.DLL" cannot be found from the system path alone.
The "PYTHON37.DLL" is taken care of by the activated conda environment. This can be checked by running
> from ctypes.util import find_library
> theDll = find_library('PYTHON37')
> print(theDll)
which returns the Path to the "PYTHON37.DLL" in the conda environment.

Checking for "TLC86T.DLL" however returns None:
> from ctypes.util import find_library
> theDll = find_library('TCL86T')
> print(theDll)

The "TLC86T.DLL" is found in the "\DLLs" subdirectory of the conda environment. For this dll to be found by the opensees.pyd, the path to the dll has to be added to the system path variable with:
> import os
> os.environ['PATH'] = 'PATH_TO_CONDA_ENV\\DLLs' + os.pathsep + os.environ['PATH']

This solved the problem for me.

**Comment by anzhiyese** [comment]
Now i solve the problem, just import openseespy after numpy and matplotlib. Anyway, thanks a lot.

**Comment by billhu0228** [comment]
I meet the same problem and solve it by download and add opensees bin file to env Path. Guess tcl86t.dll is the failed DLL to loaded.

**Comment by awa5114** [comment]
Why do we have to manually add stuff to the path? Shouldn't the pip install automatically do this?

The whole point of using conda is being able to have several virtual environments with different versions of python installed.  Once the pip install is called from a particular environment it should be attached to the python executable in that environment and that environment only.

Activating the environment typically appends the path variable with all necessary paths. This is not something the user should do!
