### ISSUE TITLE
connection between CatenaryCable and beam

### ISSUE THREAD

**Issue by CodingThinking** [zhuminjie/OpenSeesPyDoc#65]
I need to connect a column-beam with a Catenary cable(3 freedoms of 1,2,3 for each node). I set two nodes at the same position for the two element, and use equalDOF  to couple the 1 2 3 freedom of these two points. However, the analysis throws out the warning of " WARNING FE_Element::setID() - numDOF and number of dof at the DOF_Groups " . I think there must some freedoms singular in the model. Can you help to tell me how to fix this problem?

**Comment by zhuminjie** [comment]
Is that 3D or 2D problem? Beams have additional rotation dof but cable don't. You only need to equalDOF tranlational dofs, like the connect between beam and truss

**Comment by CodingThinking** [comment]
It is a 3D problem, and I think I have done what you suggested. Here is my code: 
nd = np.array([
        [1, 0., 0., 0.],
        [2, 0., 0., 5.],
        [3, 10., 10., 10],
        [4, 0., 0., 5.]
        ])
    
elem = np.array(
        [[1, 1, 2],
         [2, 3, 4]]
        )

ops.wipe()
ops.model('basic', '-ndm', 3, '-ndf', 6 )
for x in nd:
    ops.node(int(x[0]), *x[1:])

ops.fix(1, 1, 1, 1, 1, 1, 1 )
#for x in cons:
ops.fix(3, 1, 1, 1,0, 0, 0)

ops.equalDOF(2, 4, 1, 2, 3)
    
ops.uniaxialMaterial('Elastic', 1, 1.98e8, 0., 1.98e8)
ops.uniaxialMaterial('Elastic', 2, 1.0e-3, 0., 1.0e-3)  
ops.section('Elastic', 101, 2.06e11, 2.684177e-2, 2.4261e-4, 2.4261e-4, 1.0e11, 4.852522e-4)
ops.section('Aggregator', 102, 1, 'Vy', 1, 'Vz', '-section', 101)
ops.beamIntegration('Lobatto', 1, 102, 5)
ops.geomTransf('Linear', 1, 1., 0., 0.)
ops.element('dispBeamColumn', 1, 1, 2, 1, 1)
ops.element('CatenaryCable', 2, 3, 4, -445., 1.85e11, 0.03775, 10.,
                            0., 0., -44.5, 1e-6, 400, 0)
ops.element('zeroLength', 3, 2, 4, '-mat', 2, 2, 2, '-dir', 4, 5, 6)

ops.timeSeries('Linear', 1, '-factor', 1.0)
ops.pattern("Plain", 1, 1)
ops.load(2, -10000., 0., 10000., 0., 0., 0.)
ops.system('BandGeneral')
ops.constraints('Transformation')
ops.numberer('RCM')
ops.test('NormDispIncr', 1.0e-4, 150, 1)
ops.integrator("LoadControl", 1.0)
ops.algorithm('Newton')
ops.analysis('Static')
aa = ops.analyze(1)

Can you help me to figure out where the bug is?

**Comment by zhuminjie** [comment]
I can run the codes without the problem you described, but it failed to converge

**Comment by CodingThinking** [comment]
If I replace the catenarycable with a corotruss, it will surely converge. Theoratically, it is confused. I will make a new model to test, and put the result here soon.

**Comment by CodingThinking** [comment]
nd = np.array([
        [1, 0., 0., 0.],
        [2, 5., 0., 0.],
        [3, 0., 5., 0.],
        [4, 0., 0., 5.],
        [5, 10., 10., 10],
        [6, 0., 0., 5.]
        ])

ops.wipe()
ops.model('basic', '-ndm', 3, '-ndf', 6 )
for x in nd:
    ops.node(int(x[0]), *x[1:])

ops.fix(1, 1, 1, 1, 1, 1, 1 )
ops.fix(2, 1, 1, 1, 1, 1, 1)
ops.fix(3, 1, 1, 1, 1, 1, 1 )
ops.fix(5, 1, 1, 1, 1, 1, 1)
#ops.fix(4, 1, 1, 1, 1, 1, 1)

ops.equalDOF(4, 6, 1, 2, 3)
    
ops.uniaxialMaterial('Elastic', 1, 1.98e11, 0., 1.98e11)
ops.uniaxialMaterial('Elastic', 2, 1.0e-3, 0., 1.0e-3)  
ops.section('Elastic', 101, 2.06e11, 2.684177e-2, 2.4261e-4, 2.4261e-4, 1.0e11, 4.852522e-4)
ops.section('Aggregator', 102, 1, 'Vy', 1, 'Vz', '-section', 101)
ops.beamIntegration('Lobatto', 1, 102, 5)
ops.geomTransf('Linear', 1, 1., 0., 0.)
ops.geomTransf('Linear', 2, 0., 1., 0.)
ops.element('dispBeamColumn', 1, 1, 4, 1, 1)
ops.element('dispBeamColumn', 2, 2, 4, 2, 1)
ops.element('dispBeamColumn', 3, 3, 4, 1, 1)
ops.element('CatenaryCable', 4, 5, 6, -3000., 1.85e11, 0.03775, 18., 0., 0., -300., 1e-6, 600, 0)
ops.element('zeroLength', 5, 4, 6, '-mat', 2, 2, 2, '-dir', 4, 5, 6)

ops.timeSeries('Linear', 1, '-factor', 1.0)
#ops.pattern("Plain", 1, 1)
#ops.load(4, -10000., 0., 10000., 0., 0., 0.)
ops.system('BandGeneral')
ops.constraints('Transformation')
ops.numberer('RCM')
ops.test('NormDispIncr', 1.0e-4, 150, 1)
ops.integrator("LoadControl", 1.0)
ops.algorithm('Newton')
ops.analysis('Static')
aa = ops.analyze(1)

The code above is a new code. On the node 4 cable and beam are coupled. Calculation converged but not right. The result indicates that the forces are not conducted  to  beams. Is there any thing wrong in my code or any thing wrong in opensees?
