### ISSUE TITLE
Steel 02 Is not working

### ISSUE THREAD

**Issue by vacalderon** [zhuminjie/OpenSeesPyDoc#66]
Hello I was converting one of my tcl scripts to openseespy format while I was trying to use Steel02 and I get this message

msg: Invalid #args, want: uniaxialMaterial Steel02 3 fy? E? b? <R0? cR1? cR2? <a1? a2? a3? a4?>>

I'm using the arguments as specified in the manual, a1,a2,a3 and a4 are supposed to be optional right? so those are the only arguments I am not inputting. Let me know if you get this problem.
I am also inputting a list for R0,cR1 and cR2.

Thank you for any help

**Comment by zhuminjie** [comment]
can you show the line of code you called to generate the error

**Comment by vacalderon** [comment]
I solved it I wasn't using a float
