### ISSUE TITLE
Explicit Difference integrator does not work

### ISSUE THREAD

**Issue by ngsanchez** [zhuminjie/OpenSeesPyDoc#67]
I'm trying to use the Explicit Difference transient integrator, but when I write the following lines:

import openseespy.opensees as ops
ops.integrator('ExplicitDifference')

I have the following message:

WARNING unknown integrator type ExplicitDifference

Thanks in advance.
Note: all the other integrator works well.

**Comment by zhuminjie** [comment]
The explicit difference is not yet in the integrator. I will add it in the next version. Thank yoU!

**Comment by zhuminjie** [comment]
New version is uploaded.
