### ISSUE TITLE
nDmaterial only accepts single precision float for 'ref_shear_modul' input

### ISSUE THREAD

**Issue by millen1m** [zhuminjie/OpenSeesPyDoc#68]
I think the nDMaterial 'ref_shear_modul' parameter does not accept normal python float unless it has less than 32-bit precision. This means that if the number is computed in python and produces an irrational number, it wont work. The error message does not show anything related to the problem in the input.

See example file attached.

Suggestion would be to allow ref_shear_modul to be input as a c_double?
[double_precision_error.txt](https://github.com/zhuminjie/OpenSeesPyDoc/files/3249949/double_precision_error.txt)

**Comment by zhuminjie** [comment]
Thanks! I will work on it later.

**Comment by zhuminjie** [comment]
Internally, PyFloat_AS_DOUBLE is used to process float, it should handle both double and float. 

I tried the script. If you use 'a' in the first nDMaterial command, it doesn't have the error.

**Comment by millen1m** [comment]
Thanks for looking at this.

Ok, strange. Did you try with the line ‘a = ctypes.c_float(a).value’ commented out? As with out this line the script was failing.

**Comment by zhuminjie** [comment]
Yes, with a = ctypes.c_double(a).value and a used in the first command

**Comment by millen1m** [comment]
So if you delete that line does it fail? It fails on my Windows machine.

**Comment by zhuminjie** [comment]
It will fail if 'a' used in the second command, but not fail in the first command.

**Comment by millen1m** [comment]
I don’t understand, does it fail when you delete the line? On my machine if I pass a ctype.c_double that has precision of more than 16, e.g. a = 106250.00000000001, then it fails, however, if I pass in a = 106250.00000000000

This is a problem because if you divide a float in python then you often end up with these numbers. This can be solved if you force all floats in python to be ctype.c_float, however, I was wondering if this could be handled in the C++ headers.

**Comment by zhuminjie** [comment]
Here is the script I ran without problem. Can you try if you can run it?
[double_precision_error.txt](https://github.com/zhuminjie/OpenSeesPyDoc/files/3262720/double_precision_error.txt)

**Comment by millen1m** [comment]
Yes, that runs. Strange. So why does it fail when it is input into the first nDMaterial?

**Comment by zhuminjie** [comment]
I have no idea at this time.It's strange that all float inputs are processed using the same python api PyFloat_AS_DOUBLE internally. Only this variable has the problem. I believe other variables if you set to double are ok.

**Comment by millen1m** [comment]
Cheers.
