### ISSUE TITLE
NameError: name 'op' is not defined

### ISSUE THREAD

**Issue by antonsurv** [zhuminjie/OpenSeesPyDoc#69]
Dear Mr. Zhu
I run `pile.py` example 11.4.1. Laterally-Loaded Pile Foundation
but name `op.wipe()` and other is not defined

```
[anton@anton-pc]$ python pile_rev.py
Traceback (most recent call last):
  File "pile.py", line 413, in <module>
    op.wipe()
NameError: name 'op' is not defined
```

**Comment by zhuminjie** [comment]
You can contact the author the script, whose email is on the page

**Comment by antonsurv** [comment]
I add 
import openseespy.opensees as op # in line 412

Thank you, Sir
