### ISSUE TITLE
logFile message turning off

### ISSUE THREAD

**Issue by s-m-amin-ghasemi** [zhuminjie/OpenSeesPyDoc#70]
Hello
Thank you for your attention Dr. Zhu

In new version we have logfile command and one new thing here is 'noEcho'.
I can not use it to have not messages and warnings as a result.
After executing I had logfile.out in directory that show me it is working in some how but it is continuing to display warnings and messages in IDLE and also in jupyter.

**Comment by codeaadd** [comment]
Thank you for pointing to that. I have fixed it and it will be in the next version.

**Comment by zhuminjie** [comment]
Thank you for pointing to that. I have fixed it and it will be in the next version.

**Comment by s-m-amin-ghasemi** [comment]
Hello
Your welcome, its my pleasure to be in contact with you.

سید محمد امین قاسمی
با تشکر
Yours sincerely
Seyed Mohammad Amin Ghasemi

________________________________
