### ISSUE TITLE
a problem in “ConfinedConcrete01”

### ISSUE THREAD

**Issue by MojtabaSedighi** [zhuminjie/OpenSeesPyDoc#72]
We have some problem with the usage of “ConfinedConcrete01” material property in nonlinear dynamic analysis. We used that material for fiber in the core of concrete section as follow:

op.uniaxialMaterial('ConfinedConcrete01', 101, R, -25.0, 25000.0, -epscu, -0.0035, -nu, 0.15, 700.0, 700.0, 10.0, 100.0, 340.0, 200000.0, 0.0, 1000.0, 25.0)

first following massage generated in the OPENSEES and analysis continue:

msg: ConfinedConceret01 unaxial material - Written by M.D'Amato, University of Basilicata, Italy 2009

msg: 25 1 25000 0 0 0.00190513 25 0.00292311 21.5698 2.48893 11.25 1.1593728984.4

then static linear and nonlinear analysis were conducted without any problem. In the dynamic analysis, following massage generated and analysis terminated.

msg: FEM_ObjectBrokerAllClasses::getNewUniaxialMaterial -  - no UniaxialMaterial type exists for class tag 0

I wondered, could you please help us to resolved this problem.

Sincerely yours

**Comment by zhuminjie** [comment]
It's been fixed.
