### ISSUE TITLE
Job status: FAILED

### ISSUE THREAD

**Issue by warlockwarchief** [zhuminjie/OpenSeesPyDoc#74]
Dear Dr. Zhu
At first, Thanks for your modern platform, OpenSeesPy
Then, I'm a beginner and I want to run example 12.1.1 (Elastic Truss Analysis)
When I submitted the code, I see this message:

Job status: FAILED
Transitioning from status CLEANING_UP to FAILED in phase ARCHIVING.

It's my honor to have your guidance..

**Comment by warlockwarchief** [comment]
![Run OpenSeesPy](https://user-images.githubusercontent.com/53867979/62693051-fb39da00-b9e6-11e9-8959-8bd0a320a01d.png)
Dear Dr. Zhu

I couldn't understand how to handle with "line 2"
I just copy the 12.1.1 code in the Jupyter and run with Paraview but the job failed and I don't know why!

**Comment by zhuminjie** [comment]
These line highlights are not needed now. I have removed them. Don't worry about them.

What do you mean you submitted a job? Where and what job are you submitting?

**Comment by warlockwarchief** [comment]
Dear Dr. Zhu
Thanks for your attention, I don't know how to run OpenSeesPy codes!
Is it via Jupyter notebook and the Run button?
![jupyter](https://user-images.githubusercontent.com/53867979/62727272-58a54980-ba2e-11e9-94ec-13d031ccacda.PNG)
 if {answer == true} {
I was wondering to know that :
This calculation done with the High Performance Computers?
Is it a good way to run huge IDAs?
}

**Comment by zhuminjie** [comment]
Yes, you can run within the notebook.

HPC is not automatic. You have to run scripts with MPI and carefully write your scripts.

**Comment by warlockwarchief** [comment]
Dear Dr. Zhu
According to section "1.2.2. Paraview in DesignSafe"
I download  code via 12.1.1. Elastic Truss Analysis 
and use your guidance
Why this error happend?
Thanks in advance..
![ParaviewF](https://user-images.githubusercontent.com/53867979/62728012-fa796600-ba2f-11e9-9032-dd1d16ccdc65.png)

**Comment by zhuminjie** [comment]
You may want to contact designsafe team for the error.

**Comment by warlockwarchief** [comment]
Thanks for your guidance..
I hope to run OpenSeesPy correctly!
