### ISSUE TITLE
Problem with enviroment in jupyterlab

### ISSUE THREAD

**Issue by Zawarud** [zhuminjie/OpenSeesPyDoc#75]
I'm using an enviroment for use cadquery in jupyterlab 1.0( the python version is 3.6.8) for automatic building RC frame from opensees data. i install into enviroment openseespy with : 
`pip install openseespy`
then i import module with : 
`from openseespy.opensees import *`
But give me this error : 

> ~\Anaconda3\envs\cq-jl\lib\site-packages\openseespy\opensees\__init__.py in <module>
     21     if sys.version_info[1] == 6:
     22 
---> 23         from openseespy.opensees.winpy36.opensees import *
     24 
     25     else:

ImportError: DLL load failed: Impossibile trovare il modulo specificato.

how to solve this?
in the base enviroment(python 3.7) work all fine.

**Comment by Zawarud** [comment]
How I solve this :
1) uninstall all(anaconda include).
2) install the 2018 anaconda3
3) update jupyterlab to 1.0
4) create enviroment for cadquery
5) install with pip in this enviroment the openseespy module

**Comment by zhuminjie** [comment]
Thank you for posting how you solve it!
