### ISSUE TITLE
HHT Input Parameters

### ISSUE THREAD

**Issue by pavan1388** [zhuminjie/OpenSeesPyDoc#76]
Hello Dr. Zhu,

I tried to input all the parameters for HHT integrator as suggested in the OpenSeespy website (https://openseespydoc.readthedocs.io/en/latest/src/hht.html). When I run the analysis an error message pops out saying the input parameters are not correct (when I provide the form parameter). When I looked in the OpenSees website (http://opensees.berkeley.edu/wiki/index.php/Hilber-Hughes-Taylor_Method), there is no such form variable there, maybe that is the reason. So, can you please look into this.

Thank you,
Pavan Chigullapally.

**Comment by zhuminjie** [comment]
The option '-form' is already removed. Is that you talk about?

**Comment by pavan1388** [comment]
Yes. I can see that in the documentation for HHT still so, I was not sure.  All good if it is gone! Thank you.
