### ISSUE TITLE
Weird Node Acceleration response

### ISSUE THREAD

**Issue by pavan1388** [zhuminjie/OpenSeesPyDoc#77]
Hello Dr. Zhu, 

Currently, I am trying to run a single pile-column model with py curves and fiber sections in OpenSeespy. The model converges fine, but when I am trying to get nodal acceleration values at any node on the pile-column, I am getting weird results. I have attached an image of the output acceleration and displacement time history below (my guess is, it is having some kind of an oscillation problem). 

I had a similar problem when I was using elastic elements for the analysis, but I was able to eliminate the thick acceleration lines at the end of the time history by modifying the alpha value in HHT integrator. I tried to do the same for piles with fiber sections, although I was able to eliminate the thick bands at the end, the results don't make sense. The displacement time histories are fine before and after (they remained same), but I am getting very high acceleration peaks randomly (I am using NodeAccl command to get my accelerations at nodes). 

It would be great if you can help me out. Thank you in advance.

Thick acceleration bands at the end of time series
![Opensees Acceleration problem](https://user-images.githubusercontent.com/44953871/63331994-e5cf9300-c38a-11e9-8761-191cac23a6f9.png)

Acceleration bands eliminated for elastic pile-column after modifying alpha value in HHT integrator
![image](https://user-images.githubusercontent.com/44953871/63392941-eb6dbd00-c40c-11e9-9ca0-9f5461000def.png)

Random Acceleration peaks after modifying alpha value in HHT integrator
![image](https://user-images.githubusercontent.com/44953871/63393566-b7e06200-c40f-11e9-8ade-2f9be7f10b70.png)

**Comment by zhuminjie** [comment]
Did you try newmark integrator? How do you call nodeAccel?

**Comment by pavan1388** [comment]
Yes, I tried the Newmark method, and the results look the same. I collected Node accelerations using op.nodeAccel(node_number) and tried to collect it at each time step and plotted against time. I did not use the recorder commands to collect the accelerations.

**Comment by zhuminjie** [comment]
Did you set nodal mass?

**Comment by pavan1388** [comment]
Yes, I have nodal mass at the location I am checking the accelerations.

I have changed the analysis from multi support to uniform excitation, and it works fine. I am not sure about the reason still.

**Comment by pavan1388** [comment]
I am trying to have lumped mass, so I cannot have mass at all nodes. As I mentioned before, I moved from multi-support excitation to uniform excitation and I do not have this issue anymore. Thank you for looking into this issue.
