### ISSUE TITLE
Problem in a 3D reinforced frame for a static analysis

### ISSUE THREAD

**Issue by Zawarud** [zhuminjie/OpenSeesPyDoc#79]
I have not found an 3d example in the [SITE](https://openseespydoc.readthedocs.io/).
For reference I use tcl example in opensees site.
The parameters for integration are : 

`step = 10 ; nstep = 1/step

system('BandGen') 

constraints('Transformation') `

numberer('RCM') ;

test('NormDispIncr', 1.0e-3, 1000, 5)

algorithm('Newton') ;

integrator('LoadControl', nstep) ;

analysis('Static')

analyze(step)
`
#This is  the error.
`WARNING - ForceBeamColumn3d::update - failed to get compatible element forces & deformations for element: 2(dW: << 63.5061, dW0: 2.23221)

WARNING - ForceBeamColumn3d::update - failed to get compatible element forces & deformations for element: 3(dW: << 7.275, dW0: 2.3812)

WARNING - ForceBeamColumn3d::update - failed to get compatible element forces & deformations for element: 4(dW: << 593.154, dW0: 1.86277)

WARNING - ForceBeamColumn3d::update - failed to get compatible element forces & deformations for element: 6(dW: << 47.0202, dW0: 0.0206937)

WARNING - ForceBeamColumn3d::update - failed to get compatible element forces & deformations for element: 7(dW: << 103.945, dW0: 1.92501)

WARNING - ForceBeamColumn3d::update - failed to get compatible element forces & deformations for element: 8(dW: << 115.86, dW0: 1.28802)

WARNING - ForceBeamColumn3d::update - failed to get compatible element forces & deformations for element: 7(dW: << 2265.09, dW0: 2.52126e+06)

WARNING - ForceBeamColumn3d::update - failed to get compatible element forces & deformations for element: 8(dW: << 115.859, dW0: -3.37799e+07)

Domain::update - domain failed in update

LoadControl::update - model failed to update for new dU

WARNING NewtonRaphson::solveCurrentStep() -the Integrator failed in update()

StaticAnalysis::analyze() - the Algorithm failed at iteration: 1 with domain at load factor 0.2

OpenSees > analyze failed, returned: -3 error flag`

How to solve this?
p.s. The order of eleload in 3D **local system** is Wx, Wy, Wz ? you check this ?

**Comment by zhuminjie** [comment]
the order is wy, wz, wx

https://openseespydoc.readthedocs.io/en/latest/src/eleload.html

**Comment by Zawarud** [comment]
So for the beam the load due to the floor is in the Wz direction (as in the image) ?
http://opensees.berkeley.edu/wiki/images/5/5e/ElementOrientation.png

**Comment by Zawarud** [comment]
# I do this example :
![alt text](https://i.ibb.co/x6pnYzC/text11701-7-4-0-3.png)
