### ISSUE TITLE
Issue with limit state material

### ISSUE THREAD

**Issue by adhikarig** [zhuminjie/OpenSeesPyDoc#80]
Hi all,

I am modelling a non-ductile reinforced concrete column using the limit state material. I could not find any syntax for limit curves, namely, shear and axial limit curves, in Openseespy document. I, therefore, used the tcl version syntax.  [Limit_Curve](http://opensees.berkeley.edu/wiki/index.php/Limit_Curve) 

I used beta = 0.0, as recommended.  I also tried other beta values.  Below is a snippet of my code.

_shearTag, shearCurveType = 32, 2
v1, v2, v3 = 33.0*u.kN, 65.0*u.kN, 98.0*u.kN
tmpK = 444000.0*u.kN/u.metre
d1, d2, d3 = v1/tmpK, v2/tmpK, v3/tmpK
pinchX, pinchY, damage1, damage2 = 0.50, 0.40, 0.0, 0.0
beta = 0.0
ops.uniaxialMaterial('LimitState', shearTag, v1, d1, v2, d2, v3, d3, -v1, -d1,
                     -v2, -d2, -v3, -d3, pinchX, pinchY, damage1, damage2, beta,
                     shearLimitTag, shearCurveType)_

But I always get the warning as below.
_WARNING invalid beta
Traceback (most recent call last):
  File "checkElements.py", line 157, in <module>
    shearLimitTag, shearCurveType)
SystemError: <built-in function uniaxialMaterial> returned NULL without setting an error_

When I looked into the source code, I found
_double beta = 0.0;
    if (argc == 20 || argc == 16 || argc >= 22 ) {
	if (OPS_GetDoubleInput(&numdata,&beta) < 0) {
	    opserr << "WARNING invalid beta\n";
	    return 0;
	}
    }_

Any help is highly appreciated. 

cheers,
Gopal

**Comment by zhuminjie** [comment]
There is a bug. It will be fixed in the next version. Thank you!
