### ISSUE TITLE
python list not working with recorder command

### ISSUE THREAD

**Issue by adhikarig** [zhuminjie/OpenSeesPyDoc#81]
Hi all,

I was trying to use a node list to get node displacements.  Below is a snippet of my code.

_iNode = [1,2,3]
ops.recorder('Node', '-file', nodeDisp, '-time', '-node', iNode, 
                 '-closeOnWrite','-dof', 1, 2, 3, 4, 5, 6, 'disp')_

I got output of all node displacements instead of specified nodes 1, 2, and 3. 

I don't need displacements of all nodes.  any smarter way to get specific node displacements.

I am aware of nodeDisp command. 

thanks,
gopal

**Comment by zhuminjie** [comment]
You have to use list with a star before it

ops.recorder('Node', '-file', nodeDisp, '-time', '-node', *iNode,
'-closeOnWrite','-dof', 1, 2, 3, 4, 5, 6, 'disp')

**Comment by adhikarig** [comment]
Thanks Minjie
