### ISSUE TITLE
Save Node Disp in Transient Analysis

### ISSUE THREAD

**Issue by Zawarud** [zhuminjie/OpenSeesPyDoc#82]
There is a method for save in a Arrray the Node Disp  without record in a file( recorder command) ?

**Comment by Zawarud** [comment]
I mean, save node displacement each step (step =Tot_time/dt ) of Analysis without write file to hard-disk. (for more fast computing) ?

**Comment by zhuminjie** [comment]
If you don't save to hard drive, where do you save them?

**Comment by Zawarud** [comment]
in a Array like NodeDisp

**Comment by anurag-upadhay** [comment]
Follow example 12.2.2 or 12.1.7 to. You have to initiate either an empty array and change values at each step, or initiate an array with (0,0) value and add values to it at each step.

**Comment by Zawarud** [comment]
> 
> 
> Follow example 12.2.2 or 12.1.7 to. You have to either initiate an empty array and change values at each step, or initiate an array with (0,0) value and add values to it at each step.

I dont know why nodeDisp dont work (give me all zeros value). I'm using the example.
```
time = [tCurrent] ; u3 = [0.0] ; # REGISTRAZIONE PER COSTRUIRE IL GRAFICO
print('step : ',step,' | dt : ',dt,' | TOTALE :',tFinal,'sec')
while ok == 0 and tCurrent < tFinal:
    ok = analyze(1, dt)
    u3.append(nodeDisp(NTop,1)) ; time.append(tCurrent) ; # REGISTRAZIONE STEP PER STEP
    print(nodeDisp(NTop))
    tCurrent = getTime()
```

**Comment by zhuminjie** [comment]
Try to change line 20 to

exec(open('RCFrameGravity.py').read())

**Comment by Zawarud** [comment]
In 3D dimension the mass and nodal gravity load must be written like this, in the transient analysis?  : 
```
m = P/g ; # nodal mass
Q = -1.1 ; # Nodal Gravity Load
#            TAG dx dy dz   rx   ry   rz 
mass( nodeTag, *[ m, m, m, 0.0, 0.0, 0.0])
load( nodeTag, *[ 0.0, Q, 0.0, 0.0, 0.0, 0.0])
```
is right?

**Comment by zhuminjie** [comment]
I think so

**Comment by Zawarud** [comment]
I solve. The order for analysis time history is : 
1) model
2) wipeAnalysis()
3) Analisys Parameter (transient)
4) RAYLEIGH
5) Add Earthquake( timeSeries, pattern )
6) use Command analyze
