### ISSUE TITLE
Huge Number of Nodes

### ISSUE THREAD

**Issue by peterfakhry** [zhuminjie/OpenSeesPyDoc#83]
Hello there
i am solving a 20-story nonlinear benchmark problem. the number of nodes 138, is there any easier way to use python for loops than assigning each node with op.node(ID,x,y) because also this takes a large space of my code
thank you

**Comment by Zawarud** [comment]
## Like this
l = 5000.0 ;# beam length
h = 3000.0 ;# column heigh
x = 2 ; # Bays X
z = 2 ; # Bays Z
y = 4 ; # Stories 
#------------------------------
nodi = np.array([[99,0.0,0.0,0.0]]) ; #  array node
n = 0
for cy in range(0,(y+1),1) :
    for cz in range(0,(z+1),1) :
        for cx in range(0,(x+1),1) :
                n = n+1
                node(n,cx*l,cy*h,cz*l) ; 
                nodi = np.append(nodi,[[n,cx*l,cy*h,cz*l]], axis = 0)
nodi = np.delete(nodi, 0, 0)    # Del 1° row

**Comment by peterfakhry** [comment]
thanks a lot for your reply, i adjusted your code as this but got the following error
`import numpy as np
import openseespy.opensees as op
l = 5000.0 # beam length
h = 3000.0 # column heigh
x = 2  # Bays X
z = 2  # Bays Z
y = 4  # Stories 
#------------------------------
nodi = np.array([[99,0.0,0.0,0.0]])  #  array node
n = 0
for cy in range(0,(y+1),1) :
    for cz in range(0,(z+1),1) :
        for cx in range(0,(x+1),1) :
                n = n+1
                op.node(n,cx*l,cy*h,cz*l) 
                nodi = np.append(nodi,[n,cx*l,cy*h,cz*l], axis = 0)
nodi = np.delete(nodi, 0, 0)    # Del 1° row
`
OpenSeesError: See stderr output

**Comment by Zawarud** [comment]
## Like this
```
import numpy as np
from openseespy.opensees import *
wipe()
model('basic', '-ndm', 3, '-ndf', 6) ; # 3D VERSION

l = 5000.0 ;# beam length
h = 3000.0 ;# column heigh
x = 2 ; # Bays X
z = 2 ; # Bays Z
y = 4 ; # Stories 
#------------------------------
nodi = np.array([[99,0.0,0.0,0.0]]) ; #  array node
n = 0
for cy in range(0,(y+1),1) :
    for cz in range(0,(z+1),1) :
        for cx in range(0,(x+1),1) :
                n = n+1
                node(n,cx*l,cy*h,cz*l) ; 
                nodi = np.append(nodi,[[n,cx*l,cy*h,cz*l]], axis = 0)
nodi = np.delete(nodi, 0, 0)    # Del 1° row
```
Pay attension with the indentations in the code.

**Comment by peterfakhry** [comment]
thank you sir, yes, i looped the function itself
