### ISSUE TITLE
Print flag ignored in command test('NormDispIncr', tol, iter, pFlag=0, nType=2)

### ISSUE THREAD

**Issue by pp4** [zhuminjie/OpenSeesPyDoc#85]
Hi Minjie, 
Fantastic work with OpenSeesPy. 
Maybe you can replicate this issue: the print flag `pFlag `in the command `test('NormDispIncr', tol, iter, pFlag=0, nType=2)` seems to be ignored. 
I'm using OpenSeesPy 0.5.3 in Anaconda 2019.07 in Windows 10.
Many thanks and 
all the best,
Pedro

**Comment by zhuminjie** [comment]
How did you call it

**Comment by pp4** [comment]
I call it when specifying the analysis' options (see below).
I noticed this behaviour after updating from OpenSeesPy 0.1.1 to 0.5.3 and, simultaneously, from Anaconda 2018.12 in Windows 7 to Anaconda 2019.07 in Windows 10.

```
# ...

## Analysis options

# Other options ...

# Convergence test
testType = 'NormDispIncr'    # test type
tol      = 1e-5              # tolerance criteria used to check for convergence.
maxIter  = 20                # max number of iterations to check
pFlag    = 0                 # print flag (optional)
op.test(testType,
        tol, 
        maxIter,
        pFlag)

## Create analysis
analysisType = 'Static'    # char string identifying type of analysis
op.analysis(analysisType)

## Run analysis
for inc in range(numIncr):
    op.analyze(1)
    # extract and save output data ...

```

**Comment by pp4** [comment]
`pFlag=1` seems to be working as expected, i.e. it prints information on norms at each time step.
But as you can see below, `pFlag=0` is also printing information.
Could it be that the output printed with `pFlag=0` comes from the `analyze()` command, since it is the same last 5 lines of the output with `pFlag=1`?

I'm sorry if my questions are very basic..
It's just that version 0.1.1 was less verbose and I was able to read my own output messages during execution and now they are lost between thousands of other messages.

Output with `pFlag=0`:

> WARNING: CTestNormDispIncr::test() - failed to converge 
> after: 20 iterations  current Norm: 4.36004 (max: 1e-05, Norm deltaR: 78113.5)
> ModifiedNewton::solveCurrentStep() -the ConvergenceTest object failed in test()
> StaticAnalysis::analyze() - the Algorithm failed at iteration: 0 with domain at load factor 1321.56
> OpenSees > analyze failed, returned: -3 error flag

Output with `pFlag=1`:

> CTestNormDispIncr::test() - iteration: 1 current Norm: 9.31628e-05 (max: 1e-05, Norm deltaR: 1561.47)
> CTestNormDispIncr::test() - iteration: 2 current Norm: 3.16951e-05 (max: 1e-05, Norm deltaR: 1562.3)
> CTestNormDispIncr::test() - iteration: 3 current Norm: 9.14964e-05 (max: 1e-05, Norm deltaR: 1601.06)
> CTestNormDispIncr::test() - iteration: 4 current Norm: 0.000689981 (max: 1e-05, Norm deltaR: 3027.28)
> CTestNormDispIncr::test() - iteration: 5 current Norm: 0.00621388 (max: 1e-05, Norm deltaR: 19651.4)
> CTestNormDispIncr::test() - iteration: 6 current Norm: 0.567273 (max: 1e-05, Norm deltaR: 102566)
> CTestNormDispIncr::test() - iteration: 7 current Norm: 3.18737 (max: 1e-05, Norm deltaR: 114716)
> CTestNormDispIncr::test() - iteration: 8 current Norm: 3.25383 (max: 1e-05, Norm deltaR: 79948.8)
> CTestNormDispIncr::test() - iteration: 9 current Norm: 4.33387 (max: 1e-05, Norm deltaR: 83452.6)
> CTestNormDispIncr::test() - iteration: 10 current Norm: 5.71162 (max: 1e-05, Norm deltaR: 90797.5)
> CTestNormDispIncr::test() - iteration: 11 current Norm: 4.80432 (max: 1e-05, Norm deltaR: 78378.8)
> CTestNormDispIncr::test() - iteration: 12 current Norm: 4.43583 (max: 1e-05, Norm deltaR: 78180)
> CTestNormDispIncr::test() - iteration: 13 current Norm: 4.36685 (max: 1e-05, Norm deltaR: 78337.1)
> CTestNormDispIncr::test() - iteration: 14 current Norm: 4.35869 (max: 1e-05, Norm deltaR: 78124.7)
> CTestNormDispIncr::test() - iteration: 15 current Norm: 4.3701 (max: 1e-05, Norm deltaR: 78326.5)
> CTestNormDispIncr::test() - iteration: 16 current Norm: 4.35896 (max: 1e-05, Norm deltaR: 78113.5)
> CTestNormDispIncr::test() - iteration: 17 current Norm: 4.36932 (max: 1e-05, Norm deltaR: 78312.3)
> CTestNormDispIncr::test() - iteration: 18 current Norm: 4.35952 (max: 1e-05, Norm deltaR: 78111.4)
> CTestNormDispIncr::test() - iteration: 19 current Norm: 4.36865 (max: 1e-05, Norm deltaR: 78298.2)
> CTestNormDispIncr::test() - iteration: 20 current Norm: 4.36004 (max: 1e-05, Norm deltaR: 78113.5)
> **WARNING: CTestNormDispIncr::test() - failed to converge 
> after: 20 iterations  current Norm: 4.36004 (max: 1e-05, Norm deltaR: 78113.5)
> ModifiedNewton::solveCurrentStep() -the ConvergenceTest object failed in test()
> StaticAnalysis::analyze() - the Algorithm failed at iteration: 0 with domain at load factor 1321.56
> OpenSees > analyze failed, returned: -3 error flag**

**Comment by zhuminjie** [comment]
Yes, the last 5 lines are from analyze(). Since the analysis failed, it prints some errors messages. If you want less verbose message, just set pFlag=0. In both versions, the error messages for a failed analysis will be printed

**Comment by pp4** [comment]
Many thanks, Minjie. 
That closes this non-issue.. 

(in any case, it would be nice if  `analyze()` could take a keyword argument like `pFlag=0`)
