### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by ezrapogoda** [zhuminjie/OpenSeesPyDoc#89]
Dear Dr. Zhu,

I tried to run the elastic truss example but I keep getting the same error as shown in the attached screenshot. Any help would be greatly appreciated as I can't figure out the problem!
I tried to use the command 'import openseespy.opensees as ops' but that gave me the same error.
Additionally, I have tried to use python 3.7 and 3.6 which, unfortunately, was unsuccessful too.

I am using an anaconda virtual environment in vs code.
Thanks a lot!
Regard,
Ezra
![Annotation 2019-10-12 140520](https://user-images.githubusercontent.com/56478344/66702003-9b1f2700-ecfa-11e9-8205-6300a3b46e7a.png)

**Comment by zhuminjie** [comment]
This kind of error usualy is due to  that you install openseespy with one python and call it in another python.

**Comment by vjagodnik** [comment]
I think I have a similar issue.
I keep getting error "Import error:" and "Library not loaded:"

Do you think that the simplest way would be to remove Python (Anaconda) completely, reinstall it with python version 3.6, and then install Opensees?

With kind regards

**Comment by zhuminjie** [comment]
For now, only the latest Anaconda is supported

https://www.anaconda.com/distribution/

**Comment by vjagodnik** [comment]
Having issues with newest distribution and older one (python 3.6).
But I think i'm doing something wrong, regarding to installation. Will try again from beginning.

**Comment by mhscott** [comment]
Closing.
