### ISSUE TITLE
(Windows) ParaView Error - Eigen Analysis

### ISSUE THREAD

**Issue by marcozord** [zhuminjie/OpenSeesPyDoc#9]
I tried to perform eigen analysis and record the shape of the eigen modes, but the pvd recorder
with 'eigen' doesn'work.

**Comment by zhuminjie** [comment]
I will look into it. Thank you for reporting the problem

**Comment by zhuminjie** [comment]
I have checked it. It works for me. see below

![image](https://user-images.githubusercontent.com/6202967/45637713-0c40cc00-ba60-11e8-96f1-ab38625b048f.png)

It is an eigen value analysis for a frame structure. Three eigen vectors are exported to pvd recorder. Let me know what specific problem you had.
