### ISSUE TITLE
'flatSliderBearing' elements - input format

### ISSUE THREAD

**Issue by JonasWydler** [zhuminjie/OpenSeesPyDoc#91]
Hello,

I'm having trouble using flatSliderBearing elements. I'm not sure if the input format described in the user documentation is correct, since the syntax after "matTag" is simply not correct:
 element('flatSliderBearing', eleTag, *eleNodes, frnMdlTag, kInit, '-P', matTag, '-Mz', matTag[, '-orient', x1, x2, x3, y1, y2, y3][, '-shearDist', sDratio][, '-doRayleigh'][, '-mass', m][, '-iter', maxIter, tol])

I tried:
op.element(eleType, eleTag, *eleNodes, frnMdlTag, kInit, '-P', matTagP, '-Mz', matTagM, '-orient', [x1,x2,x3,y1,y2,y3])

which gives me "msg: WARNING: insufficient arguments after -orient"

I also tried:
op.element(eleType, eleTag, *eleNodes, frnMdlTag, kInit, '-P', matTagP, '-Mz', matTagM, ['-orient', x1,x2,x3,y1,y2,y3])

which leads to "Kernel died, restarting"

Could you help me with the correct format of the orientations?

Thank you very much and all the best,
Jonas

**Comment by zhuminjie** [comment]
You can try 

orient = [x1,x2,x3,y1,y2,y3]
op.element(eleType, eleTag, *eleNodes, frnMdlTag, kInit, '-P', matTagP, '-Mz', matTagM, '-orient', *orient)

**Comment by JonasWydler** [comment]
Thanks, it works!
