### ISSUE TITLE
There are a command for make a continuous beams( Gerber )

### ISSUE THREAD

**Issue by Zawarud** [zhuminjie/OpenSeesPyDoc#93]
How to set the central support for a continuous beams ?
![immagine](https://user-images.githubusercontent.com/53933533/67408004-9ee36100-f5b8-11e9-8b38-ea93139f3f2e.png)
In particular Fix Disp , but transfers rotations between the two elements .

**Comment by zhuminjie** [comment]
That's a roller support. You can add a node and fix only y direction as

ops.fix(nd, 0, 1, 0)
