### ISSUE TITLE
Correct syntax for stress/strain output for a quad element

### ISSUE THREAD

**Issue by adhikarig** [zhuminjie/OpenSeesPyDoc#94]
Hi all,

I am modelling an 1D soil column for site response analysis.  I used following syntax for strain output at the Gauss points of  Quad elements. However, I am getting a blank text file.

ops.recorder('Element', '-file', 'Gstrain2.txt', '-time', '-eleRange', 1, numEles,  'material', 2, 'strain')

Any help is highly appreciated.

cheers,
Gopal

**Comment by geosharma** [comment]
I am trying to recreate all the Geotech examples as a way to learn OpenSees and program in Python. I am modeling the same thing and I have it setup as given below. The recorder works but not the simulation. I thought I had it working once and was concentrating on creating response spectra and finally when I had the response spectra working, I find my simulation does not work. Anyway if you want to see what I have done I have a gitlab repository https://gitlab.com/geosharma. I also have 1D consolidation in that repo.
ops.recorder(
            "Element",
            "-file", fout,
            "-time",
            "-dT", motionDT,
            "-eleRange", 1, number_of_elements,
            "material", 2,
            "strain",
        )
I think you are missing the "-dT", motionDT part. The 'fout' is the path to the output file just so there is no confusion.

**Comment by mgrubisic** [comment]
In fact, everything in your example is well stated, only the material tag should be enclosed in quotation marks, as a string.

`ops.recorder(`
`"Element",`
`"-file", "Gstrain2.txt",`
`"-time",`
`"-dT", motionDT,` ==> As far as I know the output in the recorder will be the same with or without defining "-dT", try it for yourself
`"-eleRange", 1, numEles,`
`"material", "2", "strain",` ==> The quotation marks must be added here
`)`

**Comment by zhuminjie** [comment]
Good reminder, thanks!
