### ISSUE TITLE
Explicit Solver &  High Strain Rate Phenomena

### ISSUE THREAD

**Issue by warlockwarchief** [zhuminjie/OpenSeesPyDoc#95]
Dear Dr. Zhu

At first, Thanks again for your precious and modern framework, OpenSeesPy
Then, I have one question:
As you are well aware, For high strain dependent loads like impact load we must use explicit solver; OpenSees is not a good choice for researchers and they prefer commercial finite element software such as :LS-DYNA, Ansys, Abaqus, etc. Although this move from macro-finite element to micro-finite element programs  costs computationally.

I was wondering to know if your modern approach formulation, "Particle Finite Element Method" which  is implemented in OpenSeesPy could use for impact and other high-strain rate phenomena with explicit solver?How?
(Two common approach for these problems are Arbitrary Eulerian Lagrangian (ALE) and Smooth Particle Hydrodynamics (SPH) methods)

Sincerely

**Comment by zhuminjie** [comment]
PFEM is for FSI analysis, including impact and large strain and large displacement in the fluid domain

**Comment by warlockwarchief** [comment]
Dear Dr Zhu,
Thanks for your reply, Does OenSeesPy support **Explicit** Solver?How?

**Comment by zhuminjie** [comment]
What do you mean by explicit solver?

**Comment by warlockwarchief** [comment]
Dear Dr. Zhu,
As you are well aware, Dynamic analysis can be done via the explicit solver or the implicit solver. In nonlinear implicit analysis, solution of each step requires a series of trial solutions (iterations) to establish equilibrium within a certain tolerance. In explicit analysis, no iteration is required as the nodal accelerations are solved directly.
**For the case of high strain rate physical phenomena like impact and blast we must use explicit analysis**. This is the reason  nonlinear FEA programs like LS-DYNA and Abaqus have the option of explicit analysis. Although the main application of OpenSees is seismic field but I am interested in modelling high strain rate physical phenomena in your OpenSeesPy
Thanks in advance..

**Comment by zhuminjie** [comment]
OpenSees has explicit solver, but the explicit solver requires very small time steps and the error is cummulative.

**Comment by warlockwarchief** [comment]
Good,Thanks for your reply.
Does your OpenSeesPy support explicit solver?

**Comment by zhuminjie** [comment]
Yes, but it depends on which elements you want to use

**Comment by warlockwarchief** [comment]
Thanks a lot. My last question:
Is there any reference to find out which elements support explicit solver in OpenSees and OpenSeesPy?

**Comment by zhuminjie** [comment]
You can take a look at the element document

**Comment by warlockwarchief** [comment]
Thanks again for your fruitful support.
