### ISSUE TITLE
Newton method in site response analysis not converging in openseespy while converging in opensees

### ISSUE THREAD

**Issue by geosharma** [zhuminjie/OpenSeesPyDoc#97]
Since this is my first post here, I would first of all like to thank Minjie Zhu for OpenSeesPy, I would not be using OpenSees without it. 

I was trying to solve the total stress site response analysis using OpenSeesPy by converting the steps given in the [freeFieldSingle.tcl](https://opensees.berkeley.edu/wiki/index.php/Site_Response_Analysis_of_a_Layered_Soil_Column_(Total_Stress_Analysis)) file to its Python equivalent. It is not exactly a line to line conversion but I think the model and the analysis are the same. The ``.tcl`` file in OpenSees converges with  ``ops.test("NormDispIncr", 1.0e-3, 15, 5)  ops.algorithm("Newton")`` but my ``.py`` does not converge in OpenSeesPy. I was finally able to solve the problem with [otaithleigh](https://github.com/otaithleigh) help by changing ``ops.test("NormDispIncr", 1.0e-5, 50, 5)  ops.algorithm("KrylovNewton")``.  My python script can be found at the GitLab [repository](https://gitlab.com/geosharma/opensees-examples/tree/master/geotech/site_response_totalstress). 

Since my analysis using ``.py`` converges using KrylovNewton method and gives the same acceleration, velocity and displacement time histories as the ``freeFieldSingle.tcl`` file, I was wondering if  OpenSees and OpenSeesPy are complied differently which may result in this issue. I am using the 3.0.3 version of OpenSees and 0.5.3 for OpenSeesPy.
Thank you.

**Comment by zhuminjie** [comment]
Thank you for posting. it is important to do a line-by-line comparison. Sometimes, the python syntax  make you think you are doing one thing but actually doing another thing. We have compared the tcl and python for many examples, which give exactly same results. I have seen one line of python which didn't do it supposed to do changes everything. Let me know what you find.

**Comment by geosharma** [comment]
Thank you for the prompt response. I converted the ``.tcl`` file model, boundary conditions and analyses, line to line in Python. I left the recorders as it is. It still gives me a convergence error in dynamic analysis stage. Please find my python script pasted as Github gist [here](https://gist.github.com/geosharma/de1cede130bb39c8b29d51563f452b4b). Thank you once again for the help.

There are also some typos in the documentation, how do I report those. For example: element('ZeroLength', eleTag, *eleNodes, '-mat', *matTags, '-dir', *dirs[, '-doRayleigh', rFlag=0][, '-orient', *vecx, *vecyp]), but it should be 'zeroLength' instead of 'ZeroLength'. Oh, it took me half an hour to figure this out :-). I am not complaining but just want to help in small ways I can.

**Comment by zhuminjie** [comment]
Can you put the different lines of Tcl and Python here? That helps to know which line makes the difference.

Thank you!

**Comment by zhuminjie** [comment]
What are the typos you mentioned? I find that the zeroLength is in lower case already.

https://openseespydoc.readthedocs.io/en/latest/src/ZeroLength.html

**Comment by geosharma** [comment]
I was looking at this link, it may be a older version, https://openseespydoc.readthedocs.io/en/stable/ZeroLength.html

**Comment by geosharma** [comment]
When I run the analysis with these lines in the dynamic analysis:
```
    ops.constraints("Transformation")
    ops.test("NormDispIncr", 1.0e-3, 15, 5)
    ops.algorithm("Newton")
    ops.numberer("RCM")
    ops.system("ProfileSPD")
    ops.integrator("Newmark", newmark_gamma, newmark_beta)
    ops.rayleigh(alpham, betak, 0.0, 0.0)
    ops.analysis("Transient")
    ops.analyze(7990, 0.005)
```

I get 
```WARNING: CTestNormDispIncr::test() - failed to converge but going on -  current Norm: 0.0131769 (max: 0.001, Norm deltaR: 241.171)``` right from the beginning.

When the time step is changed from 0.005 to 0.002 in ``ops.analyze(7990, 0.002)`` then it completes without any warning messages.

The above lines are the same as those in the ``.tcl`` file:
```
constraints Transformation
test        NormDispIncr 1e-3 15 5
algorithm   Newton
numberer    RCM
system      ProfileSPD
integrator  Newmark $gamma $beta 
rayleigh    $a0 $a1 0.0 0.0
analysis    Transient
analyze     $nSteps  $dT
```
The nSteps=7790 and dT=0.005. The ``.tcl`` file completes without any warning.

I do not know if this is what you meant. I did not want to paste the whole code here as each file is 350 lines long. That is the reason I used the Gist for my code.

**Comment by zhuminjie** [comment]
I mean other lines of the code are exactly the same in Python and Tcl, even the data formats, such as integers and floats?

**Comment by zhuminjie** [comment]
Also when you change to dt = 0.002, does tcl and python give you the same results?

**Comment by geosharma** [comment]
I performed four analyses:

| Case | dt [s] | Algorithm | Tolerance | Maximum iteration | Agreement with `.tcl` example file |
|----|--------|------------|------------|----------------------|--------------------------------------|
| 1 | 0.002 | Newton | 1e-3 | 15 | Not good|
| 2 | 0.002 | Newton | 1e-5 | 15 | Good |
| 3 | 0.005 | KrylovNewton | 1e-3 | 50 | Not good|
| 4 | 0.005 | KrylovNewton | 1e-5 | 50 | Good |

The `.tcl` example file is the example file,  freeFieldSingle.tcl, from OpenSees website by Christopher McGann and Pedro Arduino at https://opensees.berkeley.edu/wiki/index.php/Site_Response_Analysis_of_a_Layered_Soil_Column_(Total_Stress_Analysis)

My Python script file with dt = 0.005s starts giving the non convergence message right from the beginning. The Python script file which was used for analysis can be seen/downloaded from this link https://gist.github.com/geosharma/de1cede130bb39c8b29d51563f452b4b

The matching between the original example output and the "Good" agreement cases, I presume, may at least demonstrate that the model and analysis in my Python file is correct.

Case 1:
![ex_g_02_siteresponse_totalstress_surface_groundmotion_newton_0p002_lowtolerance](https://user-images.githubusercontent.com/13501830/68886480-4b5ec180-06e5-11ea-9c38-095d9597e9d2.png)

Case 2: There may be regions where the two do not exactly match like the peak in the acceleration plot. I think that is due to recording data in the output file at dt=0.005s and performing analysis at dt=0.002s.
![ex_g_02_siteresponse_totalstress_surface_groundmotion_newton_0p002_highertolerance](https://user-images.githubusercontent.com/13501830/68886549-6cbfad80-06e5-11ea-833e-8ff39212ef35.png)

Case 3:
![ex_g_02_siteresponse_totalstress_surface_groundmotion_krylovnewton_0p005_lowtolerance](https://user-images.githubusercontent.com/13501830/68886766-cc1dbd80-06e5-11ea-95d7-f7ae3aebb7a8.png)

Case 4:
![ex_g_02_siteresponse_totalstress_surface_groundmotion_krylovnewton_0p005_hightolerance](https://user-images.githubusercontent.com/13501830/68886827-e5266e80-06e5-11ea-9379-c759ea1e3d99.png)

This goes without saying but I am once again highly thankful for all the help.

**Comment by zhuminjie** [comment]
The python and tcl should match exactly. If it doesn't, there must be some divergence in code conversion. Like I said, you want to compare the tcl and python codes line by line, and make sure all value formats are matched. By doing that, you can spot which line makes the difference, and we can discuss the reason causing that. Does this make sense to you?

**Comment by geosharma** [comment]
Ok, I will try that

**Comment by geosharma** [comment]
Ok, I have converted line by line please find attached below. For now I commented out the recorders as they have no impact. All values that need to be integers are integers, and rest are floating points. It is the same way in .tcl file too. I had done all these before too but in this file I even name the variables similarly. You can find my conversion below. I have gone through the file two or three time with the .tcl file side by side but cannot see what is different in the Python file. Maybe you can find something which I have not been able to. Thanks.
[ex_g_02_siteresponse_totalstress_tcl2py.txt](https://github.com/zhuminjie/OpenSeesPyDoc/files/3849028/ex_g_02_siteresponse_totalstress_tcl2py.txt)

**Comment by Zarhin** [comment]
I met the same problems, I think it may be the problem of the constraints method. It can be convergent when I change the constraints of the bottom nodes or uses the 'Plain' method.

**Comment by geosharma** [comment]
Thanks @Zarhin, changing the constraints from "Transformation" to "Plain" (with Newton method) does not give convergence errors for my file too. Thanks.
