### ISSUE TITLE
correct input for 'zeroLengthContact Element'

### ISSUE THREAD

**Issue by JonasWydler** [zhuminjie/OpenSeesPyDoc#98]
Hi

Somethin is wrong with my input for the zero length contact element. My code looks like:

eleType  = 'zeroLengthContact2D'
eleTag   = i + 5002
eleNodes = [i + 2002, i + 4002]
Kn       = 300.0
Kt       = 100.0
mu       = 0.2
Nx       = 0.0
Ny       = 0.0

op.element(eleType, eleTag, *eleNodes, Kn, Kt, mu, '-normal', Nx, Ny)  

which gives me:

msg: ZeroLengthContact2D:: expecting - element ZeroLengthContact2D eleTag? iNode? jNode? Kn? Kt? fs? -normal Nx? Ny?

Can anyone help me with the correct input? I also tried it with iNode and jNode seperatly but the same error message arised...

Many thanks!
Jonas

**Comment by zhuminjie** [comment]
There is a little bug. I will fix it soon. For now, you can use following. Thank you!

op.element(eleType, eleTag, *eleNodes, Kn, Kt, mu, 'normal', Nx, Ny)
