### ISSUE TITLE
stderr Output when Running in Linux

### ISSUE THREAD

**Issue by maxs3** [zhuminjie/OpenSeesPyDoc#99]
Hi Dr. Zhu

I am trying to implement parallel in Linux, however whenever I submit a job the stderr descriptors print which really slows things down. When not running in parallel I am able to suppress the stderr output using 2>&-, however when I run in parallel there seem to be instances when all output (print statements etc.) are suppressed depending on the number of processor I select.

Edit: I noticed in an earlier thread there may be some issues when running in the Unbuntu shell in Windows. Perhaps that is the issue?

![image](https://user-images.githubusercontent.com/33847705/69012858-29b05380-09df-11ea-8150-16e7fea7f5d1.png)

**Comment by zhuminjie** [comment]
I can suppress the output in the next version, or leave to users as an option. Are you using the Ubuntu shell in Windows. I never tested that. But this is probably not because of that.

**Comment by maxs3** [comment]
That would be great! Thanks!

**Comment by geosharma** [comment]
I see this too with Windows and Windows Terminal in openseepy 0.5.8. 
``python ${file} /f >nul 2>&1`` 
suppresses everything, even print statements, so it is not ideal and I have limited knowledge about terminals. So for now I have gone back to openseespy 0.5.3 
``pip install --force-install openseespy==0.5.3`` 
and will wait for the next version. Thank you.
